import type { Vertaling } from '../uiTaal'

/**
 * Afwerking voor de livegang: teksten van de familie- en zorgschermen die nog
 * vast in het Nederlands stonden (radio, foto's, onboarding, sjablonen voor
 * Home Memory, hoofdstukken van het levensboek, meldingen uit de services).
 */
export default {
  fr: {
    "Toen ik klein was": "Quand j’étais petit",
    "School en werk": "L’école et le travail",
    "Liefde en gezin": "L’amour et la famille",
    "Feesten en gewoontes": "Fêtes et traditions",
    "Reizen en plekken": "Voyages et lieux",
    "Muziek, spel en vrije tijd": "Musique, jeux et loisirs",
    "Wat ik meedraag": "Ce que je porte en moi",
    "Zoeken lukte niet.": "La recherche n'a pas réussi.",
    "Hoger": "Plus haut",
    "Lager": "Plus bas",
    "Radio 2, Nostalgie, Klara…": "Radio 2, Nostalgie, Klara…",
    "Land": "Pays",
    "België": "Belgique",
    "Nederland": "Pays-Bas",
    "Frankrijk": "France",
    "Overal": "Partout",
    "Zoek": "Chercher",
    "Vier zenders is genoeg. Verwijder er een om een andere te kiezen.": "Quatre stations suffisent. Supprimez-en une pour en choisir une autre.",
    "Niets gevonden dat in de app kan spelen. Probeer een andere naam of kies \"Overal\".": "Rien trouvé qui puisse être lu dans l’application. Essayez un autre nom ou choisissez « Partout ».",
    "Stop": "Stop",
    "Luister": "Écouter",
    "Kies": "Choisir",
    "Hoogstens {n} zenders. De bovenste speelt bij één tik op het Vandaag-scherm.": "Au maximum {n} stations. La première joue d'une seule touche sur l'écran Aujourd'hui.",
    "De foto kon niet bewaard worden.": "La photo n'a pas pu être enregistrée.",
    "Je gegevens zijn nu niet te laden": "Vos données ne peuvent pas être chargées pour l'instant",
    "Je huishouden is niet weg. Probeer het opnieuw.": "Votre foyer n'a pas disparu. Réessayez.",
    "Iemand": "Quelqu’un",
    "opende het document „{naam}”": "a ouvert le document « {naam} »",
    "opende een document": "a ouvert un document",
    "beluisterde „{naam}”": "a écouté « {naam} »",
    "beluisterde een opname": "a écouté un enregistrement",
    "bekeek de locatie": "a consulté la position",
    "Losgemaakt. De kamers en apparaten blijven bij het huis staan.": "Détaché. Les pièces et les appareils restent dans la maison.",
    "Deze twee delen het huis al.": "Ces deux personnes partagent déjà la maison.",
    "1 kamer verhuisd": "1 pièce déplacée",
    "{n} kamers verhuisd": "{n} pièces déplacées",
    "1 kamer samengevoegd": "1 pièce fusionnée",
    "{n} kamers samengevoegd": "{n} pièces fusionnées",
    "1 ding mee": "1 objet repris",
    "{n} dingen mee": "{n} objets repris",
    "{n} leeg dubbel weggelaten": "{n} doublon(s) vide(s) supprimé(s)",
    "Het huis is nu gedeeld. Er stond nog niets in om te verhuizen.": "La maison est maintenant partagée. Il n'y avait encore rien à déplacer.",
    "Het huis is nu gedeeld: {delen}.": "La maison est maintenant partagée : {delen}.",
    "Alle gegevens die LifeAngle bewaart en die jij mag zien. Bestanden (foto’s, opnames, documenten) staan hier als pad in de opslag; de bestanden zelf download je in de app.": "Toutes les données que LifeAngle conserve et que vous pouvez voir. Les fichiers (photos, enregistrements, documents) figurent ici sous forme de chemin dans le stockage ; les fichiers eux-mêmes se téléchargent dans l'application.",
    "Verwijderen lukte niet. Probeer het opnieuw.": "La suppression n'a pas réussi. Réessayez.",
    "Dit kan je niet aanpassen.": "Vous ne pouvez pas modifier ceci.",
    "Dit document heeft geen bestand": "Ce document n'a pas de fichier",
    "Dit bezoek kan je niet meer wissen.": "Vous ne pouvez plus supprimer cette visite.",
    "Medicatie van {tijdstip} bleef rond {procent} %.": "Les médicaments de {tijdstip} sont restés autour de {procent} %.",
    "De spreiding van het dagbegin bleef ongeveer gelijk.": "La variation du début de journée est restée à peu près la même.",
    "De indeling kan nog niet bewaard worden: draai supabase/27_layout.sql in de SQL-editor.": "La disposition ne peut pas encore être enregistrée : exécutez supabase/27_layout.sql dans l'éditeur SQL.",
    "De zenderlijst is nu niet bereikbaar. Probeer het straks opnieuw.": "La liste des stations n'est pas accessible pour l'instant. Réessayez plus tard.",
    "Meldingen aanzetten lukte niet. Probeer het later opnieuw.": "L'activation des notifications n'a pas réussi. Réessayez plus tard.",
    "Meldingen uitzetten lukte niet.": "La désactivation des notifications n'a pas réussi.",
    "Woonkamer": "Salon",
    "Keuken": "Cuisine",
    "Slaapkamer": "Chambre",
    "Badkamer": "Salle de bain",
    "Garage": "Garage",
    "Tuin": "Jardin",
    "Opstaan": "Se lever",
    "Medicatie nemen": "Prendre les médicaments",
    "Lunch": "Déjeuner",
    "Avondeten": "Dîner",
    "Maria Janssens": "Marie Dupont",
    "donderdag 14u dokter Janssens": "jeudi 14h docteur Dupont",
    "morgen 14u dokter": "demain 14h médecin",
    "morgen 10u kapper": "demain 10h coiffeur",
    "Wasmachine": "Machine à laver",
    "Televisie": "Télévision",
    "Oven": "Four",
    "Thermostaat": "Thermostat",
    "Medicatiedoos": "Pilulier",
    "Douche": "Douche",
    "Op het aanrecht.": "Sur le plan de travail.",
    "Vul het waterreservoir tot de streep.": "Remplissez le réservoir d'eau jusqu'au trait.",
    "Zet een kopje onder de tuit.": "Placez une tasse sous le bec.",
    "Druk op de grote knop.": "Appuyez sur le gros bouton.",
    "Wacht tot het geluid stopt.": "Attendez que le bruit s'arrête.",
    "In de bijkeuken.": "Dans l’arrière-cuisine.",
    "Doe de was in de trommel.": "Mettez le linge dans le tambour.",
    "Doe een wasdopje in het bakje.": "Mettez une dose de lessive dans le bac.",
    "Draai de knop naar 40 graden.": "Tournez le bouton sur 40 degrés.",
    "Druk op de startknop.": "Appuyez sur le bouton de démarrage.",
    "De afstandsbediening ligt op de salontafel.": "La télécommande est sur la table du salon.",
    "Neem de afstandsbediening.": "Prenez la télécommande.",
    "Druk op de rode knop bovenaan.": "Appuyez sur le bouton rouge en haut.",
    "Druk op 1 voor de eerste zender.": "Appuyez sur 1 pour la première chaîne.",
    "Het volume staat op de knop met plus en min.": "Le volume se règle avec le bouton plus et moins.",
    "Onder het aanrecht.": "Sous le plan de travail.",
    "Draai de linkerknop naar 180 graden.": "Tournez le bouton de gauche sur 180 degrés.",
    "Wacht tot het lampje uitgaat.": "Attendez que le voyant s'éteigne.",
    "Zet de schotel in het midden.": "Mettez le plat au milieu.",
    "Zet de timer.": "Réglez la minuterie.",
    "Zet het bord erin en doe de deur dicht.": "Mettez l’assiette dedans et fermez la porte.",
    "Draai de knop naar 2 minuten.": "Tournez le bouton sur 2 minutes.",
    "Druk op start.": "Appuyez sur start.",
    "Wacht tot het piept.": "Attendez le bip.",
    "Aan de muur naast de deur.": "Au mur à côté de la porte.",
    "Draai het wiel naar rechts voor warmer.": "Tournez la molette vers la droite pour plus chaud.",
    "20 graden is een goede temperatuur.": "20 degrés est une bonne température.",
    "Niet hoger dan 22 graden zetten.": "Ne pas régler au-dessus de 22 degrés.",
    "Op het kastje naast de zetel.": "Sur le meuble à côté du fauteuil.",
    "Neem de hoorn van het toestel.": "Décrochez le combiné.",
    "In de kast boven de koffie.": "Dans l’armoire au-dessus du café.",
    "Zoek het vakje van vandaag.": "Cherchez la case d'aujourd'hui.",
    "Neem de pillen met een glas water.": "Prenez les comprimés avec un verre d'eau.",
    "Vink af in de app.": "Cochez dans l'application.",
    "Op het nachtkastje.": "Sur la table de nuit.",
    "Kijk eerst op het nachtkastje.": "Regardez d'abord sur la table de nuit.",
    "Anders: op de tafel in de woonkamer.": "Sinon : sur la table du salon.",
    "Anders: bel je familie.": "Sinon : appelez votre famille.",
    "De handdoeken liggen in de kast.": "Les serviettes sont dans l'armoire.",
    "Draai de linkerkraan open voor warm water.": "Ouvrez le robinet de gauche pour l’eau chaude.",
    "Wacht tot het water warm is.": "Attendez que l'eau soit chaude.",
    "De mat ligt klaar op de vloer.": "Le tapis est prêt sur le sol.",
  },
  en: {
    "Toen ik klein was": "When I was little",
    "School en werk": "School and work",
    "Liefde en gezin": "Love and family",
    "Feesten en gewoontes": "Celebrations and customs",
    "Reizen en plekken": "Travels and places",
    "Muziek, spel en vrije tijd": "Music, games and free time",
    "Wat ik meedraag": "What I carry with me",
    "Zoeken lukte niet.": "Search did not work.",
    "Hoger": "Up",
    "Lager": "Down",
    "Radio 2, Nostalgie, Klara…": "Radio 2, Nostalgie, Klara…",
    "Land": "Country",
    "België": "Belgium",
    "Nederland": "Netherlands",
    "Frankrijk": "France",
    "Overal": "Everywhere",
    "Zoek": "Search",
    "Vier zenders is genoeg. Verwijder er een om een andere te kiezen.": "Four stations is enough. Remove one to choose another.",
    "Niets gevonden dat in de app kan spelen. Probeer een andere naam of kies \"Overal\".": "Nothing found that can play in the app. Try another name or choose \"Everywhere\".",
    "Stop": "Stop",
    "Luister": "Listen",
    "Kies": "Choose",
    "Hoogstens {n} zenders. De bovenste speelt bij één tik op het Vandaag-scherm.": "At most {n} stations. The top one plays with one tap on the Today screen.",
    "De foto kon niet bewaard worden.": "The photo could not be saved.",
    "Je gegevens zijn nu niet te laden": "Your data cannot be loaded right now",
    "Je huishouden is niet weg. Probeer het opnieuw.": "Your household is not gone. Please try again.",
    "Iemand": "Someone",
    "opende het document „{naam}”": "opened the document “{naam}”",
    "opende een document": "opened a document",
    "beluisterde „{naam}”": "listened to “{naam}”",
    "beluisterde een opname": "listened to a recording",
    "bekeek de locatie": "viewed the location",
    "Losgemaakt. De kamers en apparaten blijven bij het huis staan.": "Separated. The rooms and appliances stay with the house.",
    "Deze twee delen het huis al.": "These two already share the house.",
    "1 kamer verhuisd": "1 room moved",
    "{n} kamers verhuisd": "{n} rooms moved",
    "1 kamer samengevoegd": "1 room merged",
    "{n} kamers samengevoegd": "{n} rooms merged",
    "1 ding mee": "1 item moved",
    "{n} dingen mee": "{n} items moved",
    "{n} leeg dubbel weggelaten": "{n} empty duplicate(s) left out",
    "Het huis is nu gedeeld. Er stond nog niets in om te verhuizen.": "The house is now shared. There was nothing in it to move yet.",
    "Het huis is nu gedeeld: {delen}.": "The house is now shared: {delen}.",
    "Alle gegevens die LifeAngle bewaart en die jij mag zien. Bestanden (foto’s, opnames, documenten) staan hier als pad in de opslag; de bestanden zelf download je in de app.": "All data LifeAngle keeps that you are allowed to see. Files (photos, recordings, documents) appear here as a path in storage; you download the files themselves in the app.",
    "Verwijderen lukte niet. Probeer het opnieuw.": "Deleting did not work. Please try again.",
    "Dit kan je niet aanpassen.": "You cannot change this.",
    "Dit document heeft geen bestand": "This document has no file",
    "Dit bezoek kan je niet meer wissen.": "You can no longer delete this visit.",
    "Medicatie van {tijdstip} bleef rond {procent} %.": "Medication at {tijdstip} stayed around {procent}%.",
    "De spreiding van het dagbegin bleef ongeveer gelijk.": "The spread of the start of the day stayed about the same.",
    "De indeling kan nog niet bewaard worden: draai supabase/27_layout.sql in de SQL-editor.": "The layout cannot be saved yet: run supabase/27_layout.sql in the SQL editor.",
    "De zenderlijst is nu niet bereikbaar. Probeer het straks opnieuw.": "The station list cannot be reached right now. Try again later.",
    "Meldingen aanzetten lukte niet. Probeer het later opnieuw.": "Turning on notifications did not work. Try again later.",
    "Meldingen uitzetten lukte niet.": "Turning off notifications did not work.",
    "Woonkamer": "Living room",
    "Keuken": "Kitchen",
    "Slaapkamer": "Bedroom",
    "Badkamer": "Bathroom",
    "Garage": "Garage",
    "Tuin": "Garden",
    "Opstaan": "Get up",
    "Medicatie nemen": "Take medication",
    "Lunch": "Lunch",
    "Avondeten": "Dinner",
    "Maria Janssens": "Mary Smith",
    "donderdag 14u dokter Janssens": "thursday 2pm doctor Smith",
    "morgen 14u dokter": "tomorrow 2pm doctor",
    "morgen 10u kapper": "tomorrow 10am hairdresser",
    "Wasmachine": "Washing machine",
    "Televisie": "Television",
    "Oven": "Oven",
    "Thermostaat": "Thermostat",
    "Medicatiedoos": "Pill box",
    "Douche": "Shower",
    "Op het aanrecht.": "On the kitchen counter.",
    "Vul het waterreservoir tot de streep.": "Fill the water tank up to the line.",
    "Zet een kopje onder de tuit.": "Put a cup under the spout.",
    "Druk op de grote knop.": "Press the big button.",
    "Wacht tot het geluid stopt.": "Wait until the noise stops.",
    "In de bijkeuken.": "In the utility room.",
    "Doe de was in de trommel.": "Put the laundry in the drum.",
    "Doe een wasdopje in het bakje.": "Put a dose of detergent in the drawer.",
    "Draai de knop naar 40 graden.": "Turn the dial to 40 degrees.",
    "Druk op de startknop.": "Press the start button.",
    "De afstandsbediening ligt op de salontafel.": "The remote control is on the coffee table.",
    "Neem de afstandsbediening.": "Take the remote control.",
    "Druk op de rode knop bovenaan.": "Press the red button at the top.",
    "Druk op 1 voor de eerste zender.": "Press 1 for the first channel.",
    "Het volume staat op de knop met plus en min.": "The volume is on the plus and minus button.",
    "Onder het aanrecht.": "Under the kitchen counter.",
    "Draai de linkerknop naar 180 graden.": "Turn the left dial to 180 degrees.",
    "Wacht tot het lampje uitgaat.": "Wait until the light goes out.",
    "Zet de schotel in het midden.": "Put the dish in the middle.",
    "Zet de timer.": "Set the timer.",
    "Zet het bord erin en doe de deur dicht.": "Put the plate in and close the door.",
    "Draai de knop naar 2 minuten.": "Turn the dial to 2 minutes.",
    "Druk op start.": "Press start.",
    "Wacht tot het piept.": "Wait for the beep.",
    "Aan de muur naast de deur.": "On the wall next to the door.",
    "Draai het wiel naar rechts voor warmer.": "Turn the wheel to the right for warmer.",
    "20 graden is een goede temperatuur.": "20 degrees is a good temperature.",
    "Niet hoger dan 22 graden zetten.": "Do not set it higher than 22 degrees.",
    "Op het kastje naast de zetel.": "On the cabinet next to the armchair.",
    "Neem de hoorn van het toestel.": "Pick up the handset.",
    "In de kast boven de koffie.": "In the cupboard above the coffee.",
    "Zoek het vakje van vandaag.": "Find today's compartment.",
    "Neem de pillen met een glas water.": "Take the pills with a glass of water.",
    "Vink af in de app.": "Tick it off in the app.",
    "Op het nachtkastje.": "On the bedside table.",
    "Kijk eerst op het nachtkastje.": "Look on the bedside table first.",
    "Anders: op de tafel in de woonkamer.": "Otherwise: on the table in the living room.",
    "Anders: bel je familie.": "Otherwise: call your family.",
    "De handdoeken liggen in de kast.": "The towels are in the cupboard.",
    "Draai de linkerkraan open voor warm water.": "Turn on the left tap for hot water.",
    "Wacht tot het water warm is.": "Wait until the water is warm.",
    "De mat ligt klaar op de vloer.": "The mat is ready on the floor.",
  },
} satisfies Vertaling
