import type { Vertaling } from '../uiTaal'

/**
 * Foutmeldingen die de database (raise exception in supabase/*.sql) en de
 * edge functions (supabase/functions/*) in het Nederlands teruggeven. De app
 * toont ze via foutTekst() → tt(message); de sleutel is de exacte tekst.
 * Meldingen met een variabele (format/%s) staan hier niet: die vallen terug
 * op het Nederlands.
 */
export default {
  fr: {
    // supabase/*.sql
    'Alleen de beheerder of een coördinator past het verblijf aan': "Seul l'administrateur ou un coordinateur peut modifier le séjour",
    'Alleen de beheerder of een coördinator van het woonzorgcentrum': "Réservé à l'administrateur ou à un coordinateur de la maison de repos",
    'Alleen de beheerder of een coördinator ziet de rapporten': "Seul l'administrateur ou un coordinateur peut voir les rapports",
    'Alleen de beheerder van de organisatie': "Réservé à l'administrateur de l'organisation",
    'Alleen de beheerder van de organisatie nodigt medewerkers uit': "Seul l'administrateur de l'organisation peut inviter des collaborateurs",
    'Alleen de beheerder van dit huishouden kan dit wijzigen': "Seul l'administrateur de ce foyer peut modifier ceci",
    'Alleen de bewoner zelf stuurt een bericht aan het zorgteam': "Seul le résident lui-même peut envoyer un message à l'équipe de soins",
    'Alleen de familiebeheerder kan de koppeling stoppen': "Seul l'administrateur familial peut arrêter la liaison",
    'Alleen de familiebeheerder kan een huishouden koppelen': "Seul l'administrateur familial peut lier un foyer",
    'Alleen de familiebeheerder kan een uitnodiging intrekken': "Seul l'administrateur familial peut retirer une invitation",
    'Alleen de familiebeheerder kan iemand uitnodigen': "Seul l'administrateur familial peut inviter quelqu'un",
    'Alleen de persoon zelf kan dit wijzigen': 'Seule la personne elle-même peut modifier ceci',
    'Alleen de persoon zelf kan hierop antwoorden': 'Seule la personne elle-même peut répondre à ceci',
    'Alleen de persoon zelf of de beheerder kan dit wijzigen': "Seule la personne elle-même ou l'administrateur peut modifier ceci",
    'Alleen een beheerder of coördinator kan toewijzen': 'Seul un administrateur ou un coordinateur peut attribuer',
    'Alleen een coördinator of zorgmedewerker van deze organisatie kan op een afdeling staan':
      'Seul un coordinateur ou un soignant de cette organisation peut être affecté à une unité',
    'Alleen een lopend verblijf kan een toewijzing krijgen': 'Seul un séjour en cours peut recevoir une attribution',
    'Alleen een medewerker van deze organisatie kan toegewezen worden': 'Seul un collaborateur de cette organisation peut être attribué',
    'Alleen familie kan de dag klaarzetten': 'Seule la famille peut préparer la journée',
    'Alleen familie kan de voorraad bijwerken': 'Seule la famille peut mettre à jour le stock',
    'Alleen familie kan een bezoek plannen': 'Seule la famille peut planifier une visite',
    'Alleen familie kan een kanaal instellen': 'Seule la famille peut configurer un canal',
    'Alleen familie kan een tablet koppelen': 'Seule la famille peut lier une tablette',
    'Alleen familie kan een testmelding sturen': 'Seule la famille peut envoyer une notification de test',
    'Alleen familie kan het medicatieschema wijzigen': 'Seule la famille peut modifier le schéma de médication',
    'Alleen familie kan het verslag samenstellen': 'Seule la famille peut rédiger le rapport',
    'Alleen familie kan iets loslaten': 'Seule la famille peut libérer une tâche',
    'Alleen familie kan iets opnemen': 'Seule la famille peut prendre une tâche en charge',
    'Alleen het zorgteam duidt aanwezigheid aan': "Seule l'équipe de soins indique la présence",
    'Archiveer een afdeling via Beheer': 'Archivez une unité via Gestion',
    'Bij dit huishouden woont al iemand in huis': "Quelqu'un habite déjà dans ce foyer",
    'Dat heeft iemand anders opgenomen': "Quelqu'un d'autre s'en est déjà chargé",
    'Dat huishouden woont zelf al bij iemand anders in': "Ce foyer habite déjà lui-même chez quelqu'un d'autre",
    'Dat kan nu niet meer': "Ce n'est plus possible maintenant",
    'De reden mag hoogstens 500 tekens zijn': 'Le motif peut compter au maximum 500 caractères',
    'Deze afdeling hoort niet bij deze organisatie': "Cette unité n'appartient pas à cette organisation",
    'Deze afdeling is gearchiveerd': 'Cette unité est archivée',
    'Deze bewoner heeft geen lopend verblijf': "Ce résident n'a pas de séjour en cours",
    'Deze bewoner verblijft niet (meer) in een woonzorgcentrum': "Ce résident ne séjourne pas (plus) dans une maison de repos",
    'Deze bewoner verblijft niet in een organisatie waar jij team lead bent':
      "Ce résident ne séjourne pas dans une organisation où vous êtes chef d'équipe",
    'Deze code kennen we niet. Kijk ze na of vraag ze opnieuw aan het woonzorgcentrum.':
      'Nous ne connaissons pas ce code. Vérifiez-le ou redemandez-le à la maison de repos.',
    'Deze kaart kan je niet zelf aanmaken': 'Vous ne pouvez pas créer cette fiche vous-même',
    'Deze noodtoegang is niet (meer) actief': "Cet accès d'urgence n'est pas (plus) actif",
    'Deze soort kan niet via spraak': "Ce type n'est pas possible par la voix",
    'Deze taak is ondertussen al opgenomen': 'Cette tâche a entre-temps déjà été prise en charge',
    'Deze uitnodiging bestaat niet': "Cette invitation n'existe pas",
    'Deze uitnodiging is al aanvaard': 'Cette invitation a déjà été acceptée',
    'Deze uitnodiging is al gebruikt': 'Cette invitation a déjà été utilisée',
    'Deze uitnodiging is ingetrokken': 'Cette invitation a été retirée',
    'Deze uitnodiging is ingetrokken. Maak een nieuwe.': 'Cette invitation a été retirée. Créez-en une nouvelle.',
    'Deze uitnodiging is verlopen. Vraag een nieuwe.': 'Cette invitation a expiré. Demandez-en une nouvelle.',
    'Deze uitstap vind ik niet': 'Je ne trouve pas cette sortie',
    'Die afdeling hoort niet bij deze organisatie': "Cette unité n'appartient pas à cette organisation",
    'Die afspraak bestaat niet': "Ce rendez-vous n'existe pas",
    'Die persoon hoort niet bij de familie van dit huishouden': "Cette personne ne fait pas partie de la famille de ce foyer",
    'Die persoon hoort niet bij dit huishouden': "Cette personne ne fait pas partie de ce foyer",
    'Die persoon werkt niet voor deze organisatie': 'Cette personne ne travaille pas pour cette organisation',
    'Dit bericht staat niet op het scherm van de persoon': "Ce message n'est pas affiché sur l'écran de la personne",
    'Dit huishouden hoort niet bij een organisatie': "Ce foyer n'appartient à aucune organisation",
    'Dit vind ik niet': 'Je ne trouve pas ceci',
    'Document niet gevonden': 'Document introuvable',
    'Draai eerst 49_can_legacy.sql': "Exécutez d'abord 49_can_legacy.sql",
    'Draai eerst 50_policies_groep1.sql': "Exécutez d'abord 50_policies_groep1.sql",
    'Draai eerst 52_stays.sql': "Exécutez d'abord 52_stays.sql",
    'Draai eerst 52_stays.sql en 70_medewerkers_beheren.sql': "Exécutez d'abord 52_stays.sql et 70_medewerkers_beheren.sql",
    'Draai eerst 53_org_zonder_inhoud.sql': "Exécutez d'abord 53_org_zonder_inhoud.sql",
    'Draai eerst 54_noodtoegang.sql': "Exécutez d'abord 54_noodtoegang.sql",
    'Draai eerst 58_abonnementen.sql': "Exécutez d'abord 58_abonnementen.sql",
    'Draai eerst 59_zorg.sql': "Exécutez d'abord 59_zorg.sql",
    'Draai eerst 60_personeel.sql': "Exécutez d'abord 60_personeel.sql",
    'Draai eerst 61_bewaartermijn.sql': "Exécutez d'abord 61_bewaartermijn.sql",
    'Draai eerst 74_bezoekboek.sql': "Exécutez d'abord 74_bezoekboek.sql",
    'Draai eerst 79_nieuws_wzc.sql en 80_uitstap.sql': "Exécutez d'abord 79_nieuws_wzc.sql et 80_uitstap.sql",
    'Een Care-plan hoort bij een organisatie, een Home-plan bij een huishouden':
      'Un abonnement Care appartient à une organisation, un abonnement Home à un foyer',
    'Een Telegram chat-id is een getal, bijvoorbeeld 123456789': 'Un identifiant de chat Telegram est un nombre, par exemple 123456789',
    'Een bezoek ligt niet in de toekomst': 'Une visite ne peut pas se situer dans le futur',
    'Een bezoek van meer dan 14 dagen geleden leg je niet meer vast': "Une visite de plus de 14 jours ne s'enregistre plus",
    'Een correctie hoort bij dezelfde bewoner': 'Une correction concerne le même résident',
    'Een huishouden kan niet bij zichzelf inwonen': 'Un foyer ne peut pas habiter chez lui-même',
    'Een indeling heeft een lijst tegels': 'Une disposition contient une liste de tuiles',
    'Een uitstap van langer dan een dag geleden meld je niet meer': "Une sortie de plus d'un jour ne se signale plus",
    'Een voorraad kan niet negatief zijn': 'Un stock ne peut pas être négatif',
    'Er is geen woonzorgcentrum gekoppeld': "Aucune maison de repos n'est liée",
    'GEZAKT: de persoon kon een agenda-item toevoegen': "ÉCHEC : la personne a pu ajouter un élément à l'agenda",
    'GEZAKT: de persoon kon niet afvinken via mark_done()': "ÉCHEC : la personne n'a pas pu cocher via mark_done()",
    'GEZAKT: de persoon ziet zijn eigen logboek niet': 'ÉCHEC : la personne ne voit pas son propre journal',
    'GEZAKT: een buitenstaander kon afvinken': 'ÉCHEC : une personne extérieure a pu cocher',
    'GEZAKT: een familielid kon zichzelf of iemand anders beheerder maken':
      "ÉCHEC : un membre de la famille a pu se nommer administrateur ou nommer quelqu'un d'autre",
    'GEZAKT: familie ziet de agenda niet meer in de zelfstandige fase': "ÉCHEC : la famille ne voit plus l'agenda en phase autonome",
    'GEZAKT: zorgverlener kon een logboekregel wissen': 'ÉCHEC : un soignant a pu effacer une ligne du journal',
    'Geef een reden van minstens 20 tekens': "Indiquez un motif d'au moins 20 caractères",
    'Geen geldig e-mailadres': 'Adresse e-mail non valide',
    'Geen recht om de agenda te wijzigen': "Pas le droit de modifier l'agenda",
    'Geen recht om de boodschappenlijst te wijzigen': 'Pas le droit de modifier la liste de courses',
    'Geen recht om de indeling te wijzigen': 'Pas le droit de modifier la disposition',
    'Geen recht om de instellingen te wijzigen': 'Pas le droit de modifier les paramètres',
    'Geen recht om de locatie-instelling te wijzigen': 'Pas le droit de modifier le paramètre de localisation',
    'Geen recht om deze toewijzing te stoppen': "Pas le droit d'arrêter cette attribution",
    'Geen recht om dit profiel te wijzigen': 'Pas le droit de modifier ce profil',
    'Geen toegang': "Pas d'accès",
    'Geen toegang tot dit bericht': "Pas d'accès à ce message",
    'Geen toegang tot dit huishouden': "Pas d'accès à ce foyer",
    'Het antwoord is leeg': 'La réponse est vide',
    'Het bericht is leeg': 'Le message est vide',
    'Je hebt al een lopende noodtoegang voor deze bewoner': "Vous avez déjà un accès d'urgence en cours pour ce résident",
    'Je hebt al gewone toegang tot deze bewoner': 'Vous avez déjà un accès normal à ce résident',
    'Je hebt al veel berichten gestuurd. Het zorgteam komt zo snel mogelijk.':
      "Vous avez déjà envoyé beaucoup de messages. L'équipe de soins arrive dès que possible.",
    'Je hebt de afgelopen 24 uur al 3 keer noodtoegang gestart':
      "Vous avez déjà lancé un accès d'urgence 3 fois au cours des dernières 24 heures",
    'Je kan deze noodtoegang niet stoppen': "Vous ne pouvez pas arrêter cet accès d'urgence",
    'Je kan deze toewijzing niet stoppen': 'Vous ne pouvez pas arrêter cette attribution',
    'Je kan je eigen rol in de organisatie niet aanpassen': "Vous ne pouvez pas modifier votre propre rôle dans l'organisation",
    'Je kan jezelf niet op een afdeling zetten': 'Vous ne pouvez pas vous affecter vous-même à une unité',
    'Je kan jezelf niet toewijzen': 'Vous ne pouvez pas vous attribuer vous-même',
    'Je kan voor deze bewoner niemand toewijzen': "Vous ne pouvez attribuer personne à ce résident",
    'Je moet ook beheerder zijn van het huishouden waar je bij intrekt':
      "Vous devez aussi être administrateur du foyer où vous emménagez",
    'Kies een periode van hoogstens een jaar': "Choisissez une période d'un an maximum",
    'Kies een reden: verhuisd, overleden of andere': 'Choisissez un motif : déménagé, décédé ou autre',
    'Kies een termijn tussen 6 en 120 maanden': 'Choisissez un délai entre 6 et 120 mois',
    'Kies een termijn tussen 7 en 365 dagen': 'Choisissez un délai entre 7 et 365 jours',
    'Log eerst in met je eigen e-mailadres': "Connectez-vous d'abord avec votre propre adresse e-mail",
    'Niet aangemeld': 'Non connecté',
    'Niet ingelogd': 'Non connecté',
    'Onbekend agenda-item': "Élément d'agenda inconnu",
    'Onbekend bericht': 'Message inconnu',
    'Onbekend huishouden': 'Foyer inconnu',
    'Onbekend medicatiemoment': 'Moment de médication inconnu',
    'Onbekend medicijn': 'Médicament inconnu',
    'Onbekend niveau': 'Niveau inconnu',
    'Onbekende oproep': 'Appel inconnu',
    'Onbekende organisatie': 'Organisation inconnue',
    'Onbekende rol': 'Rôle inconnu',
    'Onbekende uitnodiging': 'Invitation inconnue',
    'Ongeldig tijdstip': 'Moment non valide',
    'Ongeldige lijst': 'Liste non valide',
    'Ongeldige titel': 'Titre non valide',
    'Te veel pogingen. Probeer het over een uur opnieuw.': 'Trop de tentatives. Réessayez dans une heure.',
    'Verhaal niet gevonden': 'Histoire introuvable',
    'Wie deze kaart is, kan je niet aanpassen': 'Vous ne pouvez pas modifier à qui appartient cette fiche',
    'Zet het nummer in internationaal formaat, bijvoorbeeld +32475123456':
      'Indiquez le numéro au format international, par exemple +32475123456',
    'Zo veel tegels bestaan er niet; dit is geen geldige indeling': "Il n'existe pas autant de tuiles ; cette disposition n'est pas valide",

    // supabase/functions/*/index.ts
    'household_id of vraag ontbreekt': 'household_id ou question manquant',
    'Te veel pogingen. Wacht een kwartier en probeer opnieuw.': "Trop de tentatives. Attendez un quart d'heure et réessayez.",
    'Deze code klopt niet of is verlopen. Vraag een nieuwe.': "Ce code n'est pas correct ou a expiré. Demandez-en un nouveau.",
    'invite_id ontbreekt': 'invite_id manquant',
    'Uitnodiging niet gevonden': 'Invitation introuvable',
    'niet ingelogd': 'non connecté',
    'Alleen met de service role': 'Uniquement avec le service role',
    'Onbekende fout': 'Erreur inconnue',
    'Verwijderen mislukt': 'La suppression a échoué',
    'Koppelen mislukt': 'La liaison a échoué',
    'onbekend': 'inconnu',
  },
  en: {
    // supabase/*.sql
    'Alleen de beheerder of een coördinator past het verblijf aan': 'Only the administrator or a coordinator can change the stay',
    'Alleen de beheerder of een coördinator van het woonzorgcentrum': 'Only the administrator or a coordinator of the care home',
    'Alleen de beheerder of een coördinator ziet de rapporten': 'Only the administrator or a coordinator can see the reports',
    'Alleen de beheerder van de organisatie': 'Only the administrator of the organisation',
    'Alleen de beheerder van de organisatie nodigt medewerkers uit': 'Only the administrator of the organisation can invite staff',
    'Alleen de beheerder van dit huishouden kan dit wijzigen': 'Only the administrator of this household can change this',
    'Alleen de bewoner zelf stuurt een bericht aan het zorgteam': 'Only the resident themselves can send a message to the care team',
    'Alleen de familiebeheerder kan de koppeling stoppen': 'Only the family administrator can stop the link',
    'Alleen de familiebeheerder kan een huishouden koppelen': 'Only the family administrator can link a household',
    'Alleen de familiebeheerder kan een uitnodiging intrekken': 'Only the family administrator can withdraw an invitation',
    'Alleen de familiebeheerder kan iemand uitnodigen': 'Only the family administrator can invite someone',
    'Alleen de persoon zelf kan dit wijzigen': 'Only the person themselves can change this',
    'Alleen de persoon zelf kan hierop antwoorden': 'Only the person themselves can reply to this',
    'Alleen de persoon zelf of de beheerder kan dit wijzigen': 'Only the person themselves or the administrator can change this',
    'Alleen een beheerder of coördinator kan toewijzen': 'Only an administrator or coordinator can assign',
    'Alleen een coördinator of zorgmedewerker van deze organisatie kan op een afdeling staan':
      'Only a coordinator or care worker of this organisation can be placed on a unit',
    'Alleen een lopend verblijf kan een toewijzing krijgen': 'Only an ongoing stay can be given an assignment',
    'Alleen een medewerker van deze organisatie kan toegewezen worden': 'Only a staff member of this organisation can be assigned',
    'Alleen familie kan de dag klaarzetten': 'Only family can prepare the day',
    'Alleen familie kan de voorraad bijwerken': 'Only family can update the stock',
    'Alleen familie kan een bezoek plannen': 'Only family can plan a visit',
    'Alleen familie kan een kanaal instellen': 'Only family can set up a channel',
    'Alleen familie kan een tablet koppelen': 'Only family can link a tablet',
    'Alleen familie kan een testmelding sturen': 'Only family can send a test notification',
    'Alleen familie kan het medicatieschema wijzigen': 'Only family can change the medication schedule',
    'Alleen familie kan het verslag samenstellen': 'Only family can compile the report',
    'Alleen familie kan iets loslaten': 'Only family can release a task',
    'Alleen familie kan iets opnemen': 'Only family can take on a task',
    'Alleen het zorgteam duidt aanwezigheid aan': 'Only the care team can mark attendance',
    'Archiveer een afdeling via Beheer': 'Archive a unit via Management',
    'Bij dit huishouden woont al iemand in huis': 'Someone already lives in with this household',
    'Dat heeft iemand anders opgenomen': 'Someone else has already taken that on',
    'Dat huishouden woont zelf al bij iemand anders in': 'That household already lives in with someone else',
    'Dat kan nu niet meer': 'That is no longer possible',
    'De reden mag hoogstens 500 tekens zijn': 'The reason may be at most 500 characters',
    'Deze afdeling hoort niet bij deze organisatie': 'This unit does not belong to this organisation',
    'Deze afdeling is gearchiveerd': 'This unit has been archived',
    'Deze bewoner heeft geen lopend verblijf': 'This resident has no ongoing stay',
    'Deze bewoner verblijft niet (meer) in een woonzorgcentrum': 'This resident is not (or no longer) staying in a care home',
    'Deze bewoner verblijft niet in een organisatie waar jij team lead bent':
      'This resident is not staying in an organisation where you are team lead',
    'Deze code kennen we niet. Kijk ze na of vraag ze opnieuw aan het woonzorgcentrum.':
      'We do not recognise this code. Check it or ask the care home for it again.',
    'Deze kaart kan je niet zelf aanmaken': 'You cannot create this card yourself',
    'Deze noodtoegang is niet (meer) actief': 'This emergency access is not (or no longer) active',
    'Deze soort kan niet via spraak': 'This type is not possible by voice',
    'Deze taak is ondertussen al opgenomen': 'This task has already been taken on in the meantime',
    'Deze uitnodiging bestaat niet': 'This invitation does not exist',
    'Deze uitnodiging is al aanvaard': 'This invitation has already been accepted',
    'Deze uitnodiging is al gebruikt': 'This invitation has already been used',
    'Deze uitnodiging is ingetrokken': 'This invitation has been withdrawn',
    'Deze uitnodiging is ingetrokken. Maak een nieuwe.': 'This invitation has been withdrawn. Create a new one.',
    'Deze uitnodiging is verlopen. Vraag een nieuwe.': 'This invitation has expired. Ask for a new one.',
    'Deze uitstap vind ik niet': 'I cannot find this outing',
    'Die afdeling hoort niet bij deze organisatie': 'That unit does not belong to this organisation',
    'Die afspraak bestaat niet': 'That appointment does not exist',
    'Die persoon hoort niet bij de familie van dit huishouden': "That person is not part of this household's family",
    'Die persoon hoort niet bij dit huishouden': 'That person is not part of this household',
    'Die persoon werkt niet voor deze organisatie': 'That person does not work for this organisation',
    'Dit bericht staat niet op het scherm van de persoon': "This message is not on the person's screen",
    'Dit huishouden hoort niet bij een organisatie': 'This household does not belong to an organisation',
    'Dit vind ik niet': 'I cannot find this',
    'Document niet gevonden': 'Document not found',
    'Draai eerst 49_can_legacy.sql': 'Run 49_can_legacy.sql first',
    'Draai eerst 50_policies_groep1.sql': 'Run 50_policies_groep1.sql first',
    'Draai eerst 52_stays.sql': 'Run 52_stays.sql first',
    'Draai eerst 52_stays.sql en 70_medewerkers_beheren.sql': 'Run 52_stays.sql and 70_medewerkers_beheren.sql first',
    'Draai eerst 53_org_zonder_inhoud.sql': 'Run 53_org_zonder_inhoud.sql first',
    'Draai eerst 54_noodtoegang.sql': 'Run 54_noodtoegang.sql first',
    'Draai eerst 58_abonnementen.sql': 'Run 58_abonnementen.sql first',
    'Draai eerst 59_zorg.sql': 'Run 59_zorg.sql first',
    'Draai eerst 60_personeel.sql': 'Run 60_personeel.sql first',
    'Draai eerst 61_bewaartermijn.sql': 'Run 61_bewaartermijn.sql first',
    'Draai eerst 74_bezoekboek.sql': 'Run 74_bezoekboek.sql first',
    'Draai eerst 79_nieuws_wzc.sql en 80_uitstap.sql': 'Run 79_nieuws_wzc.sql and 80_uitstap.sql first',
    'Een Care-plan hoort bij een organisatie, een Home-plan bij een huishouden':
      'A Care plan belongs to an organisation, a Home plan to a household',
    'Een Telegram chat-id is een getal, bijvoorbeeld 123456789': 'A Telegram chat ID is a number, for example 123456789',
    'Een bezoek ligt niet in de toekomst': 'A visit cannot be in the future',
    'Een bezoek van meer dan 14 dagen geleden leg je niet meer vast': 'A visit from more than 14 days ago can no longer be recorded',
    'Een correctie hoort bij dezelfde bewoner': 'A correction must concern the same resident',
    'Een huishouden kan niet bij zichzelf inwonen': 'A household cannot live in with itself',
    'Een indeling heeft een lijst tegels': 'A layout has a list of tiles',
    'Een uitstap van langer dan een dag geleden meld je niet meer': 'An outing from more than a day ago can no longer be reported',
    'Een voorraad kan niet negatief zijn': 'Stock cannot be negative',
    'Er is geen woonzorgcentrum gekoppeld': 'No care home is linked',
    'GEZAKT: de persoon kon een agenda-item toevoegen': 'FAILED: the person was able to add a calendar item',
    'GEZAKT: de persoon kon niet afvinken via mark_done()': 'FAILED: the person could not tick off via mark_done()',
    'GEZAKT: de persoon ziet zijn eigen logboek niet': 'FAILED: the person cannot see their own log',
    'GEZAKT: een buitenstaander kon afvinken': 'FAILED: an outsider was able to tick off',
    'GEZAKT: een familielid kon zichzelf of iemand anders beheerder maken':
      'FAILED: a family member was able to make themselves or someone else administrator',
    'GEZAKT: familie ziet de agenda niet meer in de zelfstandige fase': 'FAILED: family can no longer see the calendar in the independent phase',
    'GEZAKT: zorgverlener kon een logboekregel wissen': 'FAILED: a carer was able to delete a log entry',
    'Geef een reden van minstens 20 tekens': 'Give a reason of at least 20 characters',
    'Geen geldig e-mailadres': 'Not a valid email address',
    'Geen recht om de agenda te wijzigen': 'No permission to change the calendar',
    'Geen recht om de boodschappenlijst te wijzigen': 'No permission to change the shopping list',
    'Geen recht om de indeling te wijzigen': 'No permission to change the layout',
    'Geen recht om de instellingen te wijzigen': 'No permission to change the settings',
    'Geen recht om de locatie-instelling te wijzigen': 'No permission to change the location setting',
    'Geen recht om deze toewijzing te stoppen': 'No permission to stop this assignment',
    'Geen recht om dit profiel te wijzigen': 'No permission to change this profile',
    'Geen toegang': 'No access',
    'Geen toegang tot dit bericht': 'No access to this message',
    'Geen toegang tot dit huishouden': 'No access to this household',
    'Het antwoord is leeg': 'The reply is empty',
    'Het bericht is leeg': 'The message is empty',
    'Je hebt al een lopende noodtoegang voor deze bewoner': 'You already have ongoing emergency access for this resident',
    'Je hebt al gewone toegang tot deze bewoner': 'You already have regular access to this resident',
    'Je hebt al veel berichten gestuurd. Het zorgteam komt zo snel mogelijk.':
      'You have already sent a lot of messages. The care team will come as soon as possible.',
    'Je hebt de afgelopen 24 uur al 3 keer noodtoegang gestart': 'You have already started emergency access 3 times in the last 24 hours',
    'Je kan deze noodtoegang niet stoppen': 'You cannot stop this emergency access',
    'Je kan deze toewijzing niet stoppen': 'You cannot stop this assignment',
    'Je kan je eigen rol in de organisatie niet aanpassen': 'You cannot change your own role in the organisation',
    'Je kan jezelf niet op een afdeling zetten': 'You cannot place yourself on a unit',
    'Je kan jezelf niet toewijzen': 'You cannot assign yourself',
    'Je kan voor deze bewoner niemand toewijzen': 'You cannot assign anyone to this resident',
    'Je moet ook beheerder zijn van het huishouden waar je bij intrekt':
      'You must also be an administrator of the household you are moving in with',
    'Kies een periode van hoogstens een jaar': 'Choose a period of at most one year',
    'Kies een reden: verhuisd, overleden of andere': 'Choose a reason: moved, deceased or other',
    'Kies een termijn tussen 6 en 120 maanden': 'Choose a period between 6 and 120 months',
    'Kies een termijn tussen 7 en 365 dagen': 'Choose a period between 7 and 365 days',
    'Log eerst in met je eigen e-mailadres': 'Sign in first with your own email address',
    'Niet aangemeld': 'Not signed in',
    'Niet ingelogd': 'Not signed in',
    'Onbekend agenda-item': 'Unknown calendar item',
    'Onbekend bericht': 'Unknown message',
    'Onbekend huishouden': 'Unknown household',
    'Onbekend medicatiemoment': 'Unknown medication time',
    'Onbekend medicijn': 'Unknown medicine',
    'Onbekend niveau': 'Unknown level',
    'Onbekende oproep': 'Unknown call',
    'Onbekende organisatie': 'Unknown organisation',
    'Onbekende rol': 'Unknown role',
    'Onbekende uitnodiging': 'Unknown invitation',
    'Ongeldig tijdstip': 'Invalid time',
    'Ongeldige lijst': 'Invalid list',
    'Ongeldige titel': 'Invalid title',
    'Te veel pogingen. Probeer het over een uur opnieuw.': 'Too many attempts. Try again in an hour.',
    'Verhaal niet gevonden': 'Story not found',
    'Wie deze kaart is, kan je niet aanpassen': 'You cannot change whose card this is',
    'Zet het nummer in internationaal formaat, bijvoorbeeld +32475123456':
      'Enter the number in international format, for example +32475123456',
    'Zo veel tegels bestaan er niet; dit is geen geldige indeling': 'There are not that many tiles; this is not a valid layout',

    // supabase/functions/*/index.ts
    'household_id of vraag ontbreekt': 'household_id or question missing',
    'Te veel pogingen. Wacht een kwartier en probeer opnieuw.': 'Too many attempts. Wait a quarter of an hour and try again.',
    'Deze code klopt niet of is verlopen. Vraag een nieuwe.': 'This code is incorrect or has expired. Ask for a new one.',
    'invite_id ontbreekt': 'invite_id missing',
    'Uitnodiging niet gevonden': 'Invitation not found',
    'niet ingelogd': 'not signed in',
    'Alleen met de service role': 'Only with the service role',
    'Onbekende fout': 'Unknown error',
    'Verwijderen mislukt': 'Deleting failed',
    'Koppelen mislukt': 'Linking failed',
    'onbekend': 'unknown',
  },
} satisfies Vertaling
