/**
 * Vertalingen voor medicatie, analyse en verslag, kalender, routines,
 * taken, de week samen, boodschappen (familiekant), zorglogboek en documenten.
 */
import type { Vertaling } from '../uiTaal'

export default {
  fr: {
    "Medicatie": "Médication",
    "Het schema zoals de huisarts of apotheker het voorschreef. LifeAngle herinnert eraan, maar stelt geen diagnose en geeft geen medisch advies.": "Le schéma tel que le médecin traitant ou le pharmacien l’a prescrit. LifeAngle vous le rappelle, mais ne pose aucun diagnostic et ne donne aucun avis médical.",
    "Bezig met laden…": "Chargement…",
    "Medicijn toevoegen": "Ajouter un médicament",
    "Gestopt": "Arrêtés",
    "Blijven bewaard met hun geschiedenis. Zet ze weer aan als ze terug nodig zijn.": "Ils restent conservés avec leur historique. Réactivez-les s’ils sont à nouveau nécessaires.",
    "Sluiten": "Fermer",
    "Wijzigen": "Modifier",
    "Opslaan lukte niet.": "L’enregistrement n’a pas abouti.",
    "Geef het medicijn een naam.": "Donnez un nom au médicament.",
    "Kies minstens één tijdstip.": "Choisissez au moins un moment.",
    "Naam": "Nom",
    "Zoals op de verpakking": "Comme sur l’emballage",
    "Dosis": "Dose",
    "1 tablet": "1 comprimé",
    "Wanneer": "Quand",
    "Tijdstip {n}": "Moment {n}",
    "Tijdstip weghalen": "Retirer ce moment",
    "+ Nog een tijdstip": "+ Un autre moment",
    "Hoe innemen?": "Comment le prendre ?",
    "Bij het ontbijt, met een glas water.": "Au petit-déjeuner, avec un verre d’eau.",
    "Zo verschijnt het bij de herinnering. Neem over wat de huisarts of apotheker zei.": "C’est ainsi que cela apparaîtra dans le rappel. Reprenez ce que le médecin traitant ou le pharmacien a dit.",
    "Andere foto": "Autre photo",
    "Foto van de verpakking": "Photo de l’emballage",
    "De foto kon niet weg.": "La photo n’a pas pu être retirée.",
    "Weghalen": "Retirer",
    "Wordt bewaard zodra je op Opslaan drukt.": "Sera enregistrée dès que vous appuyez sur Enregistrer.",
    "Op je telefoon kan je kiezen tussen de camera en je fotoalbum.": "Sur votre téléphone, vous pouvez choisir entre l’appareil photo et votre album.",
    "Opslaan…": "Enregistrement…",
    "Opslaan": "Enregistrer",
    "Stoppen": "Arrêter",
    "Opnieuw starten": "Reprendre",
    "\"{naam}\" helemaal verwijderen? Ook de geschiedenis van wat wanneer genomen werd, verdwijnt. Stoppen bewaart die wel.": "Supprimer complètement « {naam} » ? L’historique de ce qui a été pris et quand disparaîtra aussi. Arrêter le médicament conserve cet historique.",
    "Verwijderen, met geschiedenis": "Supprimer, avec l’historique",
    "Nog {n} dag voorraad": "Encore {n} jour de réserve",
    "Nog {n} dagen voorraad": "Encore {n} jours de réserve",
    "Geef een aantal van 0 of meer.": "Indiquez un nombre de 0 ou plus.",
    "De voorraad bijwerken lukte niet.": "La mise à jour de la réserve n’a pas abouti.",
    "Voorraad": "Réserve",
    "aantal": "nombre",
    "Aantal doses in huis": "Nombre de doses à la maison",
    "Bezig…": "En cours…",
    "Bijwerken": "Mettre à jour",
    "Leeg laten als je de voorraad niet bijhoudt.": "Laissez vide si vous ne suivez pas la réserve.",
    "Goed voor {n} dag. Elke bevestiging trekt er één af.": "De quoi tenir {n} jour. Chaque confirmation en retire une.",
    "Goed voor {n} dagen. Elke bevestiging trekt er één af.": "De quoi tenir {n} jours. Chaque confirmation en retire une.",
    "30 dagen": "30 jours",
    "3 maanden": "3 mois",
    "1 jaar": "1 an",
    "de persoon": "la personne",
    "Wat er bevestigd werd": "Ce qui a été confirmé",
    "Per moment van de dag, en door wie het bevestigd werd.": "Par moment de la journée, et par qui cela a été confirmé.",
    "Er zijn in deze periode nog geen medicatiemomenten. Ze verschijnen zodra er een schema staat en de nachtelijke job gedraaid heeft.": "Il n’y a pas encore de prises de médicaments sur cette période. Elles apparaîtront dès qu’un schéma est en place et que le traitement de nuit a tourné.",
    "Bevestigd wil zeggen: er is op de knop gedrukt, door {voornaam} zelf of door iemand die meezorgt. Het betekent niet dat de medicatie genomen is, en een ontbrekende bevestiging betekent niet dat ze overgeslagen werd.": "Confirmé signifie : quelqu’un a appuyé sur le bouton, {voornaam} ou une personne qui l’accompagne. Cela ne veut pas dire que le médicament a été pris, et une confirmation manquante ne veut pas dire qu’il a été oublié.",
    "Alle momenten": "Tous les moments",
    "{bevestigd} van {momenten} bevestigd, waarvan {zelf} door {voornaam} zelf": "{bevestigd} sur {momenten} confirmés, dont {zelf} par {voornaam} lui-même ou elle-même",
    "over {n} dag": "sur {n} jour",
    "over {n} dagen": "sur {n} jours",
    "Wijzigingen aan het schema": "Modifications du schéma",
    "familie": "famille",
    "zorgverlener": "soignant",
    "iemand": "quelqu’un",
    "niet bevestigd": "non confirmé",
    "Dit telt alleen wat er in de app gebeurde. Iemand kan wakker liggen zonder het scherm aan te raken, dus dit is geen slaapmeting.": "Ceci ne compte que ce qui s’est passé dans l’app. On peut être éveillé sans toucher l’écran : ce n’est donc pas une mesure du sommeil.",
    "Er staan in deze periode geen medicatiemomenten.": "Aucune prise de médicaments sur cette période.",
    "Er is in deze periode niets afgevinkt, dus hierover valt niets te zeggen.": "Rien n’a été coché sur cette période, il n’y a donc rien à en dire.",
    "Nog te weinig gegevens om per weekdag iets te tonen.": "Encore trop peu de données pour afficher quelque chose par jour de la semaine.",
    "Er is 's nachts niets geregistreerd in deze periode.": "Rien n’a été enregistré la nuit sur cette période.",
    "Het schema is in deze periode niet gewijzigd.": "Le schéma n’a pas été modifié sur cette période.",
    "Er staan geen notities in het zorglogboek voor deze periode.": "Le journal de soins ne contient aucune note pour cette période.",
    "Analyse": "Analyse",
    "Wat er in de app gebeurde, over een langere periode. Wat je hier aanvinkt, komt op het verslag voor de dokter.": "Ce qui s’est passé dans l’app, sur une plus longue période. Ce que vous cochez ici figurera dans le rapport pour le médecin.",
    "Verslag maken": "Créer le rapport",
    "Staat altijd op het verslag": "Toujours dans le rapport",
    "{gebruik} van {periode} dagen werd de app gebruikt. Alle cijfers hieronder gaan over die dagen, niet over de hele periode.": "L’app a été utilisée {gebruik} jours sur {periode}. Tous les chiffres ci-dessous portent sur ces jours, pas sur toute la période.",
    "Wat gelijk bleef": "Ce qui est resté stable",
    "Niet op het verslag: {lijst}. Dat staat ook op het blad zelf, zodat de arts weet wat hij niet ziet.": "Pas dans le rapport : {lijst}. C’est aussi indiqué sur le document lui-même, pour que le médecin sache ce qu’il ne voit pas.",
    "Nog niet beschikbaar": "Pas encore disponible",
    "Hoe vaak dezelfde vraag terugkwam.": "Combien de fois la même question revenait.",
    "Vragen aan de spraakassistent worden nergens bewaard. Dat zou een nieuwe registratie vragen, en meteen een gevoelige: je legt dan vast wat {voornaam} vroeg. Dat hoort zichtbaar te zijn voor {voornaam} en uit te zetten.": "Les questions posées à l’assistant vocal ne sont conservées nulle part. Cela demanderait un nouvel enregistrement, et un enregistrement sensible : on noterait ce que {voornaam} a demandé. Cela devrait être visible pour {voornaam} et pouvoir être désactivé.",
    "Slaap en schermtijd.": "Sommeil et temps d’écran.",
    "De app registreert niet wanneer het scherm aan stond, alleen wat er gedaan werd. Een echte meting vraagt de tablet zelf of een sensor.": "L’app n’enregistre pas quand l’écran était allumé, seulement ce qui a été fait. Une vraie mesure demanderait la tablette elle-même ou un capteur.",
    "Op het verslag": "Dans le rapport",
    "{bevestigd} van {momenten}, over {dagen} dagen": "{bevestigd} sur {momenten}, sur {dagen} jours",
    "{n} zelf": "{n} soi-même",
    "Donker is wat {voornaam} zelf bevestigde, lichter wat iemand anders deed. Bevestigd is niet hetzelfde als ingenomen.": "En foncé, ce que {voornaam} a confirmé ; en clair, ce qu’une autre personne a confirmé. Confirmé ne veut pas dire pris.",
    "{vroegste} – {laatste} · mediaan {mediaan} · {dagen} dagen": "{vroegste} – {laatste} · médiane {mediaan} · {dagen} jours",
    "De balk loopt van de vroegste tot de laatste start; het streepje is de mediaan. Schaal 5 tot 13 uur. Wordt de balk breder, dan loopt het dagritme meer uiteen.": "La barre va du début le plus tôt au plus tardif ; le trait indique la médiane. Échelle de 5 h à 13 h. Plus la barre s’élargit, plus le rythme de la journée varie.",
    "{n}d": "{n} j",
    "{n}u": "{n}h",
    "maandag": "lundi",
    "dinsdag": "mardi",
    "woensdag": "mercredi",
    "donderdag": "jeudi",
    "vrijdag": "vendredi",
    "zaterdag": "samedi",
    "zondag": "dimanche",
    "‹ Terug naar analyse": "‹ Retour à l’analyse",
    "{n} onderdeel": "{n} élément",
    "{n} onderdelen": "{n} éléments",
    "Afdrukken of opslaan als PDF": "Imprimer ou enregistrer en PDF",
    "Verslag — {naam}": "Rapport — {naam}",
    "Periode {van} tot {tot} · afgedrukt op {vandaag}": "Période du {van} au {tot} · imprimé le {vandaag}",
    "Samengesteld door familie via de app LifeAngle. Geen medisch document.": "Établi par la famille via l’app LifeAngle. Ce n’est pas un document médical.",
    "Wat deze cijfers wel en niet zijn": "Ce que ces chiffres sont, et ne sont pas",
    "Bevestigd is niet ingenomen.": "Confirmé ne veut pas dire pris.",
    "De app legt vast dat er op een knop gedrukt is, door wie en wanneer. Niet of het middel geslikt werd.": "L’app enregistre qu’on a appuyé sur un bouton, par qui et quand. Pas si le médicament a été avalé.",
    "Alles komt uit het gebruik van de app. Wat buiten de app gebeurde, staat er niet in.": "Tout provient de l’utilisation de l’app. Ce qui s’est passé en dehors de l’app n’y figure pas.",
    "De app stelt geen diagnose en meet niets medisch. Er staan hier tellingen en tijdstippen, geen score en geen conclusie.": "L’app ne pose aucun diagnostic et ne mesure rien de médical. Vous trouverez ici des comptages et des horaires, pas de score ni de conclusion.",
    "Over hoeveel dagen dit gaat": "Sur combien de jours cela porte",
    "De app werd gebruikt op {gebruik} van de {periode} dagen in deze periode, van {van} tot {tot}. Alle percentages hieronder gaan over die dagen.": "L’app a été utilisée {gebruik} jours sur {periode} durant cette période, du {van} au {tot}. Tous les pourcentages ci-dessous portent sur ces jours.",
    "De app werd gebruikt op {gebruik} van de {periode} dagen in deze periode. Alle percentages hieronder gaan over die dagen.": "L’app a été utilisée {gebruik} jours sur {periode} durant cette période. Tous les pourcentages ci-dessous portent sur ces jours.",
    "Er staat nog niets aangevinkt. Kies op het analysescherm wat er op het verslag moet komen.": "Rien n’est encore coché. Choisissez dans l’écran d’analyse ce qui doit figurer dans le rapport.",
    "Wat er niet op dit verslag staat": "Ce qui ne figure pas dans ce rapport",
    "Weggelaten door familie:": "Omis par la famille :",
    "{lijst}. Deze gegevens bestaan wel in de app.": "{lijst}. Ces données existent bien dans l’app.",
    "Geen gegevens over:": "Aucune donnée sur :",
    "{lijst}. Hierover is in deze periode niets vastgelegd.": "{lijst}. Rien n’a été enregistré à ce sujet durant cette période.",
    "Alles wat de app over deze periode heeft, staat hierboven.": "Tout ce que l’app possède sur cette période figure ci-dessus.",
    "De app registreert geen slaap, geen schermtijd en niet wat {voornaam} aan de spraakassistent vroeg.": "L’app n’enregistre ni le sommeil, ni le temps d’écran, ni ce que {voornaam} a demandé à l’assistant vocal.",
    "LifeAngle — een digitaal geheugen voor het dagelijkse leven. Dit verslag vervangt geen professionele zorg.": "LifeAngle — une mémoire numérique pour la vie de tous les jours. Ce rapport ne remplace pas des soins professionnels.",
    "In totaal {bevestigd} van {momenten} momenten bevestigd ({pct}), waarvan {zelf} door {voornaam} zelf. Over {dagen} dagen.": "Au total, {bevestigd} prises sur {momenten} confirmées ({pct}), dont {zelf} par {voornaam} lui-même ou elle-même. Sur {dagen} jours.",
    "Tijdstip": "Moment",
    "Momenten": "Prises",
    "Bevestigd": "Confirmé",
    "Aandeel": "Part",
    "Waarvan zelf": "Dont soi-même",
    "Dagen": "Jours",
    "\"Waarvan zelf\" is het aantal momenten dat {voornaam} zelf bevestigde; de rest werd door familie of een zorgverlener bevestigd. Een gelijkblijvend totaal kan dus een verschuiving verbergen.": "« Dont soi-même » est le nombre de prises que {voornaam} a confirmées ; le reste a été confirmé par la famille ou un soignant. Un total stable peut donc cacher un glissement.",
    "Het tijdstip van de eerste afgevinkte activiteit van de dag. Het verschil tussen de vroegste en de laatste zegt meer dan de mediaan.": "L’heure de la première activité cochée de la journée. L’écart entre la plus tôt et la plus tardive en dit plus que la médiane.",
    "Maand": "Mois",
    "Vroegste": "Plus tôt",
    "Mediaan": "Médiane",
    "Laatste": "Plus tard",
    "Spreiding": "Écart",
    "{n} min": "{n} min",
    "Per dag van de week. Belangrijk bij het lezen: valt een hoog cijfer samen met de dag waarop er bezoek is, dan meet het bezoek en geen zelfstandigheid.": "Par jour de la semaine. Important à la lecture : si un chiffre élevé coïncide avec le jour des visites, il mesure la visite et non l’autonomie.",
    "Dag": "Jour",
    "Zelf": "Soi-même",
    "Agenda gedaan": "Agenda réalisé",
    "Handelingen in de app door de persoon zelf tussen 1 en 6 uur: {n} in deze periode.": "Actions dans l’app par la personne elle-même entre 1 h et 6 h : {n} sur cette période.",
    "Dit is geen slaapmeting": "Ce n’est pas une mesure du sommeil",
    "— iemand kan wakker liggen zonder het scherm aan te raken, dus dit telt eerder te weinig dan te veel.": "— on peut être éveillé sans toucher l’écran, ce chiffre est donc plutôt sous-estimé que surestimé.",
    "Uur": "Heure",
    "Handelingen": "Actions",
    "Aantal dagen": "Nombre de jours",
    "Wijzigingen aan het medicatieschema in deze periode. Een daling in de cijfers hierboven betekent iets anders als er kort daarvoor een middel bijkwam of wegging.": "Modifications du schéma de médication sur cette période. Une baisse des chiffres ci-dessus n’a pas le même sens si un médicament a été ajouté ou retiré peu avant.",
    "zelf": "soi-même",
    "app": "app",
    "In de woorden van familie en zorgverleners.": "Avec les mots de la famille et des soignants.",
    "Medicatie bevestigd": "Médication confirmée",
    "Per moment van de dag, en welk deel de persoon zelf bevestigde.": "Par moment de la journée, et la part confirmée par la personne elle-même.",
    "Wanneer de dag begon": "Quand la journée a commencé",
    "Dagritme": "Rythme de la journée",
    "Het tijdstip van de eerste afgevinkte activiteit. Het uiteenlopen zegt meer dan het gemiddelde.": "L’heure de la première activité cochée. L’écart en dit plus que la moyenne.",
    "Per dag van de week": "Par jour de la semaine",
    "Klopt alles op zondag omdat er dan bezoek is, dan meet je bezoek en geen zelfstandigheid.": "Si tout va bien le dimanche parce qu’il y a de la visite, vous mesurez la visite et non l’autonomie.",
    "Activiteit 's nachts": "Activité la nuit",
    "Handelingen door de persoon zelf tussen 1 en 6 uur.": "Actions de la personne elle-même entre 1 h et 6 h.",
    "Wijzigingen aan het medicatieschema": "Modifications du schéma de médication",
    "Een daling betekent iets anders als er kort daarvoor een middel bijkwam.": "Une baisse n’a pas le même sens si un médicament a été ajouté peu avant.",
    "Wat familie en zorgverleners noteerden": "Ce que la famille et les soignants ont noté",
    "Notities van familie en zorgverleners": "Notes de la famille et des soignants",
    "In hun eigen woorden. Vaak het stuk waar een arts het meest aan heeft.": "Avec leurs propres mots. Souvent la partie la plus utile pour un médecin.",
    "ma": "lu",
    "di": "ma",
    "wo": "me",
    "do": "je",
    "vr": "ve",
    "za": "sa",
    "zo": "di",
    "Kalender": "Calendrier",
    "Wat je hier plant, verschijnt vanzelf op het scherm van {naam}.": "Ce que vous planifiez ici apparaît automatiquement sur l’écran de {naam}.",
    "Vorige week": "Semaine précédente",
    "Deze week": "Cette semaine",
    "Volgende week": "Semaine suivante",
    "vandaag": "aujourd’hui",
    " · gedaan": " · fait",
    "Toevoegen": "Ajouter",
    "Je kan alleen je eigen afspraken wijzigen.": "Vous ne pouvez modifier que vos propres rendez-vous.",
    "Afspraak wijzigen": "Modifier le rendez-vous",
    "Afspraak toevoegen": "Ajouter un rendez-vous",
    "Geef de afspraak een naam.": "Donnez un nom au rendez-vous.",
    "Gepland door {naam}": "Planifié par {naam}",
    "Dit komt uit een vaste routine. Wat je hier wijzigt, geldt alleen voor deze dag.": "Ceci provient d’une routine fixe. Ce que vous modifiez ici ne vaut que pour ce jour.",
    "Om {uur} staat al {titel}. Twee dingen zo dicht bij elkaar kan veel zijn.": "À {uur}, il y a déjà {titel}. Deux choses si rapprochées, cela peut faire beaucoup.",
    "Wat?": "Quoi ?",
    "Tandarts": "Dentiste",
    "Soort": "Type",
    "Wie komt er, of met wie?": "Qui vient, ou avec qui ?",
    "Niemand in het bijzonder": "Personne en particulier",
    "Wat moet de persoon weten?": "Que doit savoir la personne ?",
    "Els haalt je om 13:30 op. Neem je identiteitskaart mee.": "Els vient vous chercher à 13:30. Prenez votre carte d’identité.",
    "Dit wordt getoond en voorgelezen vlak voor de afspraak.": "Ceci est affiché et lu à voix haute juste avant le rendez-vous.",
    "\"{titel}\" verwijderen?": "Supprimer « {titel} » ?",
    "Verwijderen": "Supprimer",
    "Afspraak": "Rendez-vous",
    "Bezoek": "Visite",
    "Maaltijd": "Repas",
    "Routine": "Routine",
    "Herinnering": "Rappel",
    "Andere": "Autre",
    "Routines": "Routines",
    "Vaste momenten die elke dag terugkomen. De nachtelijke job zet ze om in de agenda van morgen.": "Des moments fixes qui reviennent chaque jour. Le traitement de nuit les place dans l’agenda du lendemain.",
    " — staat uit": " — désactivée",
    "Nog geen stappen.": "Pas encore d’étapes.",
    "+ Routine toevoegen": "+ Ajouter une routine",
    "Wijzigingen gelden vanaf morgen. Wil je ze vandaag al zien, zet de routines dan nu om. Items die al in de agenda staan blijven ongemoeid. Dit zet ook de medicatiemomenten van vandaag en morgen klaar.": "Les modifications s’appliquent à partir de demain. Pour les voir dès aujourd’hui, convertissez les routines maintenant. Les éléments déjà dans l’agenda ne sont pas touchés. Cela prépare aussi les prises de médicaments d’aujourd’hui et de demain.",
    "Vandaag bijwerken": "Mettre à jour aujourd’hui",
    "Ochtend": "Matin",
    "Herhaling": "Répétition",
    "Stappen, één per lijn": "Étapes, une par ligne",
    "07:30 Opstaan\n08:00 Ontbijt\n08:30 Medicatie": "07:30 Lever\n08:00 Petit-déjeuner\n08:30 Médication",
    "Begin elke lijn met het uur. Regels zonder uur worden overgeslagen.": "Commencez chaque ligne par l’heure. Les lignes sans heure sont ignorées.",
    "Actief": "Active",
    "Annuleren": "Annuler",
    "Routine \"{naam}\" verwijderen?": "Supprimer la routine « {naam} » ?",
    "Weekdagen": "Jours de semaine",
    "Weekend": "Week-end",
    "Elke zondag": "Chaque dimanche",
    "Eerste van de maand": "Le premier du mois",
    "Geen tijd herkend": "Aucune heure reconnue",
    "{titel} staat in de planning, {uitleg}.": "{titel} est dans le planning, {uitleg}.",
    "Toevoegen lukte niet.": "L’ajout n’a pas abouti.",
    "Snel een afspraak toevoegen": "Ajouter rapidement un rendez-vous",
    "Typ of spreek het in gewone taal in:": "Tapez-le ou dictez-le simplement, en néerlandais :",
    "Ik haal er geen dag of uur uit. Probeer \"{voorbeeld}\".": "Je ne trouve ni jour ni heure. Essayez « {voorbeeld} ».",
    "Begrepen als": "Compris comme",
    "{dag} om {uur}": "{dag} à {uur}",
    "morgen": "demain",
    "overmorgen": "après-demain",
    "Eenmalig": "Une seule fois",
    "Elke dag": "Chaque jour",
    "Elke week": "Chaque semaine",
    "Elke maand": "Chaque mois",
    "Opnemen lukte niet.": "La prise en charge n’a pas abouti.",
    "Toewijzen lukte niet.": "L’attribution n’a pas abouti.",
    "Afvinken lukte niet.": "Cocher n’a pas abouti.",
    "Terugzetten lukte niet.": "La remise en place n’a pas abouti.",
    "Verwijderen lukte niet.": "La suppression n’a pas abouti.",
    "jij": "vous",
    "Te laat": "En retard",
    "Vandaag": "Aujourd’hui",
    "Later": "Plus tard",
    "Ooit": "Un jour",
    "Zonder dag erbij.": "Sans date.",
    "Taken": "Tâches",
    "Het regelwerk onder elkaar verdelen. {naam} ziet dit scherm niet.": "Répartir l’organisation entre vous. {naam} ne voit pas cet écran.",
    "De persoon": "La personne",
    "Niets openstaand. Wat hierboven bijkomt, verschijnt hier.": "Rien en attente. Ce que vous ajoutez ci-dessus apparaîtra ici.",
    "{titel} afvinken": "Cocher {titel}",
    "geen dag": "pas de date",
    "Wie doet {titel}": "Qui s’occupe de {titel}",
    "Niemand": "Personne",
    "Ik": "Moi",
    "Neem ik": "Je m’en charge",
    "{titel} verwijderen": "Supprimer {titel}",
    "weg": "retirer",
    "Afgevinkt deze week": "Cochées cette semaine",
    "terugzetten": "remettre",
    "Wat moet er gebeuren?": "Que faut-il faire ?",
    "Boodschappen doen": "Faire les courses",
    "Wie doet het": "Qui s’en charge",
    "Nog op te nemen": "À prendre en charge",
    "Hoe vaak": "À quelle fréquence",
    "gisteren": "hier",
    "Dit scherm toont de week van de mensen voor wie je zorgt. Je bent nog nergens familielid.": "Cet écran montre la semaine des personnes dont vous prenez soin. Vous n’êtes encore membre d’aucune famille.",
    "De week samen": "La semaine ensemble",
    "Wie gaat er wanneer langs, en wie doet wat. Zeg het hier in plaats van het te bellen.": "Qui passe quand, et qui fait quoi. Dites-le ici plutôt que de téléphoner.",
    "Even geduld…": "Un instant…",
    "Toch niet": "Finalement non",
    "Ik doe dit": "Je m’en occupe",
    "Niemand gepland": "Personne de prévu",
    "Ik ga langs": "Je passe",
    "Een bezoek dat je hier plant, staat om 14:00 en verschijnt meteen op het scherm van de persoon. Het uur verzet je in de kalender.": "Une visite planifiée ici est fixée à 14:00 et apparaît tout de suite sur l’écran de la personne. Vous pouvez changer l’heure dans le calendrier.",
    "De lijst kon niet geladen worden.": "La liste n’a pas pu être chargée.",
    "Bijvoorbeeld: melk, brood": "Par exemple : lait, pain",
    "Product toevoegen": "Ajouter un produit",
    "Dat is niet gelukt. Probeer het opnieuw.": "Cela n’a pas fonctionné. Réessayez.",
    "{naam} verwijderen": "Supprimer {naam}",
    "zelf afgevinkt": "coché par la personne",
    "automatisch": "automatique",
    "Zorglogboek": "Journal de soins",
    "Wat er gebeurd is, door familie, zorgverleners en de app zelf.": "Ce qui s’est passé, noté par la famille, les soignants et l’app elle-même.",
    "Wat gebeurde er?": "Que s’est-il passé ?",
    "Samen gewandeld": "Promenade ensemble",
    "Notitie, mag leeg blijven": "Note, facultative",
    "Vandaag wat vermoeid.": "Un peu fatigué(e) aujourd’hui.",
    "Wissen": "Effacer",
    "Nog niets genoteerd deze week.": "Rien de noté cette semaine.",
    "Documenten": "Documents",
    "Alleen zichtbaar voor familie. Niet voor zorgverleners, en niet op het scherm van de persoon.": "Visible uniquement par la famille. Pas par les soignants, et pas sur l’écran de la personne.",
    "Hospitalisatieverzekering": "Assurance hospitalisation",
    "Categorie": "Catégorie",
    "Bestand": "Fichier",
    "Document toevoegen": "Ajouter un document",
    "Zoeken": "Rechercher",
    "Nog niets in deze categorie.": "Rien dans cette catégorie pour l’instant.",
    "Openen": "Ouvrir",
    "geen bestand": "pas de fichier",
    "Links naar documenten zijn vijf minuten geldig en niet deelbaar. Verwijderen wist ook het bestand zelf.": "Les liens vers les documents sont valables cinq minutes et ne peuvent pas être partagés. Supprimer efface aussi le fichier lui-même.",
    "Identiteit": "Identité",
    "Verzekering": "Assurance",
    "Medisch": "Médical",
    "Afspraken": "Rendez-vous",
    "Belangrijk": "Important",
  },
  en: {
    "Medicatie": "Medication",
    "Het schema zoals de huisarts of apotheker het voorschreef. LifeAngle herinnert eraan, maar stelt geen diagnose en geeft geen medisch advies.": "The schedule as prescribed by the GP or pharmacist. LifeAngle sends reminders, but makes no diagnosis and gives no medical advice.",
    "Bezig met laden…": "Loading…",
    "Medicijn toevoegen": "Add a medicine",
    "Gestopt": "Stopped",
    "Blijven bewaard met hun geschiedenis. Zet ze weer aan als ze terug nodig zijn.": "They are kept with their history. Switch them back on if they are needed again.",
    "Sluiten": "Close",
    "Wijzigen": "Edit",
    "Opslaan lukte niet.": "Saving didn't work.",
    "Geef het medicijn een naam.": "Give the medicine a name.",
    "Kies minstens één tijdstip.": "Choose at least one time.",
    "Naam": "Name",
    "Zoals op de verpakking": "As on the packaging",
    "Dosis": "Dose",
    "1 tablet": "1 tablet",
    "Wanneer": "When",
    "Tijdstip {n}": "Time {n}",
    "Tijdstip weghalen": "Remove this time",
    "+ Nog een tijdstip": "+ Another time",
    "Hoe innemen?": "How to take it?",
    "Bij het ontbijt, met een glas water.": "With breakfast, with a glass of water.",
    "Zo verschijnt het bij de herinnering. Neem over wat de huisarts of apotheker zei.": "This is how it appears in the reminder. Copy what the GP or pharmacist said.",
    "Andere foto": "Different photo",
    "Foto van de verpakking": "Photo of the packaging",
    "De foto kon niet weg.": "The photo couldn't be removed.",
    "Weghalen": "Remove",
    "Wordt bewaard zodra je op Opslaan drukt.": "Will be saved as soon as you press Save.",
    "Op je telefoon kan je kiezen tussen de camera en je fotoalbum.": "On your phone you can choose between the camera and your photo library.",
    "Opslaan…": "Saving…",
    "Opslaan": "Save",
    "Stoppen": "Stop",
    "Opnieuw starten": "Start again",
    "\"{naam}\" helemaal verwijderen? Ook de geschiedenis van wat wanneer genomen werd, verdwijnt. Stoppen bewaart die wel.": "Delete \"{naam}\" completely? The history of what was taken and when will also disappear. Stopping keeps it.",
    "Verwijderen, met geschiedenis": "Delete, including history",
    "Nog {n} dag voorraad": "{n} day of supply left",
    "Nog {n} dagen voorraad": "{n} days of supply left",
    "Geef een aantal van 0 of meer.": "Enter a number of 0 or more.",
    "De voorraad bijwerken lukte niet.": "Updating the supply didn't work.",
    "Voorraad": "Supply",
    "aantal": "number",
    "Aantal doses in huis": "Number of doses at home",
    "Bezig…": "Working…",
    "Bijwerken": "Update",
    "Leeg laten als je de voorraad niet bijhoudt.": "Leave empty if you don't keep track of the supply.",
    "Goed voor {n} dag. Elke bevestiging trekt er één af.": "Enough for {n} day. Each confirmation takes one off.",
    "Goed voor {n} dagen. Elke bevestiging trekt er één af.": "Enough for {n} days. Each confirmation takes one off.",
    "30 dagen": "30 days",
    "3 maanden": "3 months",
    "1 jaar": "1 year",
    "de persoon": "the person",
    "Wat er bevestigd werd": "What was confirmed",
    "Per moment van de dag, en door wie het bevestigd werd.": "By time of day, and by whom it was confirmed.",
    "Er zijn in deze periode nog geen medicatiemomenten. Ze verschijnen zodra er een schema staat en de nachtelijke job gedraaid heeft.": "There are no medication times in this period yet. They appear once a schedule is set and the overnight job has run.",
    "Bevestigd wil zeggen: er is op de knop gedrukt, door {voornaam} zelf of door iemand die meezorgt. Het betekent niet dat de medicatie genomen is, en een ontbrekende bevestiging betekent niet dat ze overgeslagen werd.": "Confirmed means: the button was pressed, by {voornaam} or by someone helping with care. It does not mean the medication was taken, and a missing confirmation does not mean it was skipped.",
    "Alle momenten": "All times",
    "{bevestigd} van {momenten} bevestigd, waarvan {zelf} door {voornaam} zelf": "{bevestigd} of {momenten} confirmed, {zelf} of them by {voornaam}",
    "over {n} dag": "over {n} day",
    "over {n} dagen": "over {n} days",
    "Wijzigingen aan het schema": "Changes to the schedule",
    "familie": "family",
    "zorgverlener": "carer",
    "iemand": "someone",
    "niet bevestigd": "not confirmed",
    "Dit telt alleen wat er in de app gebeurde. Iemand kan wakker liggen zonder het scherm aan te raken, dus dit is geen slaapmeting.": "This only counts what happened in the app. Someone can lie awake without touching the screen, so this is not a sleep measurement.",
    "Er staan in deze periode geen medicatiemomenten.": "There are no medication times in this period.",
    "Er is in deze periode niets afgevinkt, dus hierover valt niets te zeggen.": "Nothing was ticked off in this period, so there is nothing to say about it.",
    "Nog te weinig gegevens om per weekdag iets te tonen.": "Not enough data yet to show anything per weekday.",
    "Er is 's nachts niets geregistreerd in deze periode.": "Nothing was recorded at night in this period.",
    "Het schema is in deze periode niet gewijzigd.": "The schedule was not changed in this period.",
    "Er staan geen notities in het zorglogboek voor deze periode.": "There are no notes in the care log for this period.",
    "Analyse": "Analysis",
    "Wat er in de app gebeurde, over een langere periode. Wat je hier aanvinkt, komt op het verslag voor de dokter.": "What happened in the app over a longer period. What you tick here goes into the report for the doctor.",
    "Verslag maken": "Create report",
    "Staat altijd op het verslag": "Always in the report",
    "{gebruik} van {periode} dagen werd de app gebruikt. Alle cijfers hieronder gaan over die dagen, niet over de hele periode.": "The app was used on {gebruik} of {periode} days. All figures below refer to those days, not to the whole period.",
    "Wat gelijk bleef": "What stayed the same",
    "Niet op het verslag: {lijst}. Dat staat ook op het blad zelf, zodat de arts weet wat hij niet ziet.": "Not in the report: {lijst}. This is also stated on the sheet itself, so the doctor knows what they are not seeing.",
    "Nog niet beschikbaar": "Not available yet",
    "Hoe vaak dezelfde vraag terugkwam.": "How often the same question came back.",
    "Vragen aan de spraakassistent worden nergens bewaard. Dat zou een nieuwe registratie vragen, en meteen een gevoelige: je legt dan vast wat {voornaam} vroeg. Dat hoort zichtbaar te zijn voor {voornaam} en uit te zetten.": "Questions to the voice assistant are not stored anywhere. That would require a new kind of recording, and a sensitive one: you would be logging what {voornaam} asked. That should be visible to {voornaam} and possible to switch off.",
    "Slaap en schermtijd.": "Sleep and screen time.",
    "De app registreert niet wanneer het scherm aan stond, alleen wat er gedaan werd. Een echte meting vraagt de tablet zelf of een sensor.": "The app does not record when the screen was on, only what was done. A real measurement would need the tablet itself or a sensor.",
    "Op het verslag": "In the report",
    "{bevestigd} van {momenten}, over {dagen} dagen": "{bevestigd} of {momenten}, over {dagen} days",
    "{n} zelf": "{n} self",
    "Donker is wat {voornaam} zelf bevestigde, lichter wat iemand anders deed. Bevestigd is niet hetzelfde als ingenomen.": "Dark is what {voornaam} confirmed, lighter is what someone else did. Confirmed is not the same as taken.",
    "{vroegste} – {laatste} · mediaan {mediaan} · {dagen} dagen": "{vroegste} – {laatste} · median {mediaan} · {dagen} days",
    "De balk loopt van de vroegste tot de laatste start; het streepje is de mediaan. Schaal 5 tot 13 uur. Wordt de balk breder, dan loopt het dagritme meer uiteen.": "The bar runs from the earliest to the latest start; the line is the median. Scale 5 am to 1 pm. If the bar gets wider, the daily rhythm is varying more.",
    "{n}d": "{n}d",
    "{n}u": "{n}h",
    "maandag": "Monday",
    "dinsdag": "Tuesday",
    "woensdag": "Wednesday",
    "donderdag": "Thursday",
    "vrijdag": "Friday",
    "zaterdag": "Saturday",
    "zondag": "Sunday",
    "‹ Terug naar analyse": "‹ Back to analysis",
    "{n} onderdeel": "{n} section",
    "{n} onderdelen": "{n} sections",
    "Afdrukken of opslaan als PDF": "Print or save as PDF",
    "Verslag — {naam}": "Report — {naam}",
    "Periode {van} tot {tot} · afgedrukt op {vandaag}": "Period {van} to {tot} · printed on {vandaag}",
    "Samengesteld door familie via de app LifeAngle. Geen medisch document.": "Compiled by family using the LifeAngle app. Not a medical document.",
    "Wat deze cijfers wel en niet zijn": "What these figures are and are not",
    "Bevestigd is niet ingenomen.": "Confirmed is not taken.",
    "De app legt vast dat er op een knop gedrukt is, door wie en wanneer. Niet of het middel geslikt werd.": "The app records that a button was pressed, by whom and when. Not whether the medicine was swallowed.",
    "Alles komt uit het gebruik van de app. Wat buiten de app gebeurde, staat er niet in.": "Everything comes from use of the app. What happened outside the app is not included.",
    "De app stelt geen diagnose en meet niets medisch. Er staan hier tellingen en tijdstippen, geen score en geen conclusie.": "The app makes no diagnosis and measures nothing medical. This contains counts and times, no score and no conclusion.",
    "Over hoeveel dagen dit gaat": "How many days this covers",
    "De app werd gebruikt op {gebruik} van de {periode} dagen in deze periode, van {van} tot {tot}. Alle percentages hieronder gaan over die dagen.": "The app was used on {gebruik} of the {periode} days in this period, from {van} to {tot}. All percentages below refer to those days.",
    "De app werd gebruikt op {gebruik} van de {periode} dagen in deze periode. Alle percentages hieronder gaan over die dagen.": "The app was used on {gebruik} of the {periode} days in this period. All percentages below refer to those days.",
    "Er staat nog niets aangevinkt. Kies op het analysescherm wat er op het verslag moet komen.": "Nothing is ticked yet. Choose on the analysis screen what should go into the report.",
    "Wat er niet op dit verslag staat": "What is not in this report",
    "Weggelaten door familie:": "Left out by family:",
    "{lijst}. Deze gegevens bestaan wel in de app.": "{lijst}. This data does exist in the app.",
    "Geen gegevens over:": "No data on:",
    "{lijst}. Hierover is in deze periode niets vastgelegd.": "{lijst}. Nothing was recorded about this in this period.",
    "Alles wat de app over deze periode heeft, staat hierboven.": "Everything the app has about this period is shown above.",
    "De app registreert geen slaap, geen schermtijd en niet wat {voornaam} aan de spraakassistent vroeg.": "The app does not record sleep, screen time or what {voornaam} asked the voice assistant.",
    "LifeAngle — een digitaal geheugen voor het dagelijkse leven. Dit verslag vervangt geen professionele zorg.": "LifeAngle — a digital memory for everyday life. This report does not replace professional care.",
    "In totaal {bevestigd} van {momenten} momenten bevestigd ({pct}), waarvan {zelf} door {voornaam} zelf. Over {dagen} dagen.": "In total {bevestigd} of {momenten} times confirmed ({pct}), {zelf} of them by {voornaam}. Over {dagen} days.",
    "Tijdstip": "Time",
    "Momenten": "Times",
    "Bevestigd": "Confirmed",
    "Aandeel": "Share",
    "Waarvan zelf": "Of which self",
    "Dagen": "Days",
    "\"Waarvan zelf\" is het aantal momenten dat {voornaam} zelf bevestigde; de rest werd door familie of een zorgverlener bevestigd. Een gelijkblijvend totaal kan dus een verschuiving verbergen.": "\"Of which self\" is the number of times {voornaam} confirmed; the rest was confirmed by family or a carer. A steady total can therefore hide a shift.",
    "Het tijdstip van de eerste afgevinkte activiteit van de dag. Het verschil tussen de vroegste en de laatste zegt meer dan de mediaan.": "The time of the first activity ticked off each day. The gap between the earliest and the latest says more than the median.",
    "Maand": "Month",
    "Vroegste": "Earliest",
    "Mediaan": "Median",
    "Laatste": "Latest",
    "Spreiding": "Spread",
    "{n} min": "{n} min",
    "Per dag van de week. Belangrijk bij het lezen: valt een hoog cijfer samen met de dag waarop er bezoek is, dan meet het bezoek en geen zelfstandigheid.": "Per day of the week. Important when reading: if a high figure coincides with the day there are visitors, it measures the visit, not independence.",
    "Dag": "Day",
    "Zelf": "Self",
    "Agenda gedaan": "Calendar done",
    "Handelingen in de app door de persoon zelf tussen 1 en 6 uur: {n} in deze periode.": "Actions in the app by the person themselves between 1 am and 6 am: {n} in this period.",
    "Dit is geen slaapmeting": "This is not a sleep measurement",
    "— iemand kan wakker liggen zonder het scherm aan te raken, dus dit telt eerder te weinig dan te veel.": "— someone can lie awake without touching the screen, so this undercounts rather than overcounts.",
    "Uur": "Hour",
    "Handelingen": "Actions",
    "Aantal dagen": "Number of days",
    "Wijzigingen aan het medicatieschema in deze periode. Een daling in de cijfers hierboven betekent iets anders als er kort daarvoor een middel bijkwam of wegging.": "Changes to the medication schedule in this period. A drop in the figures above means something different if a medicine was added or removed shortly before.",
    "zelf": "self",
    "app": "app",
    "In de woorden van familie en zorgverleners.": "In the words of family and carers.",
    "Medicatie bevestigd": "Medication confirmed",
    "Per moment van de dag, en welk deel de persoon zelf bevestigde.": "By time of day, and the share the person confirmed themselves.",
    "Wanneer de dag begon": "When the day started",
    "Dagritme": "Daily rhythm",
    "Het tijdstip van de eerste afgevinkte activiteit. Het uiteenlopen zegt meer dan het gemiddelde.": "The time of the first activity ticked off. The spread says more than the average.",
    "Per dag van de week": "Per day of the week",
    "Klopt alles op zondag omdat er dan bezoek is, dan meet je bezoek en geen zelfstandigheid.": "If everything is fine on Sunday because there are visitors, you are measuring the visit, not independence.",
    "Activiteit 's nachts": "Night-time activity",
    "Handelingen door de persoon zelf tussen 1 en 6 uur.": "Actions by the person themselves between 1 am and 6 am.",
    "Wijzigingen aan het medicatieschema": "Changes to the medication schedule",
    "Een daling betekent iets anders als er kort daarvoor een middel bijkwam.": "A drop means something different if a medicine was added shortly before.",
    "Wat familie en zorgverleners noteerden": "What family and carers noted",
    "Notities van familie en zorgverleners": "Notes from family and carers",
    "In hun eigen woorden. Vaak het stuk waar een arts het meest aan heeft.": "In their own words. Often the part a doctor finds most useful.",
    "ma": "Mon",
    "di": "Tue",
    "wo": "Wed",
    "do": "Thu",
    "vr": "Fri",
    "za": "Sat",
    "zo": "Sun",
    "Kalender": "Calendar",
    "Wat je hier plant, verschijnt vanzelf op het scherm van {naam}.": "What you plan here appears automatically on {naam}'s screen.",
    "Vorige week": "Previous week",
    "Deze week": "This week",
    "Volgende week": "Next week",
    "vandaag": "today",
    " · gedaan": " · done",
    "Toevoegen": "Add",
    "Je kan alleen je eigen afspraken wijzigen.": "You can only change your own appointments.",
    "Afspraak wijzigen": "Edit appointment",
    "Afspraak toevoegen": "Add appointment",
    "Geef de afspraak een naam.": "Give the appointment a name.",
    "Gepland door {naam}": "Planned by {naam}",
    "Dit komt uit een vaste routine. Wat je hier wijzigt, geldt alleen voor deze dag.": "This comes from a regular routine. What you change here applies to this day only.",
    "Om {uur} staat al {titel}. Twee dingen zo dicht bij elkaar kan veel zijn.": "{titel} is already planned at {uur}. Two things so close together can be a lot.",
    "Wat?": "What?",
    "Tandarts": "Dentist",
    "Soort": "Type",
    "Wie komt er, of met wie?": "Who is coming, or with whom?",
    "Niemand in het bijzonder": "No one in particular",
    "Wat moet de persoon weten?": "What does the person need to know?",
    "Els haalt je om 13:30 op. Neem je identiteitskaart mee.": "Els will pick you up at 13:30. Bring your ID card.",
    "Dit wordt getoond en voorgelezen vlak voor de afspraak.": "This is shown and read aloud just before the appointment.",
    "\"{titel}\" verwijderen?": "Delete \"{titel}\"?",
    "Verwijderen": "Delete",
    "Afspraak": "Appointment",
    "Bezoek": "Visit",
    "Maaltijd": "Meal",
    "Routine": "Routine",
    "Herinnering": "Reminder",
    "Andere": "Other",
    "Routines": "Routines",
    "Vaste momenten die elke dag terugkomen. De nachtelijke job zet ze om in de agenda van morgen.": "Regular moments that come back every day. The overnight job turns them into tomorrow's calendar.",
    " — staat uit": " — switched off",
    "Nog geen stappen.": "No steps yet.",
    "+ Routine toevoegen": "+ Add routine",
    "Wijzigingen gelden vanaf morgen. Wil je ze vandaag al zien, zet de routines dan nu om. Items die al in de agenda staan blijven ongemoeid. Dit zet ook de medicatiemomenten van vandaag en morgen klaar.": "Changes apply from tomorrow. If you want to see them today, convert the routines now. Items already in the calendar are left alone. This also sets up today's and tomorrow's medication times.",
    "Vandaag bijwerken": "Update today",
    "Ochtend": "Morning",
    "Herhaling": "Repeat",
    "Stappen, één per lijn": "Steps, one per line",
    "07:30 Opstaan\n08:00 Ontbijt\n08:30 Medicatie": "07:30 Get up\n08:00 Breakfast\n08:30 Medication",
    "Begin elke lijn met het uur. Regels zonder uur worden overgeslagen.": "Start each line with the time. Lines without a time are skipped.",
    "Actief": "Active",
    "Annuleren": "Cancel",
    "Routine \"{naam}\" verwijderen?": "Delete routine \"{naam}\"?",
    "Weekdagen": "Weekdays",
    "Weekend": "Weekend",
    "Elke zondag": "Every Sunday",
    "Eerste van de maand": "First of the month",
    "Geen tijd herkend": "No time recognised",
    "{titel} staat in de planning, {uitleg}.": "{titel} is in the plan, {uitleg}.",
    "Toevoegen lukte niet.": "Adding didn't work.",
    "Snel een afspraak toevoegen": "Quickly add an appointment",
    "Typ of spreek het in gewone taal in:": "Type or say it in plain Dutch:",
    "Ik haal er geen dag of uur uit. Probeer \"{voorbeeld}\".": "I can't find a day or time in that. Try \"{voorbeeld}\".",
    "Begrepen als": "Understood as",
    "{dag} om {uur}": "{dag} at {uur}",
    "morgen": "tomorrow",
    "overmorgen": "the day after tomorrow",
    "Eenmalig": "Once",
    "Elke dag": "Every day",
    "Elke week": "Every week",
    "Elke maand": "Every month",
    "Opnemen lukte niet.": "Taking it on didn't work.",
    "Toewijzen lukte niet.": "Assigning didn't work.",
    "Afvinken lukte niet.": "Ticking off didn't work.",
    "Terugzetten lukte niet.": "Putting it back didn't work.",
    "Verwijderen lukte niet.": "Deleting didn't work.",
    "jij": "you",
    "Te laat": "Overdue",
    "Vandaag": "Today",
    "Later": "Later",
    "Ooit": "Some time",
    "Zonder dag erbij.": "No date set.",
    "Taken": "Tasks",
    "Het regelwerk onder elkaar verdelen. {naam} ziet dit scherm niet.": "Share out the arranging between you. {naam} does not see this screen.",
    "De persoon": "The person",
    "Niets openstaand. Wat hierboven bijkomt, verschijnt hier.": "Nothing outstanding. Anything added above will appear here.",
    "{titel} afvinken": "Tick off {titel}",
    "geen dag": "no date",
    "Wie doet {titel}": "Who does {titel}",
    "Niemand": "No one",
    "Ik": "Me",
    "Neem ik": "I'll take it",
    "{titel} verwijderen": "Delete {titel}",
    "weg": "remove",
    "Afgevinkt deze week": "Ticked off this week",
    "terugzetten": "put back",
    "Wat moet er gebeuren?": "What needs doing?",
    "Boodschappen doen": "Do the shopping",
    "Wie doet het": "Who does it",
    "Nog op te nemen": "Still to be taken on",
    "Hoe vaak": "How often",
    "gisteren": "yesterday",
    "Dit scherm toont de week van de mensen voor wie je zorgt. Je bent nog nergens familielid.": "This screen shows the week of the people you care for. You are not a family member anywhere yet.",
    "De week samen": "The week together",
    "Wie gaat er wanneer langs, en wie doet wat. Zeg het hier in plaats van het te bellen.": "Who visits when, and who does what. Say it here instead of phoning round.",
    "Even geduld…": "One moment…",
    "Toch niet": "Not after all",
    "Ik doe dit": "I'll do this",
    "Niemand gepland": "No one planned",
    "Ik ga langs": "I'll visit",
    "Een bezoek dat je hier plant, staat om 14:00 en verschijnt meteen op het scherm van de persoon. Het uur verzet je in de kalender.": "A visit you plan here is set for 14:00 and appears straight away on the person's screen. You can change the time in the calendar.",
    "De lijst kon niet geladen worden.": "The list couldn't be loaded.",
    "Bijvoorbeeld: melk, brood": "For example: milk, bread",
    "Product toevoegen": "Add item",
    "Dat is niet gelukt. Probeer het opnieuw.": "That didn't work. Please try again.",
    "{naam} verwijderen": "Delete {naam}",
    "zelf afgevinkt": "ticked off by themselves",
    "automatisch": "automatic",
    "Zorglogboek": "Care log",
    "Wat er gebeurd is, door familie, zorgverleners en de app zelf.": "What happened, recorded by family, carers and the app itself.",
    "Wat gebeurde er?": "What happened?",
    "Samen gewandeld": "Went for a walk together",
    "Notitie, mag leeg blijven": "Note, can be left empty",
    "Vandaag wat vermoeid.": "A bit tired today.",
    "Wissen": "Delete",
    "Nog niets genoteerd deze week.": "Nothing noted this week yet.",
    "Documenten": "Documents",
    "Alleen zichtbaar voor familie. Niet voor zorgverleners, en niet op het scherm van de persoon.": "Only visible to family. Not to carers, and not on the person's screen.",
    "Hospitalisatieverzekering": "Hospital insurance",
    "Categorie": "Category",
    "Bestand": "File",
    "Document toevoegen": "Add document",
    "Zoeken": "Search",
    "Nog niets in deze categorie.": "Nothing in this category yet.",
    "Openen": "Open",
    "geen bestand": "no file",
    "Links naar documenten zijn vijf minuten geldig en niet deelbaar. Verwijderen wist ook het bestand zelf.": "Links to documents are valid for five minutes and cannot be shared. Deleting also removes the file itself.",
    "Identiteit": "Identity",
    "Verzekering": "Insurance",
    "Medisch": "Medical",
    "Afspraken": "Appointments",
    "Belangrijk": "Important",
  },
} satisfies Vertaling
