import type { Vertaling } from '../uiTaal'

/**
 * Familie-schermen: Wie is wie, Home Memory, Herinneringen, Memory Bank,
 * verhalen en levensboek, berichten op het scherm, videobellen.
 */
export default {
  fr: {
    "\"{naam}\" verwijderen uit Wie is wie?": "Retirer « {naam} » de Qui est qui ?",
    "\"{naam}\" verwijderen?": "Supprimer « {naam} » ?",
    "+ Ding toevoegen": "+ Ajouter un objet",
    "+ Herinnering toevoegen": "+ Ajouter un souvenir",
    "+ Persoon toevoegen": "+ Ajouter une personne",
    "+ Weetje toevoegen": "+ Ajouter une info",
    "Aan het spelen": "En cours de lecture",
    "Afdrukken of opslaan als PDF": "Imprimer ou enregistrer en PDF",
    "Alles in orde: bellen hoort nu ook op mobiel internet te werken.": "Tout est en ordre : les appels devraient maintenant aussi fonctionner sur l’internet mobile.",
    "Alles verdwijnt na twee dagen vanzelf. Wil je het eerder weg, dan kan dat hier.": "Tout disparaît automatiquement après deux jours. Pour le retirer plus tôt, c’est ici.",
    "Andere foto": "Autre photo",
    "Annuleren": "Annuler",
    "Begin met een sjabloon, of typ het zelf": "Partez d’un modèle, ou tapez-le vous-même",
    "Bel {naam}": "Appeler {naam}",
    "Bellen lukte niet.": "L’appel n’a pas abouti.",
    "Belt elke avond rond zeven uur.": "Appelle chaque soir vers sept heures.",
    "Beluisteren · {n} sec": "Écouter · {n} s",
    "Beluisteren": "Écouter",
    "Bericht van {naam}": "Message de {naam}",
    "Bezig met laden…": "Chargement…",
    "Bezig met testen… (6 sec)": "Test en cours… (6 s)",
    "Bezig…": "En cours…",
    "Bij de buurvrouw, Rita.": "Chez la voisine, Rita.",
    "Categorie": "Catégorie",
    "Contact": "Contact",
    "Dagboek": "Journal",
    "Dat lukte niet. Je kan alleen weghalen wat je zelf stuurde; de beheerder kan alles weghalen.": "Cela n’a pas fonctionné. Vous ne pouvez retirer que ce que vous avez envoyé vous-même ; l’administrateur peut tout retirer.",
    "De edge function turn-credentials bestaat niet, of de secrets CF_TURN_KEY_ID en CF_TURN_API_TOKEN kloppen niet.": "L’edge function turn-credentials n’existe pas, ou les secrets CF_TURN_KEY_ID et CF_TURN_API_TOKEN sont incorrects.",
    "De edge function turn-credentials gaf gegevens terug.": "L’edge function turn-credentials a renvoyé des identifiants.",
    "De foto kan je kiezen zodra de herinnering bewaard is.": "Vous pourrez choisir la photo dès que le souvenir est enregistré.",
    "Dit bericht weghalen? Het verdwijnt meteen van het scherm.": "Retirer ce message ? Il disparaît immédiatement de l’écran.",
    "Dit verhaal is er niet meer, of het hoort bij een ander huishouden.": "Cette histoire n’existe plus, ou elle appartient à un autre foyer.",
    "Dit verhaal verwijderen? Dat kan niet ongedaan gemaakt worden.": "Supprimer cette histoire ? Cette action est irréversible.",
    "Dit wordt voorgelezen in de rustige modus.": "Ce texte est lu à voix haute en mode calme.",
    "Dochter": "Fille",
    "Doe de deur open.\nDruk op de knop links.": "Ouvrez la porte.\nAppuyez sur le bouton de gauche.",
    "Een foto hoort bij de tekst van die stap. Herschrijf je de zin, dan hoort de foto er niet meer bij en kies je een nieuwe.": "Une photo va avec le texte de cette étape. Si vous réécrivez la phrase, la photo ne correspond plus et vous en choisissez une nouvelle.",
    "Een foto kan je toevoegen zodra de persoon bewaard is.": "Vous pourrez ajouter une photo dès que la personne est enregistrée.",
    "Elke dag stelt de app {naam} één vraag over het eigen leven, en {naam} kan ook zelf iets vertellen in het dagboek. Wat gedeeld wordt, staat hier.": "Chaque jour, l’app pose à {naam} une question sur sa vie, et {naam} peut aussi raconter quelque chose dans le journal. Ce qui est partagé apparaît ici.",
    "Els is je dochter. Ze woont in Leuven.": "Els est ta fille. Elle habite à Louvain.",
    "Er is nog geen TURN-server ingesteld. Bellen werkt dan op wifi, maar meestal niet op 4G of 5G. Zie de edge function": "Aucun serveur TURN n’est encore configuré. Les appels fonctionnent alors en wifi, mais généralement pas en 4G ou 5G. Voir l’edge function",
    "Er staat nu niets. Wat je stuurt, verschijnt hier meteen.": "Rien n’est affiché pour l’instant. Ce que vous envoyez apparaît ici immédiatement.",
    "Er zijn nog geen verhalen. Ze verschijnen hier zodra er een vraag beantwoord is.": "Il n’y a pas encore d’histoires. Elles apparaîtront ici dès qu’une question aura reçu une réponse.",
    "Extra, mag leeg blijven": "En plus, facultatif",
    "Familie": "Famille",
    "Familie, zorgverleners en buren, met een zin die uitlegt wie ze zijn.": "La famille, les soignants et les voisins, avec une phrase qui explique qui ils sont.",
    "Foto bij een stap": "Photo pour une étape",
    "Foto kiezen": "Choisir une photo",
    "Foto uploaden lukte niet.": "Le téléversement de la photo a échoué.",
    "Foto van {naam}": "Photo de {naam}",
    "Foto": "Photo",
    "Foto van {kamer}": "Photo : {kamer}",
    "Foto’s met een jaartal en het verhaal erbij.": "Des photos avec une année et l’histoire qui les accompagne.",
    "Gegevens ontvangen, maar de TURN-server antwoordt niet. Controleer het token bij Cloudflare.": "Identifiants reçus, mais le serveur TURN ne répond pas. Vérifiez le token chez Cloudflare.",
    "Herinneringen": "Souvenirs",
    "Het antwoord, in gewone taal": "La réponse, en langage simple",
    "Het beeld gaat rechtstreeks van toestel naar toestel, versleuteld. Er komt geen dienst van buitenaf aan te pas en er wordt niets opgenomen.": "L’image passe directement d’un appareil à l’autre, chiffrée. Aucun service extérieur n’intervient et rien n’est enregistré.",
    "Het boek": "Le livre",
    "Het leven van": "La vie de",
    "Het verhaal erbij": "L’histoire qui l’accompagne",
    "Home Memory": "Home Memory",
    "Icoon": "Icône",
    "In eigen stem": "De sa propre voix",
    "In eigen woorden verteld": "Raconté avec ses propres mots",
    "Ingesproken bericht van {naam}": "Message vocal de {naam}",
    "Inhoud": "Sommaire",
    "Jaar": "Année",
    "Korte antwoorden op vragen die terugkomen. De spraakassistent gebruikt precies deze weetjes — en niets anders.": "De courtes réponses aux questions qui reviennent. L’assistant vocal utilise exactement ces infos — et rien d’autre.",
    "Korte zinnen, één handeling per lijn. Ze worden als losse kaarten getoond.": "Des phrases courtes, une action par ligne. Elles s’affichent comme des cartes séparées.",
    "Labels, gescheiden door komma’s": "Étiquettes, séparées par des virgules",
    "Lokaal netwerk": "Réseau local",
    "Luister alles ({totaal})": "Tout écouter ({totaal})",
    "Maak er een boek van": "En faire un livre",
    "Maximaal {max} seconden. {naam} hoort je stem, en hoeft niets te lezen.": "{max} secondes maximum. {naam} entend votre voix et n’a rien à lire.",
    "Memory Bank": "Memory Bank",
    "Microfoon wordt gevraagd…": "Demande d’accès au micro…",
    "Microgolfoven": "Micro-ondes",
    "Naam": "Nom",
    "Nodig om überhaupt te bellen. Mislukt dit, dan blokkeert de browser camera of netwerk.": "Indispensable pour pouvoir appeler. Si cela échoue, le navigateur bloque la caméra ou le réseau.",
    "Nog geen verhalen. Ze verschijnen hier zodra {naam} een vraag beantwoordt.": "Pas encore d’histoires. Elles apparaîtront ici dès que {naam} répondra à une question.",
    "Nog niets in deze categorie.": "Rien encore dans cette catégorie.",
    "Nog niets in deze kamer. Voeg toe wat Maria het vaakst zoekt of niet meer kan bedienen.": "Rien encore dans cette pièce. Ajoutez ce que Maria cherche le plus souvent ou ne sait plus utiliser.",
    "Op het aanrecht, rechts van de gootsteen.": "Sur le plan de travail, à droite de l’évier.",
    "Opnemen": "Enregistrer",
    "Opnieuw": "Recommencer",
    "Opslaan lukte niet.": "L’enregistrement a échoué.",
    "Opslaan": "Enregistrer",
    "Opslaan…": "Enregistrement…",
    "Pauze": "Pause",
    "Relatie": "Lien",
    "Reservehuissleutel": "Double de la clé de la maison",
    "STUN — tussen verschillende netwerken": "STUN — entre réseaux différents",
    "Scan om dit verhaal te beluisteren": "Scannez pour écouter cette histoire",
    "Scan om te horen": "Scannez pour écouter",
    "Sluiten": "Fermer",
    "Soort": "Type",
    "Spreek een bericht in voor {naam}": "Enregistrez un message pour {naam}",
    "Staat nu op het scherm": "Actuellement à l’écran",
    "Stap inspreken": "Dicter une étape",
    "Stappen, één per lijn": "Étapes, une par ligne",
    "Stop ({nr}/{totaal})": "Arrêter ({nr}/{totaal})",
    "Stoppen": "Arrêter",
    "TURN — ook op 4G en 5G": "TURN — aussi en 4G et 5G",
    "TURN-gegevens ontvangen": "Identifiants TURN reçus",
    "Telefoon": "Téléphone",
    "Terug": "Retour",
    "Titel": "Titre",
    "Twee weken aan zee, met het hele gezin in de gele auto.": "Deux semaines à la mer, avec toute la famille dans la voiture jaune.",
    "Uit het album": "Extrait de l’album",
    "Uploaden lukte niet.": "Le téléversement a échoué.",
    "Vakantie in Spanje": "Vacances en Espagne",
    "Verbinding testen": "Tester la connexion",
    "Verhalen van {naam}": "Histoires de {naam}",
    "Versturen lukte niet. Controleer je verbinding.": "L’envoi a échoué. Vérifiez votre connexion.",
    "Versturen naar {naam}": "Envoyer à {naam}",
    "Versturen…": "Envoi…",
    "Verteld door {naam}, bewaard door de familie.": "Raconté par {naam}, conservé par la famille.",
    "Verteld in eigen stem — {min} min {sec} sec.": "Raconté de sa propre voix — {min} min {sec} s.",
    "Verteld in eigen stem — {sec} sec.": "Raconté de sa propre voix — {sec} s.",
    "Verteld in eigen stem.": "Raconté de sa propre voix.",
    "Verwijderen": "Supprimer",
    "Videobellen met {naam}": "Appel vidéo avec {naam}",
    "Waar ligt of staat het?": "Où se trouve-t-il ?",
    "Waarover gaat het?": "De quoi s’agit-il ?",
    "Wat er in huis staat, waar het ligt en hoe het werkt.": "Ce qu’il y a dans la maison, où cela se trouve et comment cela fonctionne.",
    "Wat is het?": "Qu’est-ce que c’est ?",
    "Weghalen": "Retirer",
    "Werkt dit, dan lukt bellen tussen twee wifi-netwerken.": "Si cela fonctionne, les appels passent entre deux réseaux wifi.",
    "Wie is dit? In de je-vorm": "Qui est-ce ? En tutoyant",
    "Wie is wie": "Qui est qui",
    "Wijzigen": "Modifier",
    "Zo kort mogelijk. Dit wordt voorgelezen als antwoord op een vraag.": "Le plus court possible. Ce texte est lu à voix haute en réponse à une question.",
    "Zonder TURN-gegevens kan dit niet lukken.": "Sans identifiants TURN, cela ne peut pas fonctionner.",
    "Zorg": "Soins",
    "aan het opnemen": "enregistrement en cours",
    "huis, dagelijks": "maison, quotidien",
    "nog niet bekeken": "pas encore vu",
    "{duur} opgenomen": "{duur} enregistré",
    "{naam} heeft het gezien": "{naam} l’a vu",
    "{n} seconden": "{n} secondes",
    "{n} verhaal": "{n} histoire",
    "{n} verhalen": "{n} histoires",
    "Personen": "Personnes",
    "Plaatsen": "Lieux",
    "Dingen": "Objets",
    "Voorkeuren": "Préférences",
    "Routines": "Routines",
    "Verhalen": "Histoires",
  },
  en: {
    "\"{naam}\" verwijderen uit Wie is wie?": "Remove \"{naam}\" from Who is who?",
    "\"{naam}\" verwijderen?": "Delete \"{naam}\"?",
    "+ Ding toevoegen": "+ Add an item",
    "+ Herinnering toevoegen": "+ Add a memory",
    "+ Persoon toevoegen": "+ Add a person",
    "+ Weetje toevoegen": "+ Add a fact",
    "Aan het spelen": "Playing",
    "Afdrukken of opslaan als PDF": "Print or save as PDF",
    "Alles in orde: bellen hoort nu ook op mobiel internet te werken.": "All good: calls should now also work on mobile data.",
    "Alles verdwijnt na twee dagen vanzelf. Wil je het eerder weg, dan kan dat hier.": "Everything disappears by itself after two days. To remove it sooner, you can do so here.",
    "Andere foto": "Different photo",
    "Annuleren": "Cancel",
    "Begin met een sjabloon, of typ het zelf": "Start from a template, or type it yourself",
    "Bel {naam}": "Call {naam}",
    "Bellen lukte niet.": "The call didn’t go through.",
    "Belt elke avond rond zeven uur.": "Calls every evening around seven.",
    "Beluisteren · {n} sec": "Listen · {n} sec",
    "Beluisteren": "Listen",
    "Bericht van {naam}": "Message from {naam}",
    "Bezig met laden…": "Loading…",
    "Bezig met testen… (6 sec)": "Testing… (6 sec)",
    "Bezig…": "Working…",
    "Bij de buurvrouw, Rita.": "With the neighbour, Rita.",
    "Categorie": "Category",
    "Contact": "Contact",
    "Dagboek": "Diary",
    "Dat lukte niet. Je kan alleen weghalen wat je zelf stuurde; de beheerder kan alles weghalen.": "That didn’t work. You can only remove what you sent yourself; the administrator can remove everything.",
    "De edge function turn-credentials bestaat niet, of de secrets CF_TURN_KEY_ID en CF_TURN_API_TOKEN kloppen niet.": "The edge function turn-credentials does not exist, or the secrets CF_TURN_KEY_ID and CF_TURN_API_TOKEN are incorrect.",
    "De edge function turn-credentials gaf gegevens terug.": "The edge function turn-credentials returned credentials.",
    "De foto kan je kiezen zodra de herinnering bewaard is.": "You can choose the photo once the memory has been saved.",
    "Dit bericht weghalen? Het verdwijnt meteen van het scherm.": "Remove this message? It will disappear from the screen straight away.",
    "Dit verhaal is er niet meer, of het hoort bij een ander huishouden.": "This story no longer exists, or it belongs to another household.",
    "Dit verhaal verwijderen? Dat kan niet ongedaan gemaakt worden.": "Delete this story? This cannot be undone.",
    "Dit wordt voorgelezen in de rustige modus.": "This is read aloud in calm mode.",
    "Dochter": "Daughter",
    "Doe de deur open.\nDruk op de knop links.": "Open the door.\nPress the button on the left.",
    "Een foto hoort bij de tekst van die stap. Herschrijf je de zin, dan hoort de foto er niet meer bij en kies je een nieuwe.": "A photo belongs to the text of that step. If you rewrite the sentence, the photo no longer matches and you choose a new one.",
    "Een foto kan je toevoegen zodra de persoon bewaard is.": "You can add a photo once the person has been saved.",
    "Elke dag stelt de app {naam} één vraag over het eigen leven, en {naam} kan ook zelf iets vertellen in het dagboek. Wat gedeeld wordt, staat hier.": "Every day the app asks {naam} one question about their life, and {naam} can also tell something in the diary. Whatever is shared appears here.",
    "Els is je dochter. Ze woont in Leuven.": "Els is your daughter. She lives in Leuven.",
    "Er is nog geen TURN-server ingesteld. Bellen werkt dan op wifi, maar meestal niet op 4G of 5G. Zie de edge function": "No TURN server has been set up yet. Calls will then work on Wi-Fi, but usually not on 4G or 5G. See the edge function",
    "Er staat nu niets. Wat je stuurt, verschijnt hier meteen.": "Nothing is showing right now. Whatever you send appears here straight away.",
    "Er zijn nog geen verhalen. Ze verschijnen hier zodra er een vraag beantwoord is.": "There are no stories yet. They will appear here as soon as a question has been answered.",
    "Extra, mag leeg blijven": "Extra, optional",
    "Familie": "Family",
    "Familie, zorgverleners en buren, met een zin die uitlegt wie ze zijn.": "Family, carers and neighbours, with a sentence explaining who they are.",
    "Foto bij een stap": "Photo for a step",
    "Foto kiezen": "Choose photo",
    "Foto uploaden lukte niet.": "Uploading the photo didn’t work.",
    "Foto van {naam}": "Photo from {naam}",
    "Foto": "Photo",
    "Foto van {kamer}": "Photo of {kamer}",
    "Foto’s met een jaartal en het verhaal erbij.": "Photos with a year and the story behind them.",
    "Gegevens ontvangen, maar de TURN-server antwoordt niet. Controleer het token bij Cloudflare.": "Credentials received, but the TURN server is not responding. Check the token at Cloudflare.",
    "Herinneringen": "Memories",
    "Het antwoord, in gewone taal": "The answer, in plain language",
    "Het beeld gaat rechtstreeks van toestel naar toestel, versleuteld. Er komt geen dienst van buitenaf aan te pas en er wordt niets opgenomen.": "The video goes directly from device to device, encrypted. No outside service is involved and nothing is recorded.",
    "Het boek": "The book",
    "Het leven van": "The life of",
    "Het verhaal erbij": "The story behind it",
    "Home Memory": "Home Memory",
    "Icoon": "Icon",
    "In eigen stem": "In their own voice",
    "In eigen woorden verteld": "Told in their own words",
    "Ingesproken bericht van {naam}": "Voice message from {naam}",
    "Inhoud": "Contents",
    "Jaar": "Year",
    "Korte antwoorden op vragen die terugkomen. De spraakassistent gebruikt precies deze weetjes — en niets anders.": "Short answers to questions that keep coming up. The voice assistant uses exactly these facts — and nothing else.",
    "Korte zinnen, één handeling per lijn. Ze worden als losse kaarten getoond.": "Short sentences, one action per line. They are shown as separate cards.",
    "Labels, gescheiden door komma’s": "Labels, separated by commas",
    "Lokaal netwerk": "Local network",
    "Luister alles ({totaal})": "Listen to all ({totaal})",
    "Maak er een boek van": "Turn it into a book",
    "Maximaal {max} seconden. {naam} hoort je stem, en hoeft niets te lezen.": "Up to {max} seconds. {naam} hears your voice and doesn’t need to read anything.",
    "Memory Bank": "Memory Bank",
    "Microfoon wordt gevraagd…": "Requesting microphone…",
    "Microgolfoven": "Microwave",
    "Naam": "Name",
    "Nodig om überhaupt te bellen. Mislukt dit, dan blokkeert de browser camera of netwerk.": "Needed to make any call at all. If this fails, the browser is blocking the camera or network.",
    "Nog geen verhalen. Ze verschijnen hier zodra {naam} een vraag beantwoordt.": "No stories yet. They will appear here as soon as {naam} answers a question.",
    "Nog niets in deze categorie.": "Nothing in this category yet.",
    "Nog niets in deze kamer. Voeg toe wat Maria het vaakst zoekt of niet meer kan bedienen.": "Nothing in this room yet. Add what Maria looks for most often or can no longer operate.",
    "Op het aanrecht, rechts van de gootsteen.": "On the worktop, to the right of the sink.",
    "Opnemen": "Record",
    "Opnieuw": "Again",
    "Opslaan lukte niet.": "Saving didn’t work.",
    "Opslaan": "Save",
    "Opslaan…": "Saving…",
    "Pauze": "Pause",
    "Relatie": "Relationship",
    "Reservehuissleutel": "Spare house key",
    "STUN — tussen verschillende netwerken": "STUN — between different networks",
    "Scan om dit verhaal te beluisteren": "Scan to listen to this story",
    "Scan om te horen": "Scan to listen",
    "Sluiten": "Close",
    "Soort": "Type",
    "Spreek een bericht in voor {naam}": "Record a message for {naam}",
    "Staat nu op het scherm": "On the screen now",
    "Stap inspreken": "Dictate a step",
    "Stappen, één per lijn": "Steps, one per line",
    "Stop ({nr}/{totaal})": "Stop ({nr}/{totaal})",
    "Stoppen": "Stop",
    "TURN — ook op 4G en 5G": "TURN — also on 4G and 5G",
    "TURN-gegevens ontvangen": "TURN credentials received",
    "Telefoon": "Phone",
    "Terug": "Back",
    "Titel": "Title",
    "Twee weken aan zee, met het hele gezin in de gele auto.": "Two weeks at the seaside, with the whole family in the yellow car.",
    "Uit het album": "From the album",
    "Uploaden lukte niet.": "Uploading didn’t work.",
    "Vakantie in Spanje": "Holiday in Spain",
    "Verbinding testen": "Test connection",
    "Verhalen van {naam}": "Stories of {naam}",
    "Versturen lukte niet. Controleer je verbinding.": "Sending didn’t work. Check your connection.",
    "Versturen naar {naam}": "Send to {naam}",
    "Versturen…": "Sending…",
    "Verteld door {naam}, bewaard door de familie.": "Told by {naam}, kept by the family.",
    "Verteld in eigen stem — {min} min {sec} sec.": "Told in their own voice — {min} min {sec} sec.",
    "Verteld in eigen stem — {sec} sec.": "Told in their own voice — {sec} sec.",
    "Verteld in eigen stem.": "Told in their own voice.",
    "Verwijderen": "Delete",
    "Videobellen met {naam}": "Video call with {naam}",
    "Waar ligt of staat het?": "Where is it kept?",
    "Waarover gaat het?": "What is it about?",
    "Wat er in huis staat, waar het ligt en hoe het werkt.": "What is in the house, where it is and how it works.",
    "Wat is het?": "What is it?",
    "Weghalen": "Remove",
    "Werkt dit, dan lukt bellen tussen twee wifi-netwerken.": "If this works, calls will work between two Wi-Fi networks.",
    "Wie is dit? In de je-vorm": "Who is this? Addressed as “you”",
    "Wie is wie": "Who is who",
    "Wijzigen": "Edit",
    "Zo kort mogelijk. Dit wordt voorgelezen als antwoord op een vraag.": "As short as possible. This is read aloud as the answer to a question.",
    "Zonder TURN-gegevens kan dit niet lukken.": "This cannot work without TURN credentials.",
    "Zorg": "Care",
    "aan het opnemen": "recording",
    "huis, dagelijks": "home, daily",
    "nog niet bekeken": "not seen yet",
    "{duur} opgenomen": "{duur} recorded",
    "{naam} heeft het gezien": "{naam} has seen it",
    "{n} seconden": "{n} seconds",
    "{n} verhaal": "{n} story",
    "{n} verhalen": "{n} stories",
    "Personen": "People",
    "Plaatsen": "Places",
    "Dingen": "Things",
    "Voorkeuren": "Preferences",
    "Routines": "Routines",
    "Verhalen": "Stories",
  },
} satisfies Vertaling
