import type { Vertaling } from '../uiTaal'

/** Familieschermen: menu, dashboard, dagverhaal, bezoek, delen, privacy. */
export default {
  fr: {
    "Even geduld…": "Un instant…",
    "Beheren": "Gérer",
    "Hoofdnavigatie": "Navigation principale",
    "Scherm van {naam}": "Écran de {naam}",
    "Naar het woonzorgcentrum": "Vers la maison de repos",
    "familiebeheerder": "gestionnaire familial",
    "familie": "famille",
    "zorgverlener": "soignant(e)",
    "persoon": "personne",
    "jij": "vous",
    "{rol} van {naam}": "{rol} de {naam}",
    "Huishouden": "Foyer",
    "Mijn account en wachtwoord": "Mon compte et mot de passe",
    "Uitloggen": "Se déconnecter",
    "Geen verbinding — {n} wijzigingen wordt straks verstuurd": "Pas de connexion — {n} modifications seront envoyées plus tard",
    "Geen verbinding — {n} wijziging wordt straks verstuurd": "Pas de connexion — {n} modification sera envoyée plus tard",
    "Geen verbinding — je ziet de laatst geladen gegevens": "Pas de connexion — vous voyez les dernières données chargées",
    "{n} wijzigingen wordt verstuurd…": "{n} modifications en cours d’envoi…",
    "{n} wijziging wordt verstuurd…": "{n} modification en cours d’envoi…",
    "Nog niet verbonden met de database": "Pas encore connecté à la base de données",
    "De app weet niet met welk Supabase-project ze moet praten. Twee variabelen ontbreken:": "L’application ne sait pas avec quel projet Supabase communiquer. Deux variables manquent :",
    "Open je project op supabase.com en ga naar Project Settings → API.": "Ouvrez votre projet sur supabase.com et allez dans Project Settings → API.",
    "Kopieer de Project URL en de anon public key.": "Copiez la Project URL et la anon public key.",
    "Zet ze in Netlify onder Site configuration → Environment variables.": "Ajoutez-les dans Netlify sous Site configuration → Environment variables.",
    "Klik op Deploys → Trigger deploy. De waarden worden pas bij het bouwen ingebakken.": "Cliquez sur Deploys → Trigger deploy. Les valeurs ne sont intégrées qu’au moment de la compilation.",
    "Die laatste stap wordt het vaakst vergeten: variabelen toevoegen zonder opnieuw te bouwen verandert niets aan de site die al online staat.": "C’est la dernière étape qu’on oublie le plus souvent : ajouter des variables sans recompiler ne change rien au site déjà en ligne.",
    "Er ging iets mis": "Un problème est survenu",
    "Probeer het opnieuw. Blijft het misgaan, laat het dan weten aan je familie.": "Réessayez. Si le problème persiste, prévenez votre famille.",
    "Opnieuw proberen": "Réessayer",
    "Technische details": "Détails techniques",
    "Dashboard": "Tableau de bord",
    "Kalender": "Calendrier",
    "Routines": "Routines",
    "Medicatie": "Médicaments",
    "Familie": "Famille",
    "De week samen": "La semaine ensemble",
    "Home Memory": "Home Memory",
    "Herinneringen": "Souvenirs",
    "Weetjes": "À savoir",
    "Berichten": "Messages",
    "Taken": "Tâches",
    "Boodschappen": "Courses",
    "Analyse": "Analyse",
    "Indeling": "Organisation",
    "Zorglogboek": "Journal de soins",
    "Documenten": "Documents",
    "Wie ziet wat": "Qui voit quoi",
    "Instellingen": "Paramètres",
    "Eén punt van aandacht": "Un point d’attention",
    "{n} medicatiemomenten niet bevestigd": "{n} prises de médicaments non confirmées",
    "{n} medicatiemoment niet bevestigd": "{n} prise de médicaments non confirmée",
    "De dag wijkt af": "La journée sort de l’ordinaire",
    "{n} momenten zijn niet afgevinkt": "{n} moments ne sont pas cochés",
    "Vandaag verloopt normaal": "Aujourd’hui se passe normalement",
    "Geen bijzonderheden": "Rien de particulier",
    "Het overzicht is nu niet te laden.": "L’aperçu ne peut pas être chargé pour le moment.",
    "{naam} gebruikt LifeAngle zelfstandig": "{naam} utilise LifeAngle en autonomie",
    "Je kan mee plannen en berichten sturen. Medicatie, het logboek en persoonlijke notities ziet alleen {naam}, tot {naam} zelf meer deelt.": "Vous pouvez aider à planifier et envoyer des messages. Les médicaments, le journal et les notes personnelles ne sont visibles que par {naam}, jusqu’à ce que {naam} décide d’en partager davantage.",
    "Meer hulp voorstellen": "Proposer plus d’aide",
    "rustig": "calme",
    "opvolgen": "à suivre",
    "Vandaag": "Aujourd’hui",
    "Er staat vandaag nog niets ingepland.": "Rien n’est encore prévu aujourd’hui.",
    "{n} van {totaal} afgevinkt": "{n} sur {totaal} cochés",
    "Aandacht": "Attention",
    "Niets dat opvolging vraagt.": "Rien qui demande un suivi.",
    "Gezien": "Vu",
    "Medicatie vandaag": "Médicaments aujourd’hui",
    "Geen medicatie ingepland.": "Aucun médicament prévu.",
    "✅ genomen": "✅ pris",
    "⚠️ niet bevestigd": "⚠️ non confirmé",
    "🕒 later": "🕒 plus tard",
    "Ongedaan": "Annuler",
    "Bevestigen": "Confirmer",
    "LifeAngle stelt geen diagnose en vervangt geen professionele zorg. Bij twijfel over medicatie: bel de huisarts.": "LifeAngle ne pose aucun diagnostic et ne remplace pas les soins professionnels. En cas de doute sur un médicament : appelez le médecin traitant.",
    "De dag van {naam}": "La journée de {naam}",
    "Klaar om te plakken": "Prêt à coller",
    "Doorsturen": "Transférer",
    "Zelf geschreven vandaag": "Écrit aujourd’hui",
    "Dit wordt niet mee doorgestuurd.": "Ceci n’est pas transféré.",
    "Alleen wat in de app staat. Geen beoordeling van de gezondheid.": "Uniquement ce qui figure dans l’application. Aucune évaluation de la santé.",
    "{begin} en {laatste}": "{begin} et {laatste}",
    "in de voormiddag": "dans la matinée",
    "in de namiddag": "dans l’après-midi",
    "'s avonds": "en soirée",
    "{naam} vinkte vandaag {lijst} af.": "Aujourd’hui, {naam} a coché : {lijst}.",
    "{naam} vinkte vandaag {lijst} af, en nog {n} ander.": "Aujourd’hui, {naam} a coché : {lijst}, et {n} autre chose.",
    "{naam} vinkte vandaag {lijst} af, en nog {n} andere.": "Aujourd’hui, {naam} a coché : {lijst}, et {n} autres choses.",
    "Er is vandaag nog niets afgevinkt.": "Rien n’a encore été coché aujourd’hui.",
    "{naam} was op bezoek {dagdeel}.": "{naam} est venu(e) en visite {dagdeel}.",
    "{naam} was vandaag bij {lijst}.": "Aujourd’hui, {naam} a participé à : {lijst}.",
    "{naam} was op uitstap met {wie}.": "{naam} est sorti(e) avec {wie}.",
    "{naam} is op uitstap met {wie}.": "{naam} est en sortie avec {wie}.",
    "Alle medicatie tot nu toe is bevestigd.": "Tous les médicaments jusqu’à présent ont été confirmés.",
    "De medicatie van {uren} is nog niet bevestigd.": "Les médicaments de {uren} ne sont pas encore confirmés.",
    "Nog op de planning: {wat} om {uur}.": "Encore au programme : {wat} à {uur}.",
    "Over vandaag staat er nog niets in de app.": "Rien n’est encore noté pour aujourd’hui dans l’application.",
    "Het bezoekboek staat nog niet aan. Vraag de beheerder om de update te installeren.": "Le livre des visites n’est pas encore activé. Demandez au gestionnaire d’installer la mise à jour.",
    "Het bezoek kon niet bewaard worden.": "La visite n’a pas pu être enregistrée.",
    "Wie was er hier?": "Qui est passé ?",
    "Leg je bezoek vast, dan ziet {naam} het de rest van de dag op het scherm en vergeet het niet.": "Notez votre visite : {naam} la verra à l’écran le reste de la journée et ne l’oubliera pas.",
    "Wie kwam er langs bij {naam}? De familie en {naam} zien het.": "Qui est venu voir {naam} ? La famille et {naam} le verront.",
    "Ik was op bezoek": "J’étais en visite",
    "Bezoek vastleggen": "Noter une visite",
    "Bewaard. {naam} ziet op het scherm:": "Enregistré. {naam} voit à l’écran :",
    "De foto kon niet mee; het bezoek staat er wel.": "La photo n’a pas pu être ajoutée ; la visite est bien enregistrée.",
    "Wie?": "Qui ?",
    "Iemand anders": "Quelqu’un d’autre",
    "Naam": "Nom",
    "Naam, bv. Tante Lea": "Nom, p. ex. Tante Léa",
    "Bv. de kapster, een vrijwilliger": "P. ex. la coiffeuse, un bénévole",
    "Wanneer?": "Quand ?",
    "Net": "À l’instant",
    "Eerder vandaag": "Plus tôt aujourd’hui",
    "Gisteren": "Hier",
    "om": "à",
    "Wat deden jullie?": "Qu’avez-vous fait ?",
    "(mag leeg)": "(facultatif)",
    "Inspreken": "Dicter",
    "Samen koffie gedronken en over Spanje gepraat.": "Pris un café ensemble et parlé de l’Espagne.",
    "Gekozen foto": "Photo choisie",
    "Foto weghalen": "Retirer la photo",
    "Foto toevoegen": "Ajouter une photo",
    "Een foto van jullie samen helpt het meest om het te onthouden.": "Une photo de vous ensemble aide le plus à s’en souvenir.",
    "Bezig…": "En cours…",
    "Bewaren": "Enregistrer",
    "Annuleren": "Annuler",
    "Deze week": "Cette semaine",
    "Dit bezoek wissen?": "Supprimer cette visite ?",
    "Bezoek van {naam} wissen": "Supprimer la visite de {naam}",
    "Deze week nog geen bezoek vastgelegd.": "Aucune visite notée cette semaine.",
    "Om over te praten": "Pour la conversation",
    "Ga je langs? Vandaag twee ideeën. Morgen andere.": "Vous passez ? Deux idées aujourd’hui. D’autres demain.",
    "{titel}. Toon de foto en vraag wat {naam} zich ervan herinnert.": "{titel}. Montrez la photo et demandez à {naam} ce dont il ou elle se souvient.",
    "{naam} vertelde over \"{vraag}\". Vraag er eens meer over.": "{naam} a raconté « {vraag} ». Demandez-en un peu plus.",
    "daar": "à vous",
    "Familie en contacten": "Famille et contacts",
    "Wie er is, en wie mee kan zorgen.": "Qui est là, et qui peut aider à prendre soin.",
    "Waar dingen liggen en hoe ze werken. Dit is het invulwerk dat het verschil maakt.": "Où se trouvent les choses et comment elles fonctionnent. C’est ce travail de saisie qui fait la différence.",
    "Dit huis is gedeeld met {naam}. Wat je hier wijzigt, zien zij ook.": "Cette maison est partagée avec {naam}. Ce que vous modifiez ici, ils le voient aussi.",
    "Foto’s met een jaartal en het verhaal erbij.": "Des photos avec une année et leur histoire.",
    "Bellen gaat rechtstreeks. Een ingesproken bericht verschijnt bovenaan het scherm van {naam}, ook als ze nu niet kan opnemen.": "Les appels sont directs. Un message vocal apparaît en haut de l’écran de {naam}, même si elle ne peut pas décrocher maintenant.",
    "Foto sturen": "Envoyer une photo",
    "Eén foto, met een korte zin erbij. Die komt bovenaan het scherm van {naam}.": "Une photo, avec une courte phrase. Elle apparaît en haut de l’écran de {naam}.",
    "Wat staat erop?": "Qu’y a-t-il sur la photo ?",
    "Lotte op het strand in Oostende": "Lotte sur la plage à Ostende",
    "Foto kiezen en sturen": "Choisir et envoyer une photo",
    "Bezig met sturen…": "Envoi en cours…",
    "Verstuurd.": "Envoyé.",
    "Uitnodigen lukte niet.": "L’invitation n’a pas abouti.",
    "Iemand uitnodigen": "Inviter quelqu’un",
    "Voor wie mee wil zorgen voor {naam}. De link werkt alleen voor het adres dat je hier invult.": "Pour qui souhaite aider à prendre soin de {naam}. Le lien ne fonctionne que pour l’adresse saisie ici.",
    "E-mailadres": "Adresse e-mail",
    "Rol": "Rôle",
    "Familielid": "Membre de la famille",
    "Familiebeheerder": "Gestionnaire familial",
    "Zorgverlener": "Soignant(e)",
    "De persoon zelf": "La personne elle-même",
    "Relatie": "Lien",
    "Zoon": "Fils",
    "Uitnodiging maken": "Créer l’invitation",
    "Verstuurd naar {email}. Of geef de link zelf door:": "Envoyé à {email}. Ou transmettez le lien vous-même :",
    "Klaar. Stuur deze link naar {email}:": "C’est prêt. Envoyez ce lien à {email} :",
    "Gekopieerd": "Copié",
    "Kopieer link": "Copier le lien",
    "Zeven dagen geldig, eenmalig te gebruiken.": "Valable sept jours, à usage unique.",
    "Open LifeAngle op de tablet van {naam}, kies {knop}, en tik daar deze code in. {naam} hoeft geen mail of wachtwoord te hebben.": "Ouvrez LifeAngle sur la tablette de {naam}, choisissez {knop}, puis saisissez ce code. {naam} n’a besoin ni d’e-mail ni de mot de passe.",
    "Tablet koppelen": "Associer la tablette",
    "Dit is de tablet van de persoon": "C’est la tablette de la personne",
    "Nog {tijd} geldig": "Encore valable {tijd}",
    "Nieuwe code": "Nouveau code",
    "Code maken": "Créer un code",
    "Code maken lukte niet.": "Le code n’a pas pu être créé.",
    "Ik doe het zelf": "Je me débrouille seul(e)",
    "Je gebruikt LifeAngle voor jezelf. Familie kan mee plannen, maar kijkt niet mee.": "Vous utilisez LifeAngle pour vous-même. La famille peut aider à planifier, mais ne regarde pas.",
    "Familie ziet de agenda. Niet je medicatie, logboek, notities of locatie. Geen meldingen.": "La famille voit l’agenda. Pas vos médicaments, votre journal, vos notes ni votre position. Pas d’alertes.",
    "We doen het samen": "On le fait ensemble",
    "Familie helpt mee met plannen en invullen, en kan zien hoe je dag verloopt.": "La famille aide à planifier et à compléter, et peut voir comment se passe votre journée.",
    "Familie ziet de agenda, medicatie en het logboek. Nog steeds geen meldingen.": "La famille voit l’agenda, les médicaments et le journal. Toujours pas d’alertes.",
    "Help me meer": "Aidez-moi davantage",
    "Familie krijgt een seintje als er iets afwijkt, zoals vergeten medicatie.": "La famille est prévenue quand quelque chose sort de l’ordinaire, comme un médicament oublié.",
    "Familie ziet alles wat nodig is, en krijgt meldingen bij afwijkingen.": "La famille voit tout ce qui est nécessaire et reçoit des alertes en cas d’écart.",
    "Beheerder": "Gestionnaire",
    "Tablet van de persoon": "Tablette de la personne",
    "Wat {naam} deelt": "Ce que {naam} partage",
    "Jij beslist hoeveel je familie meekijkt. Minder kan altijd; meer vraagt jouw ja.": "C’est vous qui décidez de ce que votre famille peut voir. Moins, c’est toujours possible ; plus, il faut votre accord.",
    "Als beheerder pas je dit meteen aan. Elke wijziging komt in het zorglogboek, zodat {naam} altijd kan zien wat er veranderde.": "En tant que gestionnaire, vous modifiez ceci immédiatement. Chaque changement est noté dans le journal de soins, pour que {naam} puisse toujours voir ce qui a changé.",
    "Je familie stelt voor om meer te helpen": "Votre famille propose de vous aider davantage",
    "Voorstel:": "Proposition :",
    "Ja, dat is goed": "Oui, c’est d’accord",
    "Nee, nog niet": "Non, pas encore",
    "Hoeveel hulp": "Combien d’aide",
    "nu": "actuel",
    "Aangepast. Het staat in het zorglogboek.": "Modifié. C’est noté dans le journal de soins.",
    "Alleen de familiebeheerder kan dit wijzigen.": "Seul le gestionnaire familial peut modifier ceci.",
    "Dat lukte niet.": "Cela n’a pas fonctionné.",
    "Wat ik laat onthouden": "Ce que je fais retenir",
    "Familie kan zien wat je via \"Onthoud dit\" noteert, zodra ze meekijken.": "La famille peut voir ce que vous notez via « Retiens ceci », dès qu’elle peut regarder.",
    "Alleen jij ziet wat je via \"Onthoud dit\" noteert.": "Vous seul(e) voyez ce que vous notez via « Retiens ceci ».",
    "Notities delen met familie": "Partager les notes avec la famille",
    "Wie er bij hoort": "Qui en fait partie",
    "Onbekend": "Inconnu",
    "{naam} ook beheerder maken?": "Faire aussi de {naam} un gestionnaire ?",
    "Deze persoon": "Cette personne",
    "Maak beheerder": "Nommer gestionnaire",
    "{naam} geen toegang meer geven?": "Retirer l’accès à {naam} ?",
    "Toegang weghalen": "Retirer l’accès",
    "Je familie stelt iets voor": "Votre famille vous propose quelque chose",
    "Ze willen je wat meer helpen. Jij beslist. Tik om te bekijken.": "Ils aimeraient vous aider un peu plus. C’est vous qui décidez. Touchez pour voir.",
    "Noodtoegang": "Accès d’urgence",
    "Een teamverantwoordelijke van het woonzorgcentrum kan in een noodgeval 4 uur meekijken: naam, voorkeuren, agenda, logboek en contactpersonen. Geen dagboek, documenten of locatie.": "En cas d’urgence, un responsable d’équipe de la maison de repos peut consulter pendant 4 heures : nom, préférences, agenda, journal et personnes de contact. Pas le journal intime, les documents ni la position.",
    "Loopt nog tot {uur}": "En cours jusqu’à {uur}",
    "Gestopt": "Arrêté",
    "Afgelopen": "Terminé",
    "gestart {wanneer}": "commencé {wanneer}",
    "Nog niets ingekeken.": "Rien consulté pour l’instant.",
    "1 keer ingekeken.": "Consulté 1 fois.",
    "{n} keer ingekeken.": "Consulté {n} fois.",
    "Deze noodtoegang nu stoppen?": "Arrêter cet accès d’urgence maintenant ?",
    "Nu stoppen": "Arrêter maintenant",
    "Stoppen lukte niet.": "L’arrêt n’a pas fonctionné.",
    "Wie bekeek wat": "Qui a consulté quoi",
    "De laatste 30 dagen: wie een document opende, een opname beluisterde of de locatie bekeek. Wat {naam} zelf bekijkt, staat hier niet. Alleen beheerders zien dit.": "Les 30 derniers jours : qui a ouvert un document, écouté un enregistrement ou consulté la position. Ce que {naam} consulte soi-même n’apparaît pas ici. Seuls les gestionnaires voient ceci.",
    "Bezig met laden…": "Chargement…",
    "Dit overzicht kon niet geladen worden.": "Cet aperçu n’a pas pu être chargé.",
    "Niemand bekeek de laatste 30 dagen documenten, opnames of de locatie.": "Personne n’a consulté de documents, d’enregistrements ni la position ces 30 derniers jours.",
    "Woonzorgcentrum": "Maison de repos et de soins",
    "Afdeling {naam}": "Unité {naam}",
    "kamer {nr}": "chambre {nr}",
    "Afdeling en kamer zijn nog niet ingevuld.": "L’unité et la chambre ne sont pas encore renseignées.",
    "Alleen de medewerkers die {naam} volgen, zien de agenda en de contactpersonen en schrijven zorgnotities. Wat zij voor de familie bedoelen, staat hieronder. De directie of beheerder van het woonzorgcentrum ziet geen persoonlijke gegevens. Dagboek, documenten en locatie blijven bij de familie.": "Seuls les membres du personnel qui suivent {naam} voient l’agenda et les personnes de contact, et rédigent des notes de soins. Ce qu’ils destinent à la famille figure ci-dessous. La direction ou le gestionnaire de la maison de repos ne voit aucune donnée personnelle. Le journal intime, les documents et la position restent dans la famille.",
    "Wie volgt {naam}": "Qui suit {naam}",
    "team lead van de afdeling": "responsable de l’unité",
    "toegewezen": "attitré(e)",
    "Van het zorgteam": "De l’équipe soignante",
    "De koppeling met {naam} stoppen? De medewerkers verliezen meteen hun toegang.": "Arrêter la liaison avec {naam} ? Le personnel perd immédiatement son accès.",
    "Koppeling stoppen": "Arrêter la liaison",
    "Gaat {naam} in een woonzorgcentrum wonen dat LifeAngle gebruikt? Vraag er de koppelcode en vul die hier in. Het team dat {naam} volgt, ziet dan de agenda en de contactpersonen, en schrijft zorgnotities.": "{naam} va habiter dans une maison de repos qui utilise LifeAngle ? Demandez-y le code de liaison et saisissez-le ici. L’équipe qui suit {naam} verra alors l’agenda et les personnes de contact, et rédigera des notes de soins.",
    "Koppelcode": "Code de liaison",
    "Koppelen": "Lier",
    "Koppelen lukte niet.": "La liaison n’a pas fonctionné.",
    "Gekoppeld met {naam}.": "Lié à {naam}.",
    "Downloaden lukte niet.": "Le téléchargement n’a pas fonctionné.",
    "Verwijderen lukte niet.": "La suppression n’a pas fonctionné.",
    "Wat LifeAngle bewaart, waarom, en hoe lang, staat in de {link}.": "Ce que LifeAngle conserve, pourquoi et combien de temps : tout est expliqué dans la {link}.",
    "Typ {woord} om te bevestigen": "Tapez {woord} pour confirmer",
    "Mijn gegevens": "Mes données",
    "privacyverklaring": "déclaration de confidentialité",
    "Bezig met verzamelen…": "Collecte en cours…",
    "Download mijn gegevens": "Télécharger mes données",
    "Eén bestand met alles wat jij in de app kan zien. Foto’s, opnames en documenten staan erin als verwijzing.": "Un seul fichier avec tout ce que vous pouvez voir dans l’application. Les photos, enregistrements et documents y figurent sous forme de référence.",
    "Mijn account verwijderen": "Supprimer mon compte",
    "Je account verwijderen": "Supprimer votre compte",
    "Je kan niet meer inloggen, en je profiel verdwijnt.": "Vous ne pourrez plus vous connecter, et votre profil disparaît.",
    "Gaat een huishouden over jou, of ben je er alleen in, dan verdwijnt het mee — met alle foto’s, verhalen en documenten.": "Si un foyer vous concerne, ou si vous en êtes le seul membre, il disparaît aussi — avec toutes les photos, histoires et documents.",
    "Zijn er nog anderen, dan blijft het huishouden bestaan. Wat je schreef, blijft staan zonder je naam.": "S’il y a d’autres membres, le foyer est conservé. Ce que vous avez écrit reste, sans votre nom.",
    "Dit kan niet ongedaan gemaakt worden. Download eerst je gegevens als je ze wil houden.": "Cette action est irréversible. Téléchargez d’abord vos données si vous souhaitez les garder.",
    "Ben ik de enige beheerder van een huishouden waar nog anderen in zitten, verwijder dat huishouden dan ook.": "Si je suis le seul gestionnaire d’un foyer qui compte encore d’autres membres, supprimez aussi ce foyer.",
    "Definitief verwijderen": "Supprimer définitivement",
    "Wat LifeAngle bewaart": "Ce que LifeAngle conserve",
    "Je naam en e-mailadres, om in te loggen.": "Votre nom et votre adresse e-mail, pour vous connecter.",
    "Wat jij of je familie invult: de agenda, routines, mensen, dingen in huis, foto’s, verhalen, weetjes en berichten.": "Ce que vous ou votre famille saisissez : l’agenda, les routines, les personnes, les objets de la maison, les photos, les histoires, les choses à savoir et les messages.",
    "Medicatie en het zorglogboek, als die gebruikt worden. Dat zijn gezondheidsgegevens, en die krijgen extra bescherming.": "Les médicaments et le journal de soins, s’ils sont utilisés. Ce sont des données de santé, qui bénéficient d’une protection renforcée.",
    "Je locatie, alleen als je daar uitdrukkelijk toestemming voor gaf.": "Votre position, uniquement si vous l’avez explicitement autorisé.",
    "Waarom": "Pourquoi",
    "Alleen om de app te laten werken: je dag tonen, je helpen onthouden, en je familie laten meehelpen voor zover jij dat toelaat.": "Uniquement pour faire fonctionner l’application : afficher votre journée, vous aider à vous souvenir, et permettre à votre famille d’aider dans la mesure où vous l’acceptez.",
    "Niet voor reclame. Er worden geen gegevens verkocht of gedeeld met adverteerders.": "Pas pour de la publicité. Aucune donnée n’est vendue ni partagée avec des annonceurs.",
    "Wie het kan zien": "Qui peut le voir",
    "Alleen de mensen die jij of je familiebeheerder uitnodigde, en alleen wat bij hun rol past.": "Uniquement les personnes que vous ou votre gestionnaire familial avez invitées, et uniquement ce qui correspond à leur rôle.",
    "In de zelfstandige fase ziet familie je medicatie, logboek, notities en locatie niet. Onder \"Wie ziet wat\" zie je altijd wie er meekijkt.": "En phase autonome, la famille ne voit pas vos médicaments, votre journal, vos notes ni votre position. Sous « Qui voit quoi », vous voyez toujours qui peut regarder.",
    "Zorgverleners zien geen documenten.": "Les soignants ne voient pas les documents.",
    "Waar het staat": "Où c’est stocké",
    "In een database bij Supabase, in een datacenter in de Europese Unie.": "Dans une base de données chez Supabase, dans un centre de données de l’Union européenne.",
    "Foto’s en documenten staan in afgeschermde opslag; een link ernaartoe werkt maar even.": "Les photos et documents sont dans un stockage protégé ; un lien vers eux ne fonctionne que peu de temps.",
    "Videogesprekken gaan rechtstreeks van toestel naar toestel, versleuteld. Er wordt geen beeld of geluid bewaard.": "Les appels vidéo passent directement d’un appareil à l’autre, chiffrés. Aucune image ni aucun son n’est conservé.",
    "Hoe lang": "Combien de temps",
    "Locatiegegevens: zeven dagen.": "Données de position : sept jours.",
    "Berichten aan de persoon: verdwijnen van het scherm na twee dagen, en worden daarna gewist.": "Messages à la personne : disparaissent de l’écran après deux jours, puis sont effacés.",
    "Al het andere: tot je het zelf verwijdert, of tot je je account verwijdert.": "Tout le reste : jusqu’à ce que vous le supprimiez vous-même, ou que vous supprimiez votre compte.",
    "Jouw rechten": "Vos droits",
    "Je kan al je gegevens downloaden, onder Instellingen → Mijn gegevens.": "Vous pouvez télécharger toutes vos données, sous Paramètres → Mes données.",
    "Je kan je account verwijderen, op dezelfde plek. Wat alleen over jou gaat, verdwijnt mee.": "Vous pouvez supprimer votre compte au même endroit. Ce qui ne concerne que vous disparaît aussi.",
    "Je kan toestemming voor locatie altijd weer intrekken.": "Vous pouvez toujours retirer votre autorisation de localisation.",
    "Heb je een vraag of een klacht, dan kan je ook terecht bij de Gegevensbeschermingsautoriteit.": "Pour une question ou une plainte, vous pouvez aussi vous adresser à l’Autorité de protection des données.",
    "‹ Terug": "‹ Retour",
    "Privacy": "Confidentialité",
    "Wat LifeAngle bewaart, waarom, en wat je ermee kan. In gewone taal.": "Ce que LifeAngle conserve, pourquoi, et ce que vous pouvez en faire. En langage simple.",
  },
  en: {
    "Even geduld…": "One moment…",
    "Beheren": "Manage",
    "Hoofdnavigatie": "Main navigation",
    "Scherm van {naam}": "{naam}'s screen",
    "Naar het woonzorgcentrum": "To the care home",
    "familiebeheerder": "family administrator",
    "familie": "family",
    "zorgverlener": "carer",
    "persoon": "person",
    "jij": "you",
    "{rol} van {naam}": "{rol} for {naam}",
    "Huishouden": "Household",
    "Mijn account en wachtwoord": "My account and password",
    "Uitloggen": "Log out",
    "Geen verbinding — {n} wijzigingen wordt straks verstuurd": "No connection — {n} changes will be sent shortly",
    "Geen verbinding — {n} wijziging wordt straks verstuurd": "No connection — {n} change will be sent shortly",
    "Geen verbinding — je ziet de laatst geladen gegevens": "No connection — you are seeing the last data loaded",
    "{n} wijzigingen wordt verstuurd…": "Sending {n} changes…",
    "{n} wijziging wordt verstuurd…": "Sending {n} change…",
    "Nog niet verbonden met de database": "Not yet connected to the database",
    "De app weet niet met welk Supabase-project ze moet praten. Twee variabelen ontbreken:": "The app does not know which Supabase project to talk to. Two variables are missing:",
    "Open je project op supabase.com en ga naar Project Settings → API.": "Open your project on supabase.com and go to Project Settings → API.",
    "Kopieer de Project URL en de anon public key.": "Copy the Project URL and the anon public key.",
    "Zet ze in Netlify onder Site configuration → Environment variables.": "Add them in Netlify under Site configuration → Environment variables.",
    "Klik op Deploys → Trigger deploy. De waarden worden pas bij het bouwen ingebakken.": "Click Deploys → Trigger deploy. The values are only built in when the site is built.",
    "Die laatste stap wordt het vaakst vergeten: variabelen toevoegen zonder opnieuw te bouwen verandert niets aan de site die al online staat.": "That last step is the one most often forgotten: adding variables without rebuilding changes nothing on the site that is already live.",
    "Er ging iets mis": "Something went wrong",
    "Probeer het opnieuw. Blijft het misgaan, laat het dan weten aan je familie.": "Please try again. If it keeps going wrong, let your family know.",
    "Opnieuw proberen": "Try again",
    "Technische details": "Technical details",
    "Dashboard": "Dashboard",
    "Kalender": "Calendar",
    "Routines": "Routines",
    "Medicatie": "Medication",
    "Familie": "Family",
    "De week samen": "The week together",
    "Home Memory": "Home Memory",
    "Herinneringen": "Memories",
    "Weetjes": "Good to know",
    "Berichten": "Messages",
    "Taken": "Tasks",
    "Boodschappen": "Shopping",
    "Analyse": "Insights",
    "Indeling": "Layout",
    "Zorglogboek": "Care log",
    "Documenten": "Documents",
    "Wie ziet wat": "Who sees what",
    "Instellingen": "Settings",
    "Eén punt van aandacht": "One thing to look at",
    "{n} medicatiemomenten niet bevestigd": "{n} medication times not confirmed",
    "{n} medicatiemoment niet bevestigd": "{n} medication time not confirmed",
    "De dag wijkt af": "The day is different from usual",
    "{n} momenten zijn niet afgevinkt": "{n} moments have not been ticked off",
    "Vandaag verloopt normaal": "Today is going as usual",
    "Geen bijzonderheden": "Nothing to report",
    "Het overzicht is nu niet te laden.": "The overview cannot be loaded right now.",
    "{naam} gebruikt LifeAngle zelfstandig": "{naam} uses LifeAngle independently",
    "Je kan mee plannen en berichten sturen. Medicatie, het logboek en persoonlijke notities ziet alleen {naam}, tot {naam} zelf meer deelt.": "You can help plan and send messages. Only {naam} sees medication, the log and personal notes, until {naam} chooses to share more.",
    "Meer hulp voorstellen": "Suggest more help",
    "rustig": "calm",
    "opvolgen": "follow up",
    "Vandaag": "Today",
    "Er staat vandaag nog niets ingepland.": "Nothing is planned for today yet.",
    "{n} van {totaal} afgevinkt": "{n} of {totaal} ticked off",
    "Aandacht": "Attention",
    "Niets dat opvolging vraagt.": "Nothing that needs following up.",
    "Gezien": "Seen",
    "Medicatie vandaag": "Medication today",
    "Geen medicatie ingepland.": "No medication planned.",
    "✅ genomen": "✅ taken",
    "⚠️ niet bevestigd": "⚠️ not confirmed",
    "🕒 later": "🕒 later",
    "Ongedaan": "Undo",
    "Bevestigen": "Confirm",
    "LifeAngle stelt geen diagnose en vervangt geen professionele zorg. Bij twijfel over medicatie: bel de huisarts.": "LifeAngle does not diagnose and does not replace professional care. If in doubt about medication: call the GP.",
    "De dag van {naam}": "{naam}'s day",
    "Klaar om te plakken": "Ready to paste",
    "Doorsturen": "Forward",
    "Zelf geschreven vandaag": "Written today",
    "Dit wordt niet mee doorgestuurd.": "This is not forwarded.",
    "Alleen wat in de app staat. Geen beoordeling van de gezondheid.": "Only what is in the app. No assessment of health.",
    "{begin} en {laatste}": "{begin} and {laatste}",
    "in de voormiddag": "in the morning",
    "in de namiddag": "in the afternoon",
    "'s avonds": "in the evening",
    "{naam} vinkte vandaag {lijst} af.": "Today {naam} ticked off {lijst}.",
    "{naam} vinkte vandaag {lijst} af, en nog {n} ander.": "Today {naam} ticked off {lijst}, and {n} other thing.",
    "{naam} vinkte vandaag {lijst} af, en nog {n} andere.": "Today {naam} ticked off {lijst}, and {n} other things.",
    "Er is vandaag nog niets afgevinkt.": "Nothing has been ticked off yet today.",
    "{naam} was op bezoek {dagdeel}.": "{naam} visited {dagdeel}.",
    "{naam} was vandaag bij {lijst}.": "Today {naam} took part in {lijst}.",
    "{naam} was op uitstap met {wie}.": "{naam} went on an outing with {wie}.",
    "{naam} is op uitstap met {wie}.": "{naam} is on an outing with {wie}.",
    "Alle medicatie tot nu toe is bevestigd.": "All medication so far has been confirmed.",
    "De medicatie van {uren} is nog niet bevestigd.": "The {uren} medication has not been confirmed yet.",
    "Nog op de planning: {wat} om {uur}.": "Still planned: {wat} at {uur}.",
    "Over vandaag staat er nog niets in de app.": "There is nothing in the app about today yet.",
    "Het bezoekboek staat nog niet aan. Vraag de beheerder om de update te installeren.": "The visitor book is not switched on yet. Ask the administrator to install the update.",
    "Het bezoek kon niet bewaard worden.": "The visit could not be saved.",
    "Wie was er hier?": "Who visited?",
    "Leg je bezoek vast, dan ziet {naam} het de rest van de dag op het scherm en vergeet het niet.": "Record your visit, so {naam} sees it on screen for the rest of the day and won't forget it.",
    "Wie kwam er langs bij {naam}? De familie en {naam} zien het.": "Who came to see {naam}? The family and {naam} will see it.",
    "Ik was op bezoek": "I visited",
    "Bezoek vastleggen": "Record a visit",
    "Bewaard. {naam} ziet op het scherm:": "Saved. {naam} sees on screen:",
    "De foto kon niet mee; het bezoek staat er wel.": "The photo could not be added; the visit has been saved.",
    "Wie?": "Who?",
    "Iemand anders": "Someone else",
    "Naam": "Name",
    "Naam, bv. Tante Lea": "Name, e.g. Aunt Lea",
    "Bv. de kapster, een vrijwilliger": "E.g. the hairdresser, a volunteer",
    "Wanneer?": "When?",
    "Net": "Just now",
    "Eerder vandaag": "Earlier today",
    "Gisteren": "Yesterday",
    "om": "at",
    "Wat deden jullie?": "What did you do?",
    "(mag leeg)": "(optional)",
    "Inspreken": "Dictate",
    "Samen koffie gedronken en over Spanje gepraat.": "Had coffee together and talked about Spain.",
    "Gekozen foto": "Chosen photo",
    "Foto weghalen": "Remove photo",
    "Foto toevoegen": "Add photo",
    "Een foto van jullie samen helpt het meest om het te onthouden.": "A photo of you together helps most to remember it.",
    "Bezig…": "Working…",
    "Bewaren": "Save",
    "Annuleren": "Cancel",
    "Deze week": "This week",
    "Dit bezoek wissen?": "Delete this visit?",
    "Bezoek van {naam} wissen": "Delete {naam}'s visit",
    "Deze week nog geen bezoek vastgelegd.": "No visits recorded this week yet.",
    "Om over te praten": "Things to talk about",
    "Ga je langs? Vandaag twee ideeën. Morgen andere.": "Visiting? Two ideas today. Different ones tomorrow.",
    "{titel}. Toon de foto en vraag wat {naam} zich ervan herinnert.": "{titel}. Show the photo and ask what {naam} remembers about it.",
    "{naam} vertelde over \"{vraag}\". Vraag er eens meer over.": "{naam} talked about \"{vraag}\". Ask a little more about it.",
    "daar": "there",
    "Familie en contacten": "Family and contacts",
    "Wie er is, en wie mee kan zorgen.": "Who is there, and who can help care.",
    "Waar dingen liggen en hoe ze werken. Dit is het invulwerk dat het verschil maakt.": "Where things are and how they work. This is the filling-in that makes the difference.",
    "Dit huis is gedeeld met {naam}. Wat je hier wijzigt, zien zij ook.": "This home is shared with {naam}. What you change here, they see too.",
    "Foto’s met een jaartal en het verhaal erbij.": "Photos with a year and the story behind them.",
    "Bellen gaat rechtstreeks. Een ingesproken bericht verschijnt bovenaan het scherm van {naam}, ook als ze nu niet kan opnemen.": "Calls go straight through. A voice message appears at the top of {naam}'s screen, even if she cannot answer right now.",
    "Foto sturen": "Send a photo",
    "Eén foto, met een korte zin erbij. Die komt bovenaan het scherm van {naam}.": "One photo, with a short sentence. It appears at the top of {naam}'s screen.",
    "Wat staat erop?": "What is in it?",
    "Lotte op het strand in Oostende": "Lotte on the beach in Ostend",
    "Foto kiezen en sturen": "Choose and send a photo",
    "Bezig met sturen…": "Sending…",
    "Verstuurd.": "Sent.",
    "Uitnodigen lukte niet.": "The invitation did not work.",
    "Iemand uitnodigen": "Invite someone",
    "Voor wie mee wil zorgen voor {naam}. De link werkt alleen voor het adres dat je hier invult.": "For anyone who wants to help care for {naam}. The link only works for the address you enter here.",
    "E-mailadres": "Email address",
    "Rol": "Role",
    "Familielid": "Family member",
    "Familiebeheerder": "Family administrator",
    "Zorgverlener": "Carer",
    "De persoon zelf": "The person themselves",
    "Relatie": "Relationship",
    "Zoon": "Son",
    "Uitnodiging maken": "Create invitation",
    "Verstuurd naar {email}. Of geef de link zelf door:": "Sent to {email}. Or pass on the link yourself:",
    "Klaar. Stuur deze link naar {email}:": "Done. Send this link to {email}:",
    "Gekopieerd": "Copied",
    "Kopieer link": "Copy link",
    "Zeven dagen geldig, eenmalig te gebruiken.": "Valid for seven days, single use.",
    "Open LifeAngle op de tablet van {naam}, kies {knop}, en tik daar deze code in. {naam} hoeft geen mail of wachtwoord te hebben.": "Open LifeAngle on {naam}'s tablet, choose {knop}, and enter this code there. {naam} does not need an email address or password.",
    "Tablet koppelen": "Pair the tablet",
    "Dit is de tablet van de persoon": "This is the person's tablet",
    "Nog {tijd} geldig": "Valid for {tijd} more",
    "Nieuwe code": "New code",
    "Code maken": "Create code",
    "Code maken lukte niet.": "The code could not be created.",
    "Ik doe het zelf": "I do it myself",
    "Je gebruikt LifeAngle voor jezelf. Familie kan mee plannen, maar kijkt niet mee.": "You use LifeAngle for yourself. Family can help plan, but does not look in.",
    "Familie ziet de agenda. Niet je medicatie, logboek, notities of locatie. Geen meldingen.": "Family sees the calendar. Not your medication, log, notes or location. No alerts.",
    "We doen het samen": "We do it together",
    "Familie helpt mee met plannen en invullen, en kan zien hoe je dag verloopt.": "Family helps plan and fill things in, and can see how your day is going.",
    "Familie ziet de agenda, medicatie en het logboek. Nog steeds geen meldingen.": "Family sees the calendar, medication and the log. Still no alerts.",
    "Help me meer": "Help me more",
    "Familie krijgt een seintje als er iets afwijkt, zoals vergeten medicatie.": "Family gets a heads-up when something is different, such as forgotten medication.",
    "Familie ziet alles wat nodig is, en krijgt meldingen bij afwijkingen.": "Family sees everything that is needed, and gets alerts when something is different.",
    "Beheerder": "Administrator",
    "Tablet van de persoon": "Person's tablet",
    "Wat {naam} deelt": "What {naam} shares",
    "Jij beslist hoeveel je familie meekijkt. Minder kan altijd; meer vraagt jouw ja.": "You decide how much your family can see. Less is always possible; more needs your yes.",
    "Als beheerder pas je dit meteen aan. Elke wijziging komt in het zorglogboek, zodat {naam} altijd kan zien wat er veranderde.": "As administrator you change this straight away. Every change goes into the care log, so {naam} can always see what changed.",
    "Je familie stelt voor om meer te helpen": "Your family is suggesting they help more",
    "Voorstel:": "Suggestion:",
    "Ja, dat is goed": "Yes, that's fine",
    "Nee, nog niet": "No, not yet",
    "Hoeveel hulp": "How much help",
    "nu": "now",
    "Aangepast. Het staat in het zorglogboek.": "Changed. It is in the care log.",
    "Alleen de familiebeheerder kan dit wijzigen.": "Only the family administrator can change this.",
    "Dat lukte niet.": "That didn't work.",
    "Wat ik laat onthouden": "What I ask to remember",
    "Familie kan zien wat je via \"Onthoud dit\" noteert, zodra ze meekijken.": "Family can see what you note via \"Remember this\", once they can look in.",
    "Alleen jij ziet wat je via \"Onthoud dit\" noteert.": "Only you see what you note via \"Remember this\".",
    "Notities delen met familie": "Share notes with family",
    "Wie er bij hoort": "Who is part of it",
    "Onbekend": "Unknown",
    "{naam} ook beheerder maken?": "Make {naam} an administrator as well?",
    "Deze persoon": "This person",
    "Maak beheerder": "Make administrator",
    "{naam} geen toegang meer geven?": "Remove {naam}'s access?",
    "Toegang weghalen": "Remove access",
    "Je familie stelt iets voor": "Your family has a suggestion",
    "Ze willen je wat meer helpen. Jij beslist. Tik om te bekijken.": "They would like to help you a bit more. You decide. Tap to have a look.",
    "Noodtoegang": "Emergency access",
    "Een teamverantwoordelijke van het woonzorgcentrum kan in een noodgeval 4 uur meekijken: naam, voorkeuren, agenda, logboek en contactpersonen. Geen dagboek, documenten of locatie.": "In an emergency, a team lead at the care home can look in for 4 hours: name, preferences, calendar, log and contacts. No diary, documents or location.",
    "Loopt nog tot {uur}": "Running until {uur}",
    "Gestopt": "Stopped",
    "Afgelopen": "Ended",
    "gestart {wanneer}": "started {wanneer}",
    "Nog niets ingekeken.": "Nothing viewed yet.",
    "1 keer ingekeken.": "Viewed once.",
    "{n} keer ingekeken.": "Viewed {n} times.",
    "Deze noodtoegang nu stoppen?": "Stop this emergency access now?",
    "Nu stoppen": "Stop now",
    "Stoppen lukte niet.": "Stopping did not work.",
    "Wie bekeek wat": "Who viewed what",
    "De laatste 30 dagen: wie een document opende, een opname beluisterde of de locatie bekeek. Wat {naam} zelf bekijkt, staat hier niet. Alleen beheerders zien dit.": "The last 30 days: who opened a document, listened to a recording or viewed the location. What {naam} views themselves is not shown here. Only administrators see this.",
    "Bezig met laden…": "Loading…",
    "Dit overzicht kon niet geladen worden.": "This overview could not be loaded.",
    "Niemand bekeek de laatste 30 dagen documenten, opnames of de locatie.": "Nobody viewed documents, recordings or the location in the last 30 days.",
    "Woonzorgcentrum": "Care home",
    "Afdeling {naam}": "Unit {naam}",
    "kamer {nr}": "room {nr}",
    "Afdeling en kamer zijn nog niet ingevuld.": "Unit and room have not been filled in yet.",
    "Alleen de medewerkers die {naam} volgen, zien de agenda en de contactpersonen en schrijven zorgnotities. Wat zij voor de familie bedoelen, staat hieronder. De directie of beheerder van het woonzorgcentrum ziet geen persoonlijke gegevens. Dagboek, documenten en locatie blijven bij de familie.": "Only the staff who look after {naam} see the calendar and contacts and write care notes. What they mean for the family is shown below. The care home's management or administrator sees no personal data. Diary, documents and location stay with the family.",
    "Wie volgt {naam}": "Who looks after {naam}",
    "team lead van de afdeling": "team lead of the unit",
    "toegewezen": "assigned",
    "Van het zorgteam": "From the care team",
    "De koppeling met {naam} stoppen? De medewerkers verliezen meteen hun toegang.": "Stop the link with {naam}? The staff lose their access immediately.",
    "Koppeling stoppen": "Stop the link",
    "Gaat {naam} in een woonzorgcentrum wonen dat LifeAngle gebruikt? Vraag er de koppelcode en vul die hier in. Het team dat {naam} volgt, ziet dan de agenda en de contactpersonen, en schrijft zorgnotities.": "Is {naam} moving into a care home that uses LifeAngle? Ask them for the link code and enter it here. The team looking after {naam} will then see the calendar and contacts, and write care notes.",
    "Koppelcode": "Link code",
    "Koppelen": "Link",
    "Koppelen lukte niet.": "Linking did not work.",
    "Gekoppeld met {naam}.": "Linked with {naam}.",
    "Downloaden lukte niet.": "The download did not work.",
    "Verwijderen lukte niet.": "Deleting did not work.",
    "Wat LifeAngle bewaart, waarom, en hoe lang, staat in de {link}.": "What LifeAngle keeps, why, and for how long is set out in the {link}.",
    "Typ {woord} om te bevestigen": "Type {woord} to confirm",
    "Mijn gegevens": "My data",
    "privacyverklaring": "privacy notice",
    "Bezig met verzamelen…": "Gathering…",
    "Download mijn gegevens": "Download my data",
    "Eén bestand met alles wat jij in de app kan zien. Foto’s, opnames en documenten staan erin als verwijzing.": "One file with everything you can see in the app. Photos, recordings and documents are included as references.",
    "Mijn account verwijderen": "Delete my account",
    "Je account verwijderen": "Delete your account",
    "Je kan niet meer inloggen, en je profiel verdwijnt.": "You will no longer be able to log in, and your profile disappears.",
    "Gaat een huishouden over jou, of ben je er alleen in, dan verdwijnt het mee — met alle foto’s, verhalen en documenten.": "If a household is about you, or you are its only member, it disappears too — with all photos, stories and documents.",
    "Zijn er nog anderen, dan blijft het huishouden bestaan. Wat je schreef, blijft staan zonder je naam.": "If there are others, the household stays. What you wrote remains, without your name.",
    "Dit kan niet ongedaan gemaakt worden. Download eerst je gegevens als je ze wil houden.": "This cannot be undone. Download your data first if you want to keep it.",
    "Ben ik de enige beheerder van een huishouden waar nog anderen in zitten, verwijder dat huishouden dan ook.": "If I am the only administrator of a household that still has other members, delete that household too.",
    "Definitief verwijderen": "Delete permanently",
    "Wat LifeAngle bewaart": "What LifeAngle keeps",
    "Je naam en e-mailadres, om in te loggen.": "Your name and email address, to log in.",
    "Wat jij of je familie invult: de agenda, routines, mensen, dingen in huis, foto’s, verhalen, weetjes en berichten.": "What you or your family fill in: the calendar, routines, people, things in the house, photos, stories, good-to-know notes and messages.",
    "Medicatie en het zorglogboek, als die gebruikt worden. Dat zijn gezondheidsgegevens, en die krijgen extra bescherming.": "Medication and the care log, if they are used. These are health data, and they get extra protection.",
    "Je locatie, alleen als je daar uitdrukkelijk toestemming voor gaf.": "Your location, only if you explicitly gave permission.",
    "Waarom": "Why",
    "Alleen om de app te laten werken: je dag tonen, je helpen onthouden, en je familie laten meehelpen voor zover jij dat toelaat.": "Only to make the app work: showing your day, helping you remember, and letting your family help as far as you allow.",
    "Niet voor reclame. Er worden geen gegevens verkocht of gedeeld met adverteerders.": "Not for advertising. No data is sold or shared with advertisers.",
    "Wie het kan zien": "Who can see it",
    "Alleen de mensen die jij of je familiebeheerder uitnodigde, en alleen wat bij hun rol past.": "Only the people you or your family administrator invited, and only what fits their role.",
    "In de zelfstandige fase ziet familie je medicatie, logboek, notities en locatie niet. Onder \"Wie ziet wat\" zie je altijd wie er meekijkt.": "In the independent phase, family does not see your medication, log, notes or location. Under \"Who sees what\" you can always see who is looking in.",
    "Zorgverleners zien geen documenten.": "Carers do not see documents.",
    "Waar het staat": "Where it is stored",
    "In een database bij Supabase, in een datacenter in de Europese Unie.": "In a database at Supabase, in a data centre in the European Union.",
    "Foto’s en documenten staan in afgeschermde opslag; een link ernaartoe werkt maar even.": "Photos and documents are kept in protected storage; a link to them only works for a short while.",
    "Videogesprekken gaan rechtstreeks van toestel naar toestel, versleuteld. Er wordt geen beeld of geluid bewaard.": "Video calls go directly from device to device, encrypted. No picture or sound is stored.",
    "Hoe lang": "How long",
    "Locatiegegevens: zeven dagen.": "Location data: seven days.",
    "Berichten aan de persoon: verdwijnen van het scherm na twee dagen, en worden daarna gewist.": "Messages to the person: disappear from the screen after two days, and are then deleted.",
    "Al het andere: tot je het zelf verwijdert, of tot je je account verwijdert.": "Everything else: until you delete it yourself, or until you delete your account.",
    "Jouw rechten": "Your rights",
    "Je kan al je gegevens downloaden, onder Instellingen → Mijn gegevens.": "You can download all your data, under Settings → My data.",
    "Je kan je account verwijderen, op dezelfde plek. Wat alleen over jou gaat, verdwijnt mee.": "You can delete your account in the same place. Whatever is only about you disappears with it.",
    "Je kan toestemming voor locatie altijd weer intrekken.": "You can always withdraw permission for location.",
    "Heb je een vraag of een klacht, dan kan je ook terecht bij de Gegevensbeschermingsautoriteit.": "If you have a question or a complaint, you can also contact the Data Protection Authority.",
    "‹ Terug": "‹ Back",
    "Privacy": "Privacy",
    "Wat LifeAngle bewaart, waarom, en wat je ermee kan. In gewone taal.": "What LifeAngle keeps, why, and what you can do about it. In plain language.",
  },
} satisfies Vertaling
