import type { Vertaling } from '../uiTaal'

/** Instellingen, profiel ("Dit ben ik"), indeling, meldingen, locatie, installeren en onboarding. */
export default {
  fr: {
    "Groenblauw": "Bleu-vert",
    "Blauw": "Bleu",
    "Groen": "Vert",
    "Paars": "Violet",
    "Warm bruin": "Brun chaud",
    "Alleen op een telefoon (aanbevolen)": "Uniquement sur un téléphone (recommandé)",
    "Op een telefoon staan de belknoppen en de knop 112. Op een tablet zonder simkaart niet, want daar zouden ze niets doen.": "Sur un téléphone, les boutons d’appel et le bouton 112 sont affichés. Pas sur une tablette sans carte SIM, car ils n’y feraient rien.",
    "Overal, ook op de tablet": "Partout, y compris sur la tablette",
    "Kies dit als de tablet een simkaart heeft. Probeer eerst één keer te bellen vanaf die tablet — lukt dat niet, zet het dan terug.": "Choisissez ceci si la tablette a une carte SIM. Essayez d’abord d’appeler une fois depuis cette tablette — si cela ne fonctionne pas, revenez en arrière.",
    "Nergens": "Nulle part",
    "Geen belknoppen en geen 112. Familie blijft wel bereikbaar: ze vraagt met één knop om terugbellen.": "Pas de boutons d’appel ni de 112. La famille reste joignable : elle demande d’être rappelée d’un seul bouton.",
    "de persoon": "la personne",
    "Instellingen": "Réglages",
    "Deze instellingen gelden voor het scherm van {voornaam}, op elk toestel.": "Ces réglages s’appliquent à l’écran de {voornaam}, sur chaque appareil.",
    "Bellen en 112": "Appels et 112",
    "Een tablet zonder simkaart kan niet telefoneren. Staat hier \"overal\", dan krijgt {voornaam} ook op die tablet een knop \"112\" — en daar drukt iemand op in een echte noodsituatie.": "Une tablette sans carte SIM ne peut pas téléphoner. Si vous choisissez « partout », {voornaam} aura aussi un bouton « 112 » sur cette tablette — et c’est sur ce bouton qu’on appuie en cas de véritable urgence.",
    "Waar mag ze bellen vanuit de app?": "D’où peut-elle appeler depuis l’app ?",
    "Wat moet ze doen bij nood?": "Que doit-elle faire en cas d’urgence ?",
    "Dit staat op het Help-scherm van {voornaam} op elk toestel dat niet kan bellen — de tablet dus. Wees heel concreet: waar de telefoon ligt, bij wie er aangebeld kan worden.": "Ceci s’affiche sur l’écran Aide de {voornaam} sur chaque appareil qui ne peut pas appeler — donc la tablette. Soyez très concret : où se trouve le téléphone, chez qui sonner.",
    "Dit staat op het Help-scherm van {voornaam} in plaats van de 112-knop. Wees heel concreet: waar de telefoon ligt, bij wie er aangebeld kan worden.": "Ceci s’affiche sur l’écran Aide de {voornaam} à la place du bouton 112. Soyez très concret : où se trouve le téléphone, chez qui sonner.",
    "Bel 112 met de telefoon in de gang, naast de voordeur. Of bel aan bij de buren op nummer 14.": "Appelez le 112 avec le téléphone du couloir, à côté de la porte d’entrée. Ou sonnez chez les voisins au numéro 14.",
    "Leesbaarheid": "Lisibilité",
    "Eenvoudige modus": "Mode simple",
    "Grotere tekst en knoppen, minder op één scherm.": "Texte et boutons plus grands, moins de choses par écran.",
    "Tekstgrootte": "Taille du texte",
    "Schaalt de hele app mee.": "Toute l’app s’adapte.",
    "Contrast": "Contraste",
    "Hoog contrast voor wie slecht ziet.": "Contraste élevé pour les personnes qui voient mal.",
    "Normaal": "Normal",
    "Hoog": "Élevé",
    "Thema": "Thème",
    "Volgt standaard het toestel.": "Suit l’appareil par défaut.",
    "Auto": "Auto",
    "Licht": "Clair",
    "Donker": "Sombre",
    "Accentkleur": "Couleur d’accent",
    "De kleur van knoppen, randen en wat de aandacht vraagt.": "La couleur des boutons, des bordures et de ce qui demande l’attention.",
    "Licht bij een melding": "Lumière lors d’une notification",
    "De randen van het scherm lichten zacht op bij een bericht, een oproep of een herinnering.": "Les bords de l’écran s’illuminent doucement lors d’un message, d’un appel ou d’un rappel.",
    "Probeer": "Essayer",
    "Scherm altijd aan": "Écran toujours allumé",
    "Voor een tablet die in de lader staat. Op een telefoon kost dit batterij.": "Pour une tablette posée sur son chargeur. Sur un téléphone, cela consomme de la batterie.",
    "Voorlezen": "Lecture à voix haute",
    "Berichten en verhalen worden hardop voorgelezen.": "Les messages et les récits sont lus à voix haute.",
    "Met de grote microfoonknop zegt {voornaam} gewoon wat nodig is: een afspraak, een herinnering, boodschappen, of iets vertellen voor het dagboek. Belangrijke dingen worden eerst bevestigd.": "Avec le grand bouton micro, {voornaam} dit simplement ce qu’il faut : un rendez-vous, un rappel, des courses, ou quelque chose à raconter pour le journal. Les choses importantes sont d’abord confirmées.",
    "Naam van de assistent": "Nom de l’assistant",
    "Een naam die makkelijk uit te spreken is, bijvoorbeeld Anna of Sam. Leeg laten mag.": "Un nom facile à prononcer, par exemple Anna ou Sam. Vous pouvez le laisser vide.",
    "Luisteren naar “Hallo {naam}”": "Écouter « Bonjour {naam} »",
    "Luisteren naar “Hallo …”": "Écouter « Bonjour … »",
    "Dan hoeft niemand op de knop te tikken. Werkt alleen zolang de app open staat, en alleen in Chrome en Edge. Het geluid gaat dan voortdurend naar de spraakdienst van de browser — zet dit alleen aan als dat voor jullie in orde is.": "Plus besoin d’appuyer sur le bouton. Ne fonctionne que tant que l’app est ouverte, et uniquement dans Chrome et Edge. Le son est alors envoyé en continu au service vocal du navigateur — n’activez ceci que si cela vous convient.",
    "Luisteren naar de naam": "Écouter le nom",
    "Taal": "Langue",
    "Taal van de app": "Langue de l’app",
    "Geldt voor de schermen, de datums en de stem: voorlezen én verstaan.": "S’applique aux écrans, aux dates et à la voix : lecture à voix haute et compréhension.",
    "Bellen": "Appels",
    "Zelf opnemen na": "Décrocher automatiquement après",
    "Hoe lang de tablet rinkelt voor ze het gesprek zelf aanneemt. Tijdens het rinkelen kan {voornaam} altijd zelf opnemen of weigeren. Geldt alleen in de fase \"ondersteund\".": "Combien de temps la tablette sonne avant de décrocher elle-même. Pendant la sonnerie, {voornaam} peut toujours décrocher ou refuser. Uniquement dans la phase « soutenu ».",
    "{n} sec": "{n} s",
    "Nooit": "Jamais",
    "De vaste tablet": "La tablette fixe",
    "Geldt alleen op de tablet die met een code gekoppeld is, niet op jouw toestel.": "S’applique uniquement à la tablette associée avec un code, pas à votre appareil.",
    "Kioskmodus": "Mode kiosque",
    "Het scherm blijft aan, keert vanzelf terug naar Vandaag en toont 's nachts een rustige klok.": "L’écran reste allumé, revient de lui-même à Aujourd’hui et affiche une horloge apaisante la nuit.",
    "Terug naar Vandaag": "Retour à Aujourd’hui",
    "Na zoveel minuten zonder aanraking. Een gesprek of opname wordt nooit onderbroken.": "Après ce nombre de minutes sans contact. Un appel ou un enregistrement n’est jamais interrompu.",
    "{n} min": "{n} min",
    "Nachtscherm": "Écran de nuit",
    "Een gedimde klok met dag en dagdeel. Eén tik toont even het gewone scherm.": "Une horloge tamisée avec le jour et le moment de la journée. Un toucher affiche brièvement l’écran normal.",
    "Nachtscherm vanaf": "Écran de nuit à partir de",
    "tot": "à",
    "Nachtscherm tot": "Écran de nuit jusqu’à",
    "Zodat {voornaam} de app niet per ongeluk sluit, zet je hem ook op het toestel zelf vast.": "Pour que {voornaam} ne ferme pas l’app par erreur, verrouillez-la aussi sur l’appareil lui-même.",
    "Zo doe je dat": "Voici comment faire",
    "Zo ziet het eruit": "Voici à quoi cela ressemble",
    "Ontbijten": "Petit-déjeuner",
    "Neem rustig de tijd.": "Prenez votre temps.",
    "De instellingen zijn meteen actief, ook op dit scherm.": "Les réglages s’appliquent immédiatement, aussi sur cet écran.",
    "Op het beginscherm zetten": "Ajouter à l’écran d’accueil",
    "Op de tablet van {voornaam} hoort LifeAngle als app te staan, niet als tabblad in een browser.": "Sur la tablette de {voornaam}, LifeAngle doit être installée comme app, pas ouverte dans un onglet du navigateur.",
    "Uitleg per toestel": "Explications par appareil",
    "Meldingen": "Notifications",
    "Een bericht op je gsm wanneer er iets afwijkt, bijvoorbeeld medicatie die om tien uur nog niet bevestigd is. Kan deze browser dat niet, dan gaan de dringende berichten per e-mail — dat staat hieronder.": "Un message sur votre GSM quand quelque chose sort de l’ordinaire, par exemple un médicament toujours pas confirmé à dix heures. Si ce navigateur ne le permet pas, les messages urgents partent par e-mail — voir ci-dessous.",
    "Deze browser kan geen meldingen tonen. Op iPhone en iPad lukt het alleen als LifeAngle op het beginscherm staat: deel-icoon, dan \"Zet op beginscherm\", en open LifeAngle daarna via dat icoon. Lukt dat niet, dan blijft de e-mail hieronder.": "Ce navigateur ne peut pas afficher de notifications. Sur iPhone et iPad, cela ne fonctionne que si LifeAngle est sur l’écran d’accueil : icône de partage, puis « Sur l’écran d’accueil », puis ouvrez LifeAngle via cette icône. Sinon, l’e-mail ci-dessous reste disponible.",
    "De browser houdt meldingen tegen. Zet ze weer aan bij de instellingen van de site. Tot dan blijft de e-mail hieronder.": "Le navigateur bloque les notifications. Réactivez-les dans les paramètres du site. En attendant, l’e-mail ci-dessous reste actif.",
    "Geldt alleen voor dit toestel. Zet het ook aan op je andere toestellen.": "S’applique uniquement à cet appareil. Activez-le aussi sur vos autres appareils.",
    "Niet mogelijk": "Impossible",
    "Meldingen op dit toestel": "Notifications sur cet appareil",
    "Er worden nu nog geen meldingen verstuurd: die horen bij de fase “ondersteund”. {voornaam} beslist daarover bij Wie ziet wat.": "Aucune notification n’est encore envoyée : elles font partie de la phase « soutenu ». {voornaam} en décide dans Qui voit quoi.",
    "Jouw naam": "Votre nom",
    "Zo staat het bij een bericht of een foto die je stuurt. Zet wat zij zou zeggen — \"Els\" of \"mama\" — en niet je volledige naam.": "C’est ainsi que cela apparaît sur un message ou une photo que vous envoyez. Indiquez ce qu’elle dirait — « Els » ou « maman » — et pas votre nom complet.",
    "Naam": "Nom",
    "Opslaan…": "Enregistrement…",
    "Opslaan": "Enregistrer",
    "Er staat nu je e-mailadres. De app toont voorlopig \"{naam}\".": "C’est actuellement votre adresse e-mail. L’app affiche pour l’instant « {naam} ».",
    "Opgeslagen. Het geldt vanaf je volgende bericht.": "Enregistré. Cela s’applique à partir de votre prochain message.",
    "Dat lukte niet. Probeer het straks nog eens.": "Cela n’a pas fonctionné. Réessayez un peu plus tard.",
    "Opslag op dit toestel": "Stockage sur cet appareil",
    "Foto's en ingesproken berichten blijven bewaard, zodat ze ook zonder wifi te zien zijn. Dat loopt op. Opruimen kan altijd: alles komt daarna gewoon opnieuw van de server, alleen duurt de eerste keer kijken dan weer even.": "Les photos et les messages vocaux sont conservés, pour rester visibles même sans wifi. Cela s’accumule. Vous pouvez toujours faire le ménage : tout revient ensuite simplement du serveur, seule la première consultation prend un peu plus de temps.",
    "Bezig…": "En cours…",
    "Bewaarde foto’s opruimen": "Supprimer les photos conservées",
    "Opgeruimd.": "C’est fait.",
    "Gebruik hiervoor niet de knop van de browser zelf (\"Gegevens verwijderen en rechten resetten\"). Die wist ook de aanmelding, en op de tablet de koppeling met dit huishouden.": "N’utilisez pas pour cela le bouton du navigateur lui-même (« Effacer les données et réinitialiser les autorisations »). Il efface aussi la connexion et, sur la tablette, l’association avec ce foyer.",
    "Dat lukte niet.": "Cela n’a pas fonctionné.",
    "Woont samen": "Vit avec quelqu’un",
    "Woont {voornaam} in hetzelfde huis als iemand anders voor wie je zorgt? Dan is er één keuken, en hoef je de wasmachine maar één keer uit te leggen.": "{voornaam} vit dans la même maison qu’une autre personne dont vous prenez soin ? Alors il n’y a qu’une cuisine, et vous n’expliquez la machine à laver qu’une seule fois.",
    "Gedeeld wordt alleen het huis: kamers, apparaten, waar dingen liggen en hoe ze werken. Niet de familie, de herinneringen, de medicatie, de agenda of het zorglogboek — die blijven per persoon.": "Seule la maison est partagée : les pièces, les appareils, où se trouvent les choses et comment elles fonctionnent. Pas la famille, les souvenirs, les médicaments, l’agenda ou le journal de soins — ceux-ci restent propres à chaque personne.",
    "{voornaam} woont in huis bij {bij}.": "{voornaam} vit dans la maison de {bij}.",
    "iemand anders": "quelqu’un d’autre",
    "Home Memory is voor beiden hetzelfde. Wat je aan de keuken wijzigt, zien ze allebei.": "Home Memory est le même pour les deux. Ce que vous modifiez dans la cuisine, ils le voient tous les deux.",
    "Als je losmaakt, blijven de kamers en apparaten bij {bij} staan. {voornaam} begint dan met een leeg Home Memory.": "Si vous séparez, les pièces et les appareils restent chez {bij}. {voornaam} recommence alors avec un Home Memory vide.",
    "het andere huishouden": "l’autre foyer",
    "Toch losmaken": "Séparer quand même",
    "Laat maar": "Laisser tel quel",
    "Losmaken": "Séparer",
    "Je beheert nog geen tweede huishouden dat op zichzelf woont. Zodra dat er is, kan je het hier samenvoegen.": "Vous ne gérez pas encore un deuxième foyer qui vit seul. Dès qu’il y en a un, vous pourrez les réunir ici.",
    "Zelfde huis": "Même maison",
    "‹ Terug": "‹ Retour",
    "Afdrukken of opslaan als PDF": "Imprimer ou enregistrer en PDF",
    "Dit ben ik": "Voici qui je suis",
    "Noem me": "Appelez-moi",
    "Wat je moet weten om mij te helpen": "Ce qu’il faut savoir pour m’aider",
    "Zo praat je best met mij": "Comment me parler au mieux",
    "Als ik onrustig ben, helpt dit": "Quand je suis agité(e), ceci m’aide",
    "Hier raak ik van overstuur": "Ceci me bouleverse",
    "Waar ik vandaan kom": "D’où je viens",
    "Wie bij mij hoort": "Mes proches",
    "Nog niemand ingevuld.": "Personne n’a encore été ajouté.",
    "Mijn huisarts en andere contacten": "Mon médecin traitant et autres contacts",
    "Hoe mijn dag er thuis uitziet": "À quoi ressemble ma journée à la maison",
    "Niet om na te volgen, wel om te weten wat ik gewend ben.": "Pas pour le suivre à la lettre, mais pour savoir ce dont j’ai l’habitude.",
    "Wat ik graag heb": "Ce que j’aime",
    "Wanneer ik thuis medicatie krijg": "Quand je reçois mes médicaments à la maison",
    "Dit is geen medicatielijst.": "Ceci n’est pas une liste de médicaments.",
    "Het zegt alleen op welke momenten ik thuis iets kreeg. Vraag het schema met doseringen aan mijn huisarts of apotheek.": "Elle indique seulement à quels moments je recevais quelque chose à la maison. Demandez le schéma avec les doses à mon médecin traitant ou à ma pharmacie.",
    "Nog dit": "Encore ceci",
    "Samengesteld door mijn familie op {datum}, via de app LifeAngle. Geen medisch dossier.": "Rédigé par ma famille le {datum}, via l’app LifeAngle. Ce n’est pas un dossier médical.",
    "— niet ingevuld —": "— non renseigné —",
    "Hoe wil ze aangesproken worden?": "Comment souhaite-t-elle qu’on l’appelle ?",
    "Niet iedereen heet voor iedereen hetzelfde.": "On ne porte pas le même nom pour tout le monde.",
    "Zo praat je best met deze persoon": "Comment parler au mieux à cette personne",
    "Wat jij vanzelf doet, weet een verpleegkundige op dag één niet.": "Ce que vous faites naturellement, une infirmière ne le sait pas le premier jour.",
    "Traag praten, één vraag tegelijk. Ga links staan, daar hoort ze beter.": "Parler lentement, une question à la fois. Placez-vous à sa gauche, elle y entend mieux.",
    "Als ze onrustig is, helpt dit": "Quand elle est agitée, ceci aide",
    "Het belangrijkste veld van het hele blad.": "Le champ le plus important de toute la fiche.",
    "Muziek van vroeger opzetten. Even mee naar buiten. Niet tegenspreken.": "Mettre de la musique d’autrefois. Sortir un moment avec elle. Ne pas la contredire.",
    "Hier raakt ze van overstuur": "Ceci la bouleverse",
    "Even belangrijk, en vaak moeilijker op te schrijven.": "Tout aussi important, et souvent plus difficile à écrire.",
    "Veel mensen tegelijk. Als iemand zegt dat ze zich vergist.": "Beaucoup de monde à la fois. Quand quelqu’un lui dit qu’elle se trompe.",
    "Nog iets dat ze moeten weten": "Autre chose à savoir",
    "Wat hier niet in de vakjes past.": "Ce qui ne rentre pas dans les cases.",
    "Slaapt met het licht aan. De bril ligt altijd links naast het bed.": "Dort avec la lumière allumée. Les lunettes sont toujours à gauche du lit.",
    "Eén blad dat meegaat naar het ziekenhuis of het woonzorgcentrum. Daar is {voornaam} op dag één een naam op een lijst; dit maakt er een mens van. De rest — familie, voorkeuren, de dagindeling — haalt het blad uit wat hier al staat.": "Une seule fiche qui accompagne {voornaam} à l’hôpital ou en maison de repos. Là-bas, le premier jour, {voornaam} n’est qu’un nom sur une liste ; cette fiche en fait une personne. Le reste — la famille, les préférences, le déroulement de la journée — la fiche le reprend de ce qui est déjà ici.",
    "Bekijken en afdrukken": "Voir et imprimer",
    "Bezig met opslaan…": "Enregistrement en cours…",
    "Niet opgeslagen — probeer opnieuw.": "Non enregistré — réessayez.",
    "{n} van {totaal} ingevuld. Het slaat vanzelf op.": "{n} sur {totaal} renseignés. L’enregistrement est automatique.",
    "Indeling": "Disposition",
    "Wat er op het dagscherm van {voornaam} staat, in welke volgorde en hoe groot. Het verandert meteen op de tablet; je hoeft die niet aan te raken.": "Ce qui figure sur l’écran du jour de {voornaam}, dans quel ordre et en quelle taille. Cela change immédiatement sur la tablette ; inutile d’y toucher.",
    "Niet opgeslagen — probeer opnieuw": "Non enregistré — réessayez",
    "Opgeslagen": "Enregistré",
    "Nog niet klaar om te bewaren.": "Pas encore prêt à enregistrer.",
    "De database kent de indeling nog niet. Draai {bestand} in de SQL-editor van Supabase; tot dan toont het scherm van {voornaam} de standaardindeling en blijven wijzigingen hier niet staan.": "La base de données ne connaît pas encore la disposition. Exécutez {bestand} dans l’éditeur SQL de Supabase ; d’ici là, l’écran de {voornaam} affiche la disposition par défaut et les modifications faites ici ne sont pas conservées.",
    "Beginnen vanaf een sjabloon": "Partir d’un modèle",
    "Dit vervangt de hele indeling. Daarna kan je nog alles aanpassen.": "Ceci remplace toute la disposition. Vous pourrez ensuite encore tout adapter.",
    "In gebruik": "Utilisé",
    "{n} blokken": "{n} blocs",
    "Zo ziet het scherm van {voornaam} eruit": "Voici à quoi ressemble l’écran de {voornaam}",
    "Tik een tegel om hem aan te passen.": "Touchez une tuile pour la modifier.",
    "Het echte scherm bekijken": "Voir l’écran réel",
    "Bezig met laden…": "Chargement…",
    "vast": "fixe",
    "vol": "pleine",
    "half": "demi",
    "{n} tegel. De leesvolgorde is van boven naar beneden — precies wat de voorleesfunctie aanhoudt.": "{n} tuile. L’ordre de lecture va de haut en bas — exactement celui que suit la lecture à voix haute.",
    "{n} tegels. De leesvolgorde is van boven naar beneden — precies wat de voorleesfunctie aanhoudt.": "{n} tuiles. L’ordre de lecture va de haut en bas — exactement celui que suit la lecture à voix haute.",
    "Dit zijn er meer dan {n}. Dat kan, maar elke tegel erbij is één keuze meer die {voornaam} tegelijk ziet. Kijk gerust of er eentje bij kan die je niet mist.": "Il y en a plus de {n}. C’est possible, mais chaque tuile en plus est un choix de plus que {voornaam} voit en même temps. Regardez s’il y en a une dont vous pourriez vous passer.",
    "Gekozen tegel": "Tuile sélectionnée",
    "Grootte": "Taille",
    "Vol": "Pleine",
    "Half": "Demi",
    "Deze tegel is altijd vol-breed; half wordt hier onleesbaar.": "Cette tuile occupe toujours toute la largeur ; en demi, elle deviendrait illisible.",
    "Halve tegels kunnen niet zolang de tekst op groot staat — dan blijven er drie woorden per regel over.": "Les demi-tuiles ne sont pas possibles tant que le texte est en grand — il ne resterait que trois mots par ligne.",
    "Volgorde": "Ordre",
    "Omhoog": "Monter",
    "Omlaag": "Descendre",
    "\"Wat nu?\" staat altijd bovenaan en kan niet weg. Dat is de vraag waar de app om draait; die hoort niet per huishouden ergens anders te staan. Half mag wel: op een tablet staat de kaart dan bovenaan de linkerkolom.": "« Et maintenant ? » est toujours en haut et ne peut pas être retiré. C’est la question autour de laquelle tourne l’app ; elle ne doit pas se trouver ailleurs selon le foyer. En demi, c’est possible : sur une tablette, la carte se place alors en haut de la colonne de gauche.",
    "Van het scherm halen": "Retirer de l’écran",
    "Tik hierboven een tegel om hem groter te maken, te verplaatsen of weg te halen.": "Touchez une tuile ci-dessus pour l’agrandir, la déplacer ou la retirer.",
    "Toevoegen": "Ajouter",
    "Alles staat er al op.": "Tout y figure déjà.",
    "Wat nu?": "Et maintenant ?",
    "Wat er op dit moment moet gebeuren, met een knop om het af te vinken.": "Ce qu’il faut faire maintenant, avec un bouton pour le cocher.",
    "Daarna": "Ensuite",
    "Het eerstvolgende dat eraan komt.": "La prochaine chose à venir.",
    "Vandaag": "Aujourd’hui",
    "De hele dag als tijdlijn, met wat al gedaan is.": "Toute la journée sous forme de ligne du temps, avec ce qui est déjà fait.",
    "Berichten": "Messages",
    "Wat familie stuurde, met de mogelijkheid te antwoorden.": "Ce que la famille a envoyé, avec la possibilité de répondre.",
    "Medicatie": "Médicaments",
    "Het eerstvolgende moment met de foto van de doos, en een knop om te bevestigen.": "Le prochain moment avec la photo de la boîte, et un bouton pour confirmer.",
    "Onthoud dit": "Retiens ceci",
    "Iets laten onthouden: waar iets ligt, wat er gezegd is.": "Faire retenir quelque chose : où se trouve un objet, ce qui a été dit.",
    "Muziek": "Musique",
    "De radio of de muziek van vroeger, met één knop aan.": "La radio ou la musique d’autrefois, allumée d’un seul bouton.",
    "Vandaag vroeger": "Ce jour-là, autrefois",
    "Een foto van deze dag in een ander jaar. Blijft weg op dagen waar niets bij past.": "Une photo de ce jour une autre année. N’apparaît pas les jours où rien ne correspond.",
    "Herinneringen": "Souvenirs",
    "De nieuwste foto, met een weg naar de hele tijdlijn. Staat er elke dag.": "La photo la plus récente, avec un accès à toute la ligne du temps. Présente chaque jour.",
    "Weetjes": "Bon à savoir",
    "Antwoorden op vragen die terugkomen: waar iets ligt, hoe iets moet.": "Des réponses aux questions qui reviennent : où se trouve quelque chose, comment faire quelque chose.",
    "Vertel eens": "Raconte-moi",
    "Elke dag één vraag over vroeger, voor het levensboek.": "Chaque jour une question sur autrefois, pour le livre de vie.",
    "Grote knoppen": "Grands boutons",
    "Wat nu?, Familie en Help als drie grote knoppen.": "Et maintenant ?, Famille et Aide sous forme de trois grands boutons.",
    "Rustig": "Calme",
    "Drie blokken. Eén ding tegelijk, elke dag op dezelfde plek.": "Trois blocs. Une chose à la fois, chaque jour au même endroit.",
    "Standaard": "Standard",
    "De dag en wat familie stuurt, met de grote kaart bovenaan.": "La journée et ce que la famille envoie, avec la grande carte en haut.",
    "Twee kolommen": "Deux colonnes",
    "Zoals het scherm er vroeger liggend uitzag: links de dag, rechts wat er te doen en te zien is. Op een tablet loopt alles door in twee kolommen.": "Comme l’écran en mode paysage d’avant : à gauche la journée, à droite ce qu’il y a à faire et à voir. Sur une tablette, tout se suit en deux colonnes.",
    "Alles": "Tout",
    "Elke module, om te zien wat er bestaat. Daarna weghalen wat niet past.": "Chaque module, pour voir ce qui existe. Retirez ensuite ce qui ne convient pas.",
    "Je telefoonnummer. Komt op je vergrendelscherm, ook met de app dicht.": "Votre numéro de téléphone. Apparaît sur votre écran de verrouillage, même avec l’app fermée.",
    "Stuur de bot eerst \"start\" in Telegram, en zoek dan hieronder je chat-id op.": "Envoyez d’abord « start » au bot dans Telegram, puis recherchez votre chat-id ci-dessous.",
    "Weghalen": "Retirer",
    "Bewaren": "Enregistrer",
    "Zoeken…": "Recherche…",
    "Zoek mijn chat-id": "Trouver mon chat-id",
    "Niemand gevonden. Stuur de bot eerst \"start\" in Telegram en probeer het opnieuw — of TG_BOT_TOKEN ontbreekt nog bij de secrets in Supabase.": "Personne trouvé. Envoyez d’abord « start » au bot dans Telegram et réessayez — ou TG_BOT_TOKEN manque encore dans les secrets de Supabase.",
    "Dat lukte niet. Draait push-notify al met de nieuwe code?": "Cela n’a pas fonctionné. push-notify tourne-t-il déjà avec le nouveau code ?",
    "Bewaard.": "Enregistré.",
    "Weggehaald.": "Retiré.",
    "E-mail": "E-mail",
    "e-mail": "e-mail",
    "een melding op dit toestel": "une notification sur cet appareil",
    "Je hebt geen enkele weg aan staan buiten de app zelf. Zet e-mail aan, of vul hieronder een WhatsApp-nummer in — anders zie je een dringend bericht alleen wanneer LifeAngle open staat.": "Aucun canal n’est activé en dehors de l’app elle-même. Activez l’e-mail ou indiquez un numéro WhatsApp ci-dessous — sinon vous ne verrez un message urgent que lorsque LifeAngle est ouverte.",
    "Dit toestel krijgt geen pushmeldingen. Toestemming geldt per toestel én per account: aanzetten op de tablet doet niets voor je telefoon. Op iPhone en iPad kan het alleen wanneer de app op het beginscherm staat.": "Cet appareil ne reçoit pas de notifications push. L’autorisation vaut par appareil et par compte : l’activer sur la tablette ne fait rien pour votre téléphone. Sur iPhone et iPad, ce n’est possible que si l’app est sur l’écran d’accueil.",
    "Pushmeldingen worden alleen verstuurd wanneer de ondersteuning op \"ondersteund\" staat. Dat kan je aanpassen bij Wie ziet wat. De e-mail bij dringende berichten gaat wel door.": "Les notifications push ne sont envoyées que lorsque l’accompagnement est réglé sur « soutenu ». Vous pouvez le modifier dans Qui voit quoi. L’e-mail pour les messages urgents part quand même.",
    "Er wacht 1 melding die niet verstuurd raakt. Druk op \"Stuur een testmelding\" hieronder: dan zegt de app welke weg het laat afweten, in plaats van dat je moet raden.": "1 notification attend sans pouvoir être envoyée. Appuyez sur « Envoyer une notification test » ci-dessous : l’app vous dira quel canal fait défaut, au lieu de devoir deviner.",
    "Er wachten {n} meldingen die niet verstuurd raken. Druk op \"Stuur een testmelding\" hieronder: dan zegt de app welke weg het laat afweten, in plaats van dat je moet raden.": "{n} notifications attendent sans pouvoir être envoyées. Appuyez sur « Envoyer une notification test » ci-dessous : l’app vous dira quel canal fait défaut, au lieu de devoir deviner.",
    "Je krijgt dringende berichten alleen in de app": "Vous ne recevez les messages urgents que dans l’app",
    "Dringende berichten komen bij jou aan via {wegen}": "Les messages urgents vous parviennent par {wegen}",
    "en": "et",
    "Ook per e-mail, bij dringende berichten": "Aussi par e-mail, pour les messages urgents",
    "Alleen wanneer ze vraagt of je belt, of om hulp vraagt. E-mail werkt op elk toestel, zonder toestemming — dit is de weg die het altijd haalt.": "Uniquement quand elle demande que vous l’appeliez, ou demande de l’aide. L’e-mail fonctionne sur tous les appareils, sans autorisation — c’est le canal qui passe toujours.",
    "Dringende meldingen ook per e-mail": "Notifications urgentes aussi par e-mail",
    "Alles staat klaar.": "Tout est prêt.",
    "Stuur een testmelding": "Envoyer une notification test",
    "Verstuurd, langs elke weg die aan staat. Komt er binnen een minuut niets aan, dan staat hierboven waarschijnlijk al waarom.": "Envoyé, par chaque canal activé. Si rien n’arrive dans la minute, la raison figure probablement déjà ci-dessus.",
    "Deze weg staat uit bij de server:": "Ce canal est désactivé sur le serveur :",
    "Deze wegen staan uit bij de server:": "Ces canaux sont désactivés sur le serveur :",
    "{sleutels} ontbreekt nog bij Edge Functions → Secrets in Supabase.": "{sleutels} manque encore dans Edge Functions → Secrets de Supabase.",
    "de secrets": "les secrets",
    "Een weg weigerde het bericht:": "Un canal a refusé le message :",
    "Dat lukte niet. Draaide {bestand} al?": "Cela n’a pas fonctionné. {bestand} a-t-il déjà été exécuté ?",
    "push-notify is niet bereikbaar. Kijk in Supabase bij Edge Functions of het adres onder de titel eindigt op /push-notify — staat daar iets anders, dan roept de app een functie aan die niet bestaat.": "push-notify n’est pas joignable. Vérifiez dans Supabase, sous Edge Functions, que l’adresse sous le titre se termine par /push-notify — si ce n’est pas le cas, l’app appelle une fonction qui n’existe pas.",
    "Dit toestel kan geen locatie bepalen.": "Cet appareil ne peut pas déterminer de position.",
    "Toestemming voor locatie geweigerd in de browser.": "Autorisation de localisation refusée dans le navigateur.",
    "Locatie": "Localisation",
    "Staat uit tot iemand er toestemming voor geeft. {voornaam} ziet altijd wanneer het aan staat, en kan het zelf uitzetten.": "Désactivée jusqu’à ce que quelqu’un donne son autorisation. {voornaam} voit toujours quand elle est activée, et peut la désactiver de son côté.",
    "Aan": "Activée",
    "Uit": "Désactivée",
    "Uitzetten": "Désactiver",
    "Aanzetten, met dit huis als veilige zone": "Activer, avec cette maison comme zone sûre",
    "Veilige zone: {m} meter rond het huis. Familie krijgt één melding wanneer die zone verlaten wordt, niet bij elk punt erbuiten.": "Zone sûre : {m} mètres autour de la maison. La famille reçoit une seule notification quand cette zone est quittée, pas à chaque point en dehors.",
    "Laatst gemeten {wanneer} — buiten de zone": "Dernière mesure {wanneer} — hors de la zone",
    "Laatst gemeten {wanneer} — in de zone": "Dernière mesure {wanneer} — dans la zone",
    "Nog geen positie doorgegeven.": "Aucune position transmise pour l’instant.",
    "Posities worden na zeven dagen gewist. Er wordt niets bijgehouden zolang dit uit staat.": "Les positions sont effacées après sept jours. Rien n’est enregistré tant que ceci est désactivé.",
    "iPad of iPhone": "iPad ou iPhone",
    "Open deze pagina in Safari. In een andere browser lukt het niet.": "Ouvrez cette page dans Safari. Cela ne fonctionne pas dans un autre navigateur.",
    "Druk onderaan (of bovenaan) op het deelicoon: een vierkantje met een pijl omhoog.": "Appuyez en bas (ou en haut) sur l’icône de partage : un petit carré avec une flèche vers le haut.",
    "Scrol in de lijst tot \"Zet op beginscherm\".": "Faites défiler la liste jusqu’à « Sur l’écran d’accueil ».",
    "Druk rechtsboven op \"Voeg toe\".": "Appuyez en haut à droite sur « Ajouter ».",
    "Apple laat geen installatieknop in de app zelf toe. Dit is de enige weg, en je hoeft het maar één keer te doen.": "Apple n’autorise pas de bouton d’installation dans l’app elle-même. C’est le seul moyen, et vous ne devez le faire qu’une fois.",
    "Android-tablet of -telefoon": "Tablette ou téléphone Android",
    "Open deze pagina in Chrome.": "Ouvrez cette page dans Chrome.",
    "Druk op de knop met de drie puntjes, rechtsboven.": "Appuyez sur le bouton à trois points, en haut à droite.",
    "Kies \"App installeren\" of \"Toevoegen aan startscherm\".": "Choisissez « Installer l’application » ou « Ajouter à l’écran d’accueil ».",
    "Bevestig met \"Installeren\".": "Confirmez avec « Installer ».",
    "Windows of Mac": "Windows ou Mac",
    "Open deze pagina in Chrome of Edge.": "Ouvrez cette page dans Chrome ou Edge.",
    "Klik op het installatie-icoon rechts in de adresbalk.": "Cliquez sur l’icône d’installation à droite dans la barre d’adresse.",
    "Klik op \"Installeren\".": "Cliquez sur « Installer ».",
    "LifeAngle op het beginscherm": "LifeAngle sur l’écran d’accueil",
    "Dan opent de app met een eigen icoon, zonder adresbalk, en blijft ze ingelogd. Ze werkt ook door wanneer de wifi even hapert.": "L’app s’ouvre alors avec sa propre icône, sans barre d’adresse, et reste connectée. Elle continue aussi de fonctionner quand le wifi flanche un instant.",
    "Deze app staat al op het beginscherm van dit toestel.": "Cette app est déjà sur l’écran d’accueil de cet appareil.",
    "Nu installeren": "Installer maintenant",
    "De tablet klaarzetten": "Préparer la tablette",
    "Voor het toestel dat bij de persoon blijft staan. Eén keer instellen, daarna hoeft er niemand meer aan.": "Pour l’appareil qui reste chez la personne. À régler une seule fois, ensuite plus personne ne doit y toucher.",
    "Laat de tablet in de lader staan, op een vaste plaats.": "Laissez la tablette sur son chargeur, à un endroit fixe.",
    "Zet het schermslot uit, of gebruik een code die de familie kent.": "Désactivez le verrouillage de l’écran, ou utilisez un code que la famille connaît.",
    "Zet het scherm op \"nooit vergrendelen\" zolang hij aan de lader hangt.": "Réglez l’écran sur « ne jamais verrouiller » tant que la tablette est sur le chargeur.",
    "Zet in LifeAngle bij Instellingen de kioskmodus aan. Dat kan ook van op afstand.": "Activez le mode kiosque dans LifeAngle, sous Réglages. C’est aussi possible à distance.",
    "Geef bij de eerste keer toestemming voor microfoon en camera.": "La première fois, autorisez le micro et la caméra.",
    "Zet het volume hoog genoeg om een inkomende oproep te horen.": "Réglez le volume assez fort pour entendre un appel entrant.",
    "Geluid uitproberen": "Tester le son",
    "Browsers laten geluid pas toe nadat iemand het scherm één keer heeft aangeraakt na het opstarten. Druk hier na het klaarzetten één keer, dan weet je dat de beltoon werkt op dit toestel.": "Les navigateurs n’autorisent le son qu’après un premier toucher de l’écran après le démarrage. Appuyez ici une fois la préparation terminée : vous saurez ainsi que la sonnerie fonctionne sur cet appareil.",
    "Beltoon proberen": "Tester la sonnerie",
    "Hoor je niets, kijk dan of het toestel niet op stil staat en of het volume van de media hoog genoeg is.": "Si vous n’entendez rien, vérifiez que l’appareil n’est pas en mode silencieux et que le volume multimédia est assez élevé.",
    "De app vastzetten": "Verrouiller l’app",
    "Een app kan zichzelf niet vergrendelen; dat doet het toestel. Kies wat bij de tablet past.": "Une app ne peut pas se verrouiller elle-même ; c’est l’appareil qui le fait. Choisissez ce qui convient à la tablette.",
    "Videobellen en de microfoon werken alleen op een beveiligde verbinding. Via het gewone webadres is dat in orde; via een lokaal IP-adres niet.": "Les appels vidéo et le micro ne fonctionnent que sur une connexion sécurisée. Via l’adresse web habituelle, c’est le cas ; via une adresse IP locale, non.",
    "Dit toestel: {platform}.": "Cet appareil : {platform}.",
    "iPad: Begeleide toegang": "iPad : Accès guidé",
    "Ingebouwd en gratis. Uit de app gaan kan alleen nog met een code.": "Intégré et gratuit. On ne peut quitter l’app qu’avec un code.",
    "Instellingen → Toegankelijkheid → Begeleide toegang: zet het aan en kies een code.": "Réglages → Accessibilité → Accès guidé : activez-le et choisissez un code.",
    "Instellingen → Beeldscherm en helderheid → Automatisch vergrendelen: Nooit.": "Réglages → Luminosité et affichage → Verrouillage automatique : Jamais.",
    "Open LifeAngle vanaf het beginscherm en klik drie keer snel op de zij- of thuisknop.": "Ouvrez LifeAngle depuis l’écran d’accueil et appuyez trois fois rapidement sur le bouton latéral ou principal.",
    "Tik op Start. Stoppen doe je weer met drie klikken en de code.": "Touchez Démarrer. Pour arrêter, appuyez à nouveau trois fois et saisissez le code.",
    "Android: app vastzetten": "Android : épingler l’application",
    "Ingebouwd en gratis. Goed genoeg voor de meeste mensen, maar wie weet hoe het werkt, krijgt het ongedaan.": "Intégré et gratuit. Suffisant pour la plupart des gens, mais quelqu’un qui sait comment faire peut l’annuler.",
    "Instellingen → Beveiliging → App vastzetten (soms onder Meer beveiligingsinstellingen): aanzetten, met ontgrendelen bij losmaken.": "Paramètres → Sécurité → Épingler l’application (parfois sous Autres paramètres de sécurité) : activer, avec déverrouillage pour retirer l’épingle.",
    "Open LifeAngle vanaf het beginscherm.": "Ouvrez LifeAngle depuis l’écran d’accueil.",
    "Open het overzicht van recente apps, tik op het pictogram van LifeAngle en kies Vastzetten.": "Ouvrez l’aperçu des applications récentes, touchez l’icône de LifeAngle et choisissez Épingler.",
    "Android: Fully Kiosk Browser": "Android : Fully Kiosk Browser",
    "Een kleine eenmalige licentie per toestel, en de degelijkste keuze voor een tablet die jaren aan de muur hangt. LifeAngle start vanzelf na een stroomonderbreking, en de kioskmodus kan dan ook de echte helderheid regelen.": "Une petite licence unique par appareil, et le choix le plus solide pour une tablette qui reste des années au mur. LifeAngle redémarre de lui-même après une coupure de courant, et le mode kiosque peut alors aussi régler la vraie luminosité.",
    "Installeer Fully Kiosk Browser uit de Play Store.": "Installez Fully Kiosk Browser depuis le Play Store.",
    "Zet het webadres van LifeAngle als Start URL.": "Indiquez l’adresse web de LifeAngle comme Start URL.",
    "Zet bij Advanced Web Settings de JavaScript Interface aan.": "Dans Advanced Web Settings, activez JavaScript Interface.",
    "Zet bij Device Management Keep Screen On en Launch on Boot aan.": "Dans Device Management, activez Keep Screen On et Launch on Boot.",
    "Zet Kiosk Mode aan en kies een code om eruit te gaan.": "Activez Kiosk Mode et choisissez un code pour en sortir.",
    "Koppel de tablet daarna met de code uit Instellingen, net als anders.": "Associez ensuite la tablette avec le code des Réglages, comme d’habitude.",
    "Zet LifeAngle op het beginscherm van dit toestel": "Ajoutez LifeAngle à l’écran d’accueil de cet appareil",
    "Installeren": "Installer",
    "Hoe doe ik dat?": "Comment faire ?",
    "Verbergen": "Masquer",
    "Later": "Plus tard",
    "Er ging iets mis. Probeer het opnieuw.": "Un problème est survenu. Réessayez.",
    "Voor wie is deze app?": "Pour qui est cette app ?",
    "Dat bepaalt wie de app beheert en welk scherm je straks ziet.": "Cela détermine qui gère l’app et quel écran vous verrez ensuite.",
    "Ik gebruik de app zelf": "J’utilise l’app moi-même",
    "Ik zorg voor een familielid": "Je prends soin d’un proche",
    "Hoe heet je?": "Comment vous appelez-vous ?",
    "Over wie gaat het?": "De qui s’agit-il ?",
    "Zo spreekt de app je aan.": "C’est ainsi que l’app s’adressera à vous.",
    "De naam die op het scherm komt te staan.": "Le nom qui apparaîtra à l’écran.",
    "Adres, mag leeg blijven": "Adresse, peut rester vide",
    "Lindestraat 12, Herent": "Rue des Tilleuls 12, Namur",
    "Het adres verschijnt op het hulpscherm, als antwoord op \"waar ben ik?\".": "L’adresse apparaît sur l’écran d’aide, en réponse à « où suis-je ? ».",
    "Wie is er belangrijk?": "Qui compte ?",
    "Drie volstaat om te beginnen. Later kan je er meer toevoegen en uitnodigen.": "Trois suffisent pour commencer. Vous pourrez en ajouter et en inviter d’autres plus tard.",
    "Dochter": "Fille",
    "Telefoon": "Téléphone",
    "Nog iemand": "Quelqu’un d’autre",
    "De dagelijkse routine": "La routine quotidienne",
    "Eén regel per moment, beginnend met het uur. Pas aan wat niet klopt.": "Une ligne par moment, en commençant par l’heure. Corrigez ce qui ne convient pas.",
    "Welke kamers zijn er?": "Quelles pièces y a-t-il ?",
    "Tik weg wat er niet is.": "Touchez pour retirer ce qui n’existe pas.",
    "Eén ding om te onthouden": "Une chose à retenir",
    "Begin met wat het vaakst gezocht wordt of niet meer lukt.": "Commencez par ce qu’on cherche le plus souvent ou ce qui ne réussit plus.",
    "Koffiezetapparaat": "Cafetière",
    "Op het aanrecht, rechts van de gootsteen.": "Sur le plan de travail, à droite de l’évier.",
    "Vul het waterreservoir.\nZet een kopje onder de tuit.\nDruk op de grote knop.": "Remplissez le réservoir d’eau.\nPlacez une tasse sous le bec.\nAppuyez sur le grand bouton.",
    "Terug": "Retour",
    "Klaar": "Terminé",
    "Verder": "Suivant",
    "Ik registreer een woonzorgcentrum": "J’inscris une maison de repos",
    "Deze stap overslaan": "Passer cette étape",
  },
  en: {
    "Groenblauw": "Teal",
    "Blauw": "Blue",
    "Groen": "Green",
    "Paars": "Purple",
    "Warm bruin": "Warm brown",
    "Alleen op een telefoon (aanbevolen)": "Only on a phone (recommended)",
    "Op een telefoon staan de belknoppen en de knop 112. Op een tablet zonder simkaart niet, want daar zouden ze niets doen.": "On a phone, the call buttons and the 112 button are shown. Not on a tablet without a SIM card, because they would do nothing there.",
    "Overal, ook op de tablet": "Everywhere, including the tablet",
    "Kies dit als de tablet een simkaart heeft. Probeer eerst één keer te bellen vanaf die tablet — lukt dat niet, zet het dan terug.": "Choose this if the tablet has a SIM card. Try calling once from that tablet first — if it doesn’t work, switch it back.",
    "Nergens": "Nowhere",
    "Geen belknoppen en geen 112. Familie blijft wel bereikbaar: ze vraagt met één knop om terugbellen.": "No call buttons and no 112. Family can still be reached: she asks for a call back with one button.",
    "de persoon": "the person",
    "Instellingen": "Settings",
    "Deze instellingen gelden voor het scherm van {voornaam}, op elk toestel.": "These settings apply to {voornaam}’s screen, on every device.",
    "Bellen en 112": "Calls and 112",
    "Een tablet zonder simkaart kan niet telefoneren. Staat hier \"overal\", dan krijgt {voornaam} ook op die tablet een knop \"112\" — en daar drukt iemand op in een echte noodsituatie.": "A tablet without a SIM card cannot make phone calls. If this is set to \"everywhere\", {voornaam} also gets a \"112\" button on that tablet — and that is what someone presses in a real emergency.",
    "Waar mag ze bellen vanuit de app?": "Where may she call from in the app?",
    "Wat moet ze doen bij nood?": "What should she do in an emergency?",
    "Dit staat op het Help-scherm van {voornaam} op elk toestel dat niet kan bellen — de tablet dus. Wees heel concreet: waar de telefoon ligt, bij wie er aangebeld kan worden.": "This appears on {voornaam}’s Help screen on every device that cannot call — so the tablet. Be very specific: where the phone is, whose doorbell to ring.",
    "Dit staat op het Help-scherm van {voornaam} in plaats van de 112-knop. Wees heel concreet: waar de telefoon ligt, bij wie er aangebeld kan worden.": "This appears on {voornaam}’s Help screen instead of the 112 button. Be very specific: where the phone is, whose doorbell to ring.",
    "Bel 112 met de telefoon in de gang, naast de voordeur. Of bel aan bij de buren op nummer 14.": "Call 112 with the phone in the hallway, next to the front door. Or ring the neighbours’ bell at number 14.",
    "Leesbaarheid": "Readability",
    "Eenvoudige modus": "Simple mode",
    "Grotere tekst en knoppen, minder op één scherm.": "Larger text and buttons, less on one screen.",
    "Tekstgrootte": "Text size",
    "Schaalt de hele app mee.": "Scales the whole app.",
    "Contrast": "Contrast",
    "Hoog contrast voor wie slecht ziet.": "High contrast for people with poor eyesight.",
    "Normaal": "Normal",
    "Hoog": "High",
    "Thema": "Theme",
    "Volgt standaard het toestel.": "Follows the device by default.",
    "Auto": "Auto",
    "Licht": "Light",
    "Donker": "Dark",
    "Accentkleur": "Accent colour",
    "De kleur van knoppen, randen en wat de aandacht vraagt.": "The colour of buttons, borders and anything that needs attention.",
    "Licht bij een melding": "Light on a notification",
    "De randen van het scherm lichten zacht op bij een bericht, een oproep of een herinnering.": "The edges of the screen glow softly for a message, a call or a reminder.",
    "Probeer": "Try",
    "Scherm altijd aan": "Screen always on",
    "Voor een tablet die in de lader staat. Op een telefoon kost dit batterij.": "For a tablet that sits in its charger. On a phone this uses battery.",
    "Voorlezen": "Read aloud",
    "Berichten en verhalen worden hardop voorgelezen.": "Messages and stories are read aloud.",
    "Met de grote microfoonknop zegt {voornaam} gewoon wat nodig is: een afspraak, een herinnering, boodschappen, of iets vertellen voor het dagboek. Belangrijke dingen worden eerst bevestigd.": "With the big microphone button, {voornaam} simply says what’s needed: an appointment, a reminder, shopping, or something to tell for the diary. Important things are confirmed first.",
    "Naam van de assistent": "Assistant’s name",
    "Een naam die makkelijk uit te spreken is, bijvoorbeeld Anna of Sam. Leeg laten mag.": "A name that is easy to say, for example Anna or Sam. You may leave it empty.",
    "Luisteren naar “Hallo {naam}”": "Listen for “Hello {naam}”",
    "Luisteren naar “Hallo …”": "Listen for “Hello …”",
    "Dan hoeft niemand op de knop te tikken. Werkt alleen zolang de app open staat, en alleen in Chrome en Edge. Het geluid gaat dan voortdurend naar de spraakdienst van de browser — zet dit alleen aan als dat voor jullie in orde is.": "Then nobody needs to tap the button. Only works while the app is open, and only in Chrome and Edge. The sound is then sent continuously to the browser’s speech service — only turn this on if that is fine with you.",
    "Luisteren naar de naam": "Listen for the name",
    "Taal": "Language",
    "Taal van de app": "App language",
    "Geldt voor de schermen, de datums en de stem: voorlezen én verstaan.": "Applies to the screens, the dates and the voice: reading aloud and understanding.",
    "Bellen": "Calls",
    "Zelf opnemen na": "Answer automatically after",
    "Hoe lang de tablet rinkelt voor ze het gesprek zelf aanneemt. Tijdens het rinkelen kan {voornaam} altijd zelf opnemen of weigeren. Geldt alleen in de fase \"ondersteund\".": "How long the tablet rings before it answers the call itself. While it rings, {voornaam} can always answer or decline. Only applies in the \"supported\" phase.",
    "{n} sec": "{n} sec",
    "Nooit": "Never",
    "De vaste tablet": "The fixed tablet",
    "Geldt alleen op de tablet die met een code gekoppeld is, niet op jouw toestel.": "Only applies to the tablet linked with a code, not to your device.",
    "Kioskmodus": "Kiosk mode",
    "Het scherm blijft aan, keert vanzelf terug naar Vandaag en toont 's nachts een rustige klok.": "The screen stays on, returns to Today by itself and shows a calm clock at night.",
    "Terug naar Vandaag": "Back to Today",
    "Na zoveel minuten zonder aanraking. Een gesprek of opname wordt nooit onderbroken.": "After this many minutes without a touch. A call or recording is never interrupted.",
    "{n} min": "{n} min",
    "Nachtscherm": "Night screen",
    "Een gedimde klok met dag en dagdeel. Eén tik toont even het gewone scherm.": "A dimmed clock with the day and part of the day. One tap briefly shows the normal screen.",
    "Nachtscherm vanaf": "Night screen from",
    "tot": "to",
    "Nachtscherm tot": "Night screen until",
    "Zodat {voornaam} de app niet per ongeluk sluit, zet je hem ook op het toestel zelf vast.": "So that {voornaam} doesn’t close the app by accident, also pin it on the device itself.",
    "Zo doe je dat": "Here’s how",
    "Zo ziet het eruit": "This is how it looks",
    "Ontbijten": "Breakfast",
    "Neem rustig de tijd.": "Take your time.",
    "De instellingen zijn meteen actief, ook op dit scherm.": "The settings take effect immediately, on this screen too.",
    "Op het beginscherm zetten": "Add to home screen",
    "Op de tablet van {voornaam} hoort LifeAngle als app te staan, niet als tabblad in een browser.": "On {voornaam}’s tablet, LifeAngle should be installed as an app, not as a browser tab.",
    "Uitleg per toestel": "Instructions per device",
    "Meldingen": "Notifications",
    "Een bericht op je gsm wanneer er iets afwijkt, bijvoorbeeld medicatie die om tien uur nog niet bevestigd is. Kan deze browser dat niet, dan gaan de dringende berichten per e-mail — dat staat hieronder.": "A message on your mobile when something is out of the ordinary, for example medication still not confirmed at ten o’clock. If this browser can’t do that, urgent messages go by email — see below.",
    "Deze browser kan geen meldingen tonen. Op iPhone en iPad lukt het alleen als LifeAngle op het beginscherm staat: deel-icoon, dan \"Zet op beginscherm\", en open LifeAngle daarna via dat icoon. Lukt dat niet, dan blijft de e-mail hieronder.": "This browser can’t show notifications. On iPhone and iPad it only works if LifeAngle is on the home screen: share icon, then \"Add to Home Screen\", then open LifeAngle from that icon. If that doesn’t work, the email below remains.",
    "De browser houdt meldingen tegen. Zet ze weer aan bij de instellingen van de site. Tot dan blijft de e-mail hieronder.": "The browser is blocking notifications. Turn them back on in the site settings. Until then, the email below remains.",
    "Geldt alleen voor dit toestel. Zet het ook aan op je andere toestellen.": "Only applies to this device. Turn it on on your other devices too.",
    "Niet mogelijk": "Not possible",
    "Meldingen op dit toestel": "Notifications on this device",
    "Er worden nu nog geen meldingen verstuurd: die horen bij de fase “ondersteund”. {voornaam} beslist daarover bij Wie ziet wat.": "No notifications are being sent yet: they belong to the “supported” phase. {voornaam} decides on that under Who sees what.",
    "Jouw naam": "Your name",
    "Zo staat het bij een bericht of een foto die je stuurt. Zet wat zij zou zeggen — \"Els\" of \"mama\" — en niet je volledige naam.": "This is how it appears on a message or photo you send. Put what she would say — \"Els\" or \"Mum\" — not your full name.",
    "Naam": "Name",
    "Opslaan…": "Saving…",
    "Opslaan": "Save",
    "Er staat nu je e-mailadres. De app toont voorlopig \"{naam}\".": "Your email address is there now. For now the app shows \"{naam}\".",
    "Opgeslagen. Het geldt vanaf je volgende bericht.": "Saved. It applies from your next message.",
    "Dat lukte niet. Probeer het straks nog eens.": "That didn’t work. Please try again later.",
    "Opslag op dit toestel": "Storage on this device",
    "Foto's en ingesproken berichten blijven bewaard, zodat ze ook zonder wifi te zien zijn. Dat loopt op. Opruimen kan altijd: alles komt daarna gewoon opnieuw van de server, alleen duurt de eerste keer kijken dan weer even.": "Photos and voice messages are kept so they can be seen without wifi. That adds up. You can always clear them: everything simply comes back from the server afterwards, only the first view takes a little longer again.",
    "Bezig…": "Working…",
    "Bewaarde foto’s opruimen": "Clear stored photos",
    "Opgeruimd.": "Cleared.",
    "Gebruik hiervoor niet de knop van de browser zelf (\"Gegevens verwijderen en rechten resetten\"). Die wist ook de aanmelding, en op de tablet de koppeling met dit huishouden.": "Don’t use the browser’s own button for this (\"Delete data and reset permissions\"). It also removes the sign-in and, on the tablet, the link with this household.",
    "Dat lukte niet.": "That didn’t work.",
    "Woont samen": "Lives together",
    "Woont {voornaam} in hetzelfde huis als iemand anders voor wie je zorgt? Dan is er één keuken, en hoef je de wasmachine maar één keer uit te leggen.": "Does {voornaam} live in the same house as someone else you care for? Then there is one kitchen, and you only need to explain the washing machine once.",
    "Gedeeld wordt alleen het huis: kamers, apparaten, waar dingen liggen en hoe ze werken. Niet de familie, de herinneringen, de medicatie, de agenda of het zorglogboek — die blijven per persoon.": "Only the house is shared: rooms, appliances, where things are and how they work. Not the family, memories, medication, calendar or care log — those stay per person.",
    "{voornaam} woont in huis bij {bij}.": "{voornaam} lives in the same house as {bij}.",
    "iemand anders": "someone else",
    "Home Memory is voor beiden hetzelfde. Wat je aan de keuken wijzigt, zien ze allebei.": "Home Memory is the same for both. What you change in the kitchen, they both see.",
    "Als je losmaakt, blijven de kamers en apparaten bij {bij} staan. {voornaam} begint dan met een leeg Home Memory.": "If you unlink, the rooms and appliances stay with {bij}. {voornaam} then starts with an empty Home Memory.",
    "het andere huishouden": "the other household",
    "Toch losmaken": "Unlink anyway",
    "Laat maar": "Never mind",
    "Losmaken": "Unlink",
    "Je beheert nog geen tweede huishouden dat op zichzelf woont. Zodra dat er is, kan je het hier samenvoegen.": "You don’t manage a second household living on its own yet. As soon as there is one, you can join them here.",
    "Zelfde huis": "Same house",
    "‹ Terug": "‹ Back",
    "Afdrukken of opslaan als PDF": "Print or save as PDF",
    "Dit ben ik": "This is me",
    "Noem me": "Call me",
    "Wat je moet weten om mij te helpen": "What you need to know to help me",
    "Zo praat je best met mij": "The best way to talk to me",
    "Als ik onrustig ben, helpt dit": "When I’m restless, this helps",
    "Hier raak ik van overstuur": "This upsets me",
    "Waar ik vandaan kom": "Where I come from",
    "Wie bij mij hoort": "The people who belong with me",
    "Nog niemand ingevuld.": "Nobody filled in yet.",
    "Mijn huisarts en andere contacten": "My GP and other contacts",
    "Hoe mijn dag er thuis uitziet": "What my day at home looks like",
    "Niet om na te volgen, wel om te weten wat ik gewend ben.": "Not to be followed to the letter, but to know what I’m used to.",
    "Wat ik graag heb": "What I like",
    "Wanneer ik thuis medicatie krijg": "When I get medication at home",
    "Dit is geen medicatielijst.": "This is not a medication list.",
    "Het zegt alleen op welke momenten ik thuis iets kreeg. Vraag het schema met doseringen aan mijn huisarts of apotheek.": "It only says at which times I received something at home. Ask my GP or pharmacy for the schedule with doses.",
    "Nog dit": "One more thing",
    "Samengesteld door mijn familie op {datum}, via de app LifeAngle. Geen medisch dossier.": "Put together by my family on {datum}, using the LifeAngle app. Not a medical record.",
    "— niet ingevuld —": "— not filled in —",
    "Hoe wil ze aangesproken worden?": "What does she like to be called?",
    "Niet iedereen heet voor iedereen hetzelfde.": "Not everyone goes by the same name for everyone.",
    "Zo praat je best met deze persoon": "The best way to talk to this person",
    "Wat jij vanzelf doet, weet een verpleegkundige op dag één niet.": "What you do without thinking, a nurse doesn’t know on day one.",
    "Traag praten, één vraag tegelijk. Ga links staan, daar hoort ze beter.": "Speak slowly, one question at a time. Stand on her left, she hears better on that side.",
    "Als ze onrustig is, helpt dit": "When she’s restless, this helps",
    "Het belangrijkste veld van het hele blad.": "The most important field on the whole sheet.",
    "Muziek van vroeger opzetten. Even mee naar buiten. Niet tegenspreken.": "Put on music from the old days. Go outside with her for a while. Don’t contradict her.",
    "Hier raakt ze van overstuur": "This upsets her",
    "Even belangrijk, en vaak moeilijker op te schrijven.": "Just as important, and often harder to write down.",
    "Veel mensen tegelijk. Als iemand zegt dat ze zich vergist.": "Lots of people at once. When someone tells her she’s mistaken.",
    "Nog iets dat ze moeten weten": "Anything else they should know",
    "Wat hier niet in de vakjes past.": "Whatever doesn’t fit in the boxes.",
    "Slaapt met het licht aan. De bril ligt altijd links naast het bed.": "Sleeps with the light on. The glasses are always to the left of the bed.",
    "Eén blad dat meegaat naar het ziekenhuis of het woonzorgcentrum. Daar is {voornaam} op dag één een naam op een lijst; dit maakt er een mens van. De rest — familie, voorkeuren, de dagindeling — haalt het blad uit wat hier al staat.": "One sheet that goes along to the hospital or care home. There, on day one, {voornaam} is a name on a list; this turns that into a person. The rest — family, preferences, the daily routine — the sheet takes from what is already here.",
    "Bekijken en afdrukken": "View and print",
    "Bezig met opslaan…": "Saving…",
    "Niet opgeslagen — probeer opnieuw.": "Not saved — please try again.",
    "{n} van {totaal} ingevuld. Het slaat vanzelf op.": "{n} of {totaal} filled in. It saves automatically.",
    "Indeling": "Layout",
    "Wat er op het dagscherm van {voornaam} staat, in welke volgorde en hoe groot. Het verandert meteen op de tablet; je hoeft die niet aan te raken.": "What is on {voornaam}’s day screen, in what order and how big. It changes on the tablet straight away; you don’t need to touch it.",
    "Niet opgeslagen — probeer opnieuw": "Not saved — please try again",
    "Opgeslagen": "Saved",
    "Nog niet klaar om te bewaren.": "Not ready to save yet.",
    "De database kent de indeling nog niet. Draai {bestand} in de SQL-editor van Supabase; tot dan toont het scherm van {voornaam} de standaardindeling en blijven wijzigingen hier niet staan.": "The database doesn’t know about the layout yet. Run {bestand} in the Supabase SQL editor; until then {voornaam}’s screen shows the default layout and changes here won’t be kept.",
    "Beginnen vanaf een sjabloon": "Start from a template",
    "Dit vervangt de hele indeling. Daarna kan je nog alles aanpassen.": "This replaces the whole layout. You can still change everything afterwards.",
    "In gebruik": "In use",
    "{n} blokken": "{n} blocks",
    "Zo ziet het scherm van {voornaam} eruit": "This is what {voornaam}’s screen looks like",
    "Tik een tegel om hem aan te passen.": "Tap a tile to change it.",
    "Het echte scherm bekijken": "View the real screen",
    "Bezig met laden…": "Loading…",
    "vast": "fixed",
    "vol": "full",
    "half": "half",
    "{n} tegel. De leesvolgorde is van boven naar beneden — precies wat de voorleesfunctie aanhoudt.": "{n} tile. The reading order is top to bottom — exactly what the read-aloud function follows.",
    "{n} tegels. De leesvolgorde is van boven naar beneden — precies wat de voorleesfunctie aanhoudt.": "{n} tiles. The reading order is top to bottom — exactly what the read-aloud function follows.",
    "Dit zijn er meer dan {n}. Dat kan, maar elke tegel erbij is één keuze meer die {voornaam} tegelijk ziet. Kijk gerust of er eentje bij kan die je niet mist.": "That’s more than {n}. That’s allowed, but every extra tile is one more choice {voornaam} sees at once. Feel free to check whether there’s one you wouldn’t miss.",
    "Gekozen tegel": "Selected tile",
    "Grootte": "Size",
    "Vol": "Full",
    "Half": "Half",
    "Deze tegel is altijd vol-breed; half wordt hier onleesbaar.": "This tile is always full width; at half it becomes unreadable.",
    "Halve tegels kunnen niet zolang de tekst op groot staat — dan blijven er drie woorden per regel over.": "Half tiles aren’t possible while the text is set to large — that would leave three words per line.",
    "Volgorde": "Order",
    "Omhoog": "Move up",
    "Omlaag": "Move down",
    "\"Wat nu?\" staat altijd bovenaan en kan niet weg. Dat is de vraag waar de app om draait; die hoort niet per huishouden ergens anders te staan. Half mag wel: op een tablet staat de kaart dan bovenaan de linkerkolom.": "\"What now?\" is always at the top and can’t be removed. That is the question the app revolves around; it shouldn’t be somewhere else per household. Half is allowed: on a tablet the card then sits at the top of the left column.",
    "Van het scherm halen": "Remove from the screen",
    "Tik hierboven een tegel om hem groter te maken, te verplaatsen of weg te halen.": "Tap a tile above to make it bigger, move it or remove it.",
    "Toevoegen": "Add",
    "Alles staat er al op.": "Everything is already on it.",
    "Wat nu?": "What now?",
    "Wat er op dit moment moet gebeuren, met een knop om het af te vinken.": "What needs to happen right now, with a button to tick it off.",
    "Daarna": "Next",
    "Het eerstvolgende dat eraan komt.": "The next thing coming up.",
    "Vandaag": "Today",
    "De hele dag als tijdlijn, met wat al gedaan is.": "The whole day as a timeline, with what has already been done.",
    "Berichten": "Messages",
    "Wat familie stuurde, met de mogelijkheid te antwoorden.": "What family sent, with the option to reply.",
    "Medicatie": "Medication",
    "Het eerstvolgende moment met de foto van de doos, en een knop om te bevestigen.": "The next moment with the photo of the box, and a button to confirm.",
    "Onthoud dit": "Remember this",
    "Iets laten onthouden: waar iets ligt, wat er gezegd is.": "Have something remembered: where something is, what was said.",
    "Muziek": "Music",
    "De radio of de muziek van vroeger, met één knop aan.": "The radio or music from the old days, on with one button.",
    "Vandaag vroeger": "On this day",
    "Een foto van deze dag in een ander jaar. Blijft weg op dagen waar niets bij past.": "A photo from this day in another year. Stays hidden on days with nothing to match.",
    "Herinneringen": "Memories",
    "De nieuwste foto, met een weg naar de hele tijdlijn. Staat er elke dag.": "The newest photo, with a way to the whole timeline. There every day.",
    "Weetjes": "Good to know",
    "Antwoorden op vragen die terugkomen: waar iets ligt, hoe iets moet.": "Answers to questions that keep coming back: where something is, how to do something.",
    "Vertel eens": "Tell me",
    "Elke dag één vraag over vroeger, voor het levensboek.": "One question a day about the old days, for the life book.",
    "Grote knoppen": "Big buttons",
    "Wat nu?, Familie en Help als drie grote knoppen.": "What now?, Family and Help as three big buttons.",
    "Rustig": "Calm",
    "Drie blokken. Eén ding tegelijk, elke dag op dezelfde plek.": "Three blocks. One thing at a time, in the same place every day.",
    "Standaard": "Standard",
    "De dag en wat familie stuurt, met de grote kaart bovenaan.": "The day and what family sends, with the big card at the top.",
    "Twee kolommen": "Two columns",
    "Zoals het scherm er vroeger liggend uitzag: links de dag, rechts wat er te doen en te zien is. Op een tablet loopt alles door in twee kolommen.": "Like the landscape screen used to look: the day on the left, what there is to do and see on the right. On a tablet everything flows in two columns.",
    "Alles": "Everything",
    "Elke module, om te zien wat er bestaat. Daarna weghalen wat niet past.": "Every module, to see what exists. Then remove what doesn’t fit.",
    "Je telefoonnummer. Komt op je vergrendelscherm, ook met de app dicht.": "Your phone number. Shows on your lock screen, even with the app closed.",
    "Stuur de bot eerst \"start\" in Telegram, en zoek dan hieronder je chat-id op.": "First send the bot \"start\" in Telegram, then look up your chat ID below.",
    "Weghalen": "Remove",
    "Bewaren": "Save",
    "Zoeken…": "Searching…",
    "Zoek mijn chat-id": "Find my chat ID",
    "Niemand gevonden. Stuur de bot eerst \"start\" in Telegram en probeer het opnieuw — of TG_BOT_TOKEN ontbreekt nog bij de secrets in Supabase.": "Nobody found. First send the bot \"start\" in Telegram and try again — or TG_BOT_TOKEN is still missing from the secrets in Supabase.",
    "Dat lukte niet. Draait push-notify al met de nieuwe code?": "That didn’t work. Is push-notify already running the new code?",
    "Bewaard.": "Saved.",
    "Weggehaald.": "Removed.",
    "E-mail": "Email",
    "e-mail": "email",
    "een melding op dit toestel": "a notification on this device",
    "Je hebt geen enkele weg aan staan buiten de app zelf. Zet e-mail aan, of vul hieronder een WhatsApp-nummer in — anders zie je een dringend bericht alleen wanneer LifeAngle open staat.": "You have no channel switched on apart from the app itself. Turn on email, or fill in a WhatsApp number below — otherwise you’ll only see an urgent message when LifeAngle is open.",
    "Dit toestel krijgt geen pushmeldingen. Toestemming geldt per toestel én per account: aanzetten op de tablet doet niets voor je telefoon. Op iPhone en iPad kan het alleen wanneer de app op het beginscherm staat.": "This device doesn’t get push notifications. Permission is per device and per account: turning it on on the tablet does nothing for your phone. On iPhone and iPad it only works when the app is on the home screen.",
    "Pushmeldingen worden alleen verstuurd wanneer de ondersteuning op \"ondersteund\" staat. Dat kan je aanpassen bij Wie ziet wat. De e-mail bij dringende berichten gaat wel door.": "Push notifications are only sent when support is set to \"supported\". You can change that under Who sees what. The email for urgent messages still goes out.",
    "Er wacht 1 melding die niet verstuurd raakt. Druk op \"Stuur een testmelding\" hieronder: dan zegt de app welke weg het laat afweten, in plaats van dat je moet raden.": "1 notification is waiting and isn’t getting sent. Press \"Send a test notification\" below: the app will then tell you which channel is failing, instead of you having to guess.",
    "Er wachten {n} meldingen die niet verstuurd raken. Druk op \"Stuur een testmelding\" hieronder: dan zegt de app welke weg het laat afweten, in plaats van dat je moet raden.": "{n} notifications are waiting and aren’t getting sent. Press \"Send a test notification\" below: the app will then tell you which channel is failing, instead of you having to guess.",
    "Je krijgt dringende berichten alleen in de app": "You only get urgent messages in the app",
    "Dringende berichten komen bij jou aan via {wegen}": "Urgent messages reach you via {wegen}",
    "en": "and",
    "Ook per e-mail, bij dringende berichten": "Also by email, for urgent messages",
    "Alleen wanneer ze vraagt of je belt, of om hulp vraagt. E-mail werkt op elk toestel, zonder toestemming — dit is de weg die het altijd haalt.": "Only when she asks you to call, or asks for help. Email works on every device, without permission — this is the channel that always gets through.",
    "Dringende meldingen ook per e-mail": "Urgent notifications by email too",
    "Alles staat klaar.": "Everything is ready.",
    "Stuur een testmelding": "Send a test notification",
    "Verstuurd, langs elke weg die aan staat. Komt er binnen een minuut niets aan, dan staat hierboven waarschijnlijk al waarom.": "Sent, via every channel that is on. If nothing arrives within a minute, the reason is probably already shown above.",
    "Deze weg staat uit bij de server:": "This channel is switched off on the server:",
    "Deze wegen staan uit bij de server:": "These channels are switched off on the server:",
    "{sleutels} ontbreekt nog bij Edge Functions → Secrets in Supabase.": "{sleutels} is still missing under Edge Functions → Secrets in Supabase.",
    "de secrets": "the secrets",
    "Een weg weigerde het bericht:": "A channel refused the message:",
    "Dat lukte niet. Draaide {bestand} al?": "That didn’t work. Has {bestand} been run yet?",
    "push-notify is niet bereikbaar. Kijk in Supabase bij Edge Functions of het adres onder de titel eindigt op /push-notify — staat daar iets anders, dan roept de app een functie aan die niet bestaat.": "push-notify can’t be reached. Check in Supabase under Edge Functions whether the address below the title ends in /push-notify — if it says something else, the app is calling a function that doesn’t exist.",
    "Dit toestel kan geen locatie bepalen.": "This device can’t determine a location.",
    "Toestemming voor locatie geweigerd in de browser.": "Location permission refused in the browser.",
    "Locatie": "Location",
    "Staat uit tot iemand er toestemming voor geeft. {voornaam} ziet altijd wanneer het aan staat, en kan het zelf uitzetten.": "Off until someone gives permission. {voornaam} always sees when it’s on, and can turn it off.",
    "Aan": "On",
    "Uit": "Off",
    "Uitzetten": "Turn off",
    "Aanzetten, met dit huis als veilige zone": "Turn on, with this house as the safe zone",
    "Veilige zone: {m} meter rond het huis. Familie krijgt één melding wanneer die zone verlaten wordt, niet bij elk punt erbuiten.": "Safe zone: {m} metres around the house. Family gets one notification when that zone is left, not for every point outside it.",
    "Laatst gemeten {wanneer} — buiten de zone": "Last measured {wanneer} — outside the zone",
    "Laatst gemeten {wanneer} — in de zone": "Last measured {wanneer} — inside the zone",
    "Nog geen positie doorgegeven.": "No position received yet.",
    "Posities worden na zeven dagen gewist. Er wordt niets bijgehouden zolang dit uit staat.": "Positions are deleted after seven days. Nothing is recorded while this is off.",
    "iPad of iPhone": "iPad or iPhone",
    "Open deze pagina in Safari. In een andere browser lukt het niet.": "Open this page in Safari. It won’t work in another browser.",
    "Druk onderaan (of bovenaan) op het deelicoon: een vierkantje met een pijl omhoog.": "Tap the share icon at the bottom (or top): a small square with an arrow pointing up.",
    "Scrol in de lijst tot \"Zet op beginscherm\".": "Scroll down the list to \"Add to Home Screen\".",
    "Druk rechtsboven op \"Voeg toe\".": "Tap \"Add\" in the top right.",
    "Apple laat geen installatieknop in de app zelf toe. Dit is de enige weg, en je hoeft het maar één keer te doen.": "Apple doesn’t allow an install button inside the app itself. This is the only way, and you only need to do it once.",
    "Android-tablet of -telefoon": "Android tablet or phone",
    "Open deze pagina in Chrome.": "Open this page in Chrome.",
    "Druk op de knop met de drie puntjes, rechtsboven.": "Tap the three-dot button in the top right.",
    "Kies \"App installeren\" of \"Toevoegen aan startscherm\".": "Choose \"Install app\" or \"Add to Home screen\".",
    "Bevestig met \"Installeren\".": "Confirm with \"Install\".",
    "Windows of Mac": "Windows or Mac",
    "Open deze pagina in Chrome of Edge.": "Open this page in Chrome or Edge.",
    "Klik op het installatie-icoon rechts in de adresbalk.": "Click the install icon on the right of the address bar.",
    "Klik op \"Installeren\".": "Click \"Install\".",
    "LifeAngle op het beginscherm": "LifeAngle on the home screen",
    "Dan opent de app met een eigen icoon, zonder adresbalk, en blijft ze ingelogd. Ze werkt ook door wanneer de wifi even hapert.": "The app then opens with its own icon, without an address bar, and stays signed in. It also keeps working when the wifi briefly drops.",
    "Deze app staat al op het beginscherm van dit toestel.": "This app is already on the home screen of this device.",
    "Nu installeren": "Install now",
    "De tablet klaarzetten": "Setting up the tablet",
    "Voor het toestel dat bij de persoon blijft staan. Eén keer instellen, daarna hoeft er niemand meer aan.": "For the device that stays with the person. Set it up once, and after that nobody needs to touch it.",
    "Laat de tablet in de lader staan, op een vaste plaats.": "Leave the tablet in its charger, in a fixed spot.",
    "Zet het schermslot uit, of gebruik een code die de familie kent.": "Turn off the screen lock, or use a code the family knows.",
    "Zet het scherm op \"nooit vergrendelen\" zolang hij aan de lader hangt.": "Set the screen to \"never lock\" while it’s on the charger.",
    "Zet in LifeAngle bij Instellingen de kioskmodus aan. Dat kan ook van op afstand.": "Turn on kiosk mode in LifeAngle under Settings. This can also be done remotely.",
    "Geef bij de eerste keer toestemming voor microfoon en camera.": "The first time, allow the microphone and camera.",
    "Zet het volume hoog genoeg om een inkomende oproep te horen.": "Set the volume high enough to hear an incoming call.",
    "Geluid uitproberen": "Test the sound",
    "Browsers laten geluid pas toe nadat iemand het scherm één keer heeft aangeraakt na het opstarten. Druk hier na het klaarzetten één keer, dan weet je dat de beltoon werkt op dit toestel.": "Browsers only allow sound after someone has touched the screen once after start-up. Press here once after setting up, and you’ll know the ringtone works on this device.",
    "Beltoon proberen": "Test the ringtone",
    "Hoor je niets, kijk dan of het toestel niet op stil staat en of het volume van de media hoog genoeg is.": "If you hear nothing, check that the device isn’t on silent and that the media volume is high enough.",
    "De app vastzetten": "Pinning the app",
    "Een app kan zichzelf niet vergrendelen; dat doet het toestel. Kies wat bij de tablet past.": "An app can’t lock itself; the device does that. Choose what suits the tablet.",
    "Videobellen en de microfoon werken alleen op een beveiligde verbinding. Via het gewone webadres is dat in orde; via een lokaal IP-adres niet.": "Video calls and the microphone only work on a secure connection. Via the normal web address that’s fine; via a local IP address it isn’t.",
    "Dit toestel: {platform}.": "This device: {platform}.",
    "iPad: Begeleide toegang": "iPad: Guided Access",
    "Ingebouwd en gratis. Uit de app gaan kan alleen nog met een code.": "Built in and free. Leaving the app is only possible with a code.",
    "Instellingen → Toegankelijkheid → Begeleide toegang: zet het aan en kies een code.": "Settings → Accessibility → Guided Access: turn it on and choose a code.",
    "Instellingen → Beeldscherm en helderheid → Automatisch vergrendelen: Nooit.": "Settings → Display & Brightness → Auto-Lock: Never.",
    "Open LifeAngle vanaf het beginscherm en klik drie keer snel op de zij- of thuisknop.": "Open LifeAngle from the home screen and quickly press the side or home button three times.",
    "Tik op Start. Stoppen doe je weer met drie klikken en de code.": "Tap Start. To stop, press three times again and enter the code.",
    "Android: app vastzetten": "Android: app pinning",
    "Ingebouwd en gratis. Goed genoeg voor de meeste mensen, maar wie weet hoe het werkt, krijgt het ongedaan.": "Built in and free. Good enough for most people, but someone who knows how it works can undo it.",
    "Instellingen → Beveiliging → App vastzetten (soms onder Meer beveiligingsinstellingen): aanzetten, met ontgrendelen bij losmaken.": "Settings → Security → App pinning (sometimes under More security settings): turn on, with unlock required to unpin.",
    "Open LifeAngle vanaf het beginscherm.": "Open LifeAngle from the home screen.",
    "Open het overzicht van recente apps, tik op het pictogram van LifeAngle en kies Vastzetten.": "Open the recent apps overview, tap the LifeAngle icon and choose Pin.",
    "Android: Fully Kiosk Browser": "Android: Fully Kiosk Browser",
    "Een kleine eenmalige licentie per toestel, en de degelijkste keuze voor een tablet die jaren aan de muur hangt. LifeAngle start vanzelf na een stroomonderbreking, en de kioskmodus kan dan ook de echte helderheid regelen.": "A small one-off licence per device, and the most robust choice for a tablet that hangs on the wall for years. LifeAngle starts by itself after a power cut, and kiosk mode can then also control the real brightness.",
    "Installeer Fully Kiosk Browser uit de Play Store.": "Install Fully Kiosk Browser from the Play Store.",
    "Zet het webadres van LifeAngle als Start URL.": "Set LifeAngle’s web address as the Start URL.",
    "Zet bij Advanced Web Settings de JavaScript Interface aan.": "Under Advanced Web Settings, turn on JavaScript Interface.",
    "Zet bij Device Management Keep Screen On en Launch on Boot aan.": "Under Device Management, turn on Keep Screen On and Launch on Boot.",
    "Zet Kiosk Mode aan en kies een code om eruit te gaan.": "Turn on Kiosk Mode and choose a code to exit it.",
    "Koppel de tablet daarna met de code uit Instellingen, net als anders.": "Then link the tablet with the code from Settings, as usual.",
    "Zet LifeAngle op het beginscherm van dit toestel": "Add LifeAngle to this device’s home screen",
    "Installeren": "Install",
    "Hoe doe ik dat?": "How do I do that?",
    "Verbergen": "Hide",
    "Later": "Later",
    "Er ging iets mis. Probeer het opnieuw.": "Something went wrong. Please try again.",
    "Voor wie is deze app?": "Who is this app for?",
    "Dat bepaalt wie de app beheert en welk scherm je straks ziet.": "This decides who manages the app and which screen you’ll see.",
    "Ik gebruik de app zelf": "I use the app myself",
    "Ik zorg voor een familielid": "I care for a family member",
    "Hoe heet je?": "What’s your name?",
    "Over wie gaat het?": "Who is it about?",
    "Zo spreekt de app je aan.": "This is how the app will address you.",
    "De naam die op het scherm komt te staan.": "The name that will appear on the screen.",
    "Adres, mag leeg blijven": "Address, may be left empty",
    "Lindestraat 12, Herent": "12 Linden Street, Leuven",
    "Het adres verschijnt op het hulpscherm, als antwoord op \"waar ben ik?\".": "The address appears on the help screen, as the answer to \"where am I?\".",
    "Wie is er belangrijk?": "Who is important?",
    "Drie volstaat om te beginnen. Later kan je er meer toevoegen en uitnodigen.": "Three is enough to start. You can add and invite more later.",
    "Dochter": "Daughter",
    "Telefoon": "Phone",
    "Nog iemand": "Someone else",
    "De dagelijkse routine": "The daily routine",
    "Eén regel per moment, beginnend met het uur. Pas aan wat niet klopt.": "One line per moment, starting with the time. Change whatever isn’t right.",
    "Welke kamers zijn er?": "Which rooms are there?",
    "Tik weg wat er niet is.": "Tap away what isn’t there.",
    "Eén ding om te onthouden": "One thing to remember",
    "Begin met wat het vaakst gezocht wordt of niet meer lukt.": "Start with what is searched for most often or no longer works.",
    "Koffiezetapparaat": "Coffee maker",
    "Op het aanrecht, rechts van de gootsteen.": "On the worktop, to the right of the sink.",
    "Vul het waterreservoir.\nZet een kopje onder de tuit.\nDruk op de grote knop.": "Fill the water tank.\nPut a cup under the spout.\nPress the big button.",
    "Terug": "Back",
    "Klaar": "Done",
    "Verder": "Next",
    "Ik registreer een woonzorgcentrum": "I’m registering a care home",
    "Deze stap overslaan": "Skip this step",
  },
} satisfies Vertaling
