import type { Vertaling } from '../uiTaal'

/** Importeren (84) en de demo (85). */
export default {
  fr: {
    '1 bewoner importeren': 'Importer 1 résident(e)',
    '1 bewoner staat nu in Care.': '1 résident(e) figure maintenant dans Care.',
    '1 uitnodiging maken': 'Créer 1 invitation',
    '1. Je lijst': '1. Votre liste',
    '2. Nakijken': '2. Vérifier',
    'Afdeling "{naam}" bestaat niet': 'L’unité « {naam} » n’existe pas',
    'Alle links (CSV)': 'Tous les liens (CSV)',
    'Bekijk als': 'Voir en tant que',
    'Bezig met nakijken…': 'Vérification en cours…',
    'CSV-bestand kiezen': 'Choisir un fichier CSV',
    'De demo en alle verzonnen bewoners wissen?': 'Supprimer la démo et tous les résidents fictifs ?',
    'Demo met verzonnen bewoners. Probeer gerust alles uit.': 'Démo avec des résidents fictifs. Essayez tout librement.',
    'Demo wissen': 'Supprimer la démo',
    'Demo wordt klaargezet…': 'Préparation de la démo…',
    'Demo-woonzorgcentrum openen': 'Ouvrir la maison de repos de démo',
    'E-mail familie': 'E-mail de la famille',
    'Een .xlsx-bestand? Kies in Excel "Opslaan als" en dan "CSV (gescheiden door lijstscheidingsteken)".':
      'Un fichier .xlsx ? Dans Excel, choisissez « Enregistrer sous » puis « CSV (séparateur : point-virgule) ».',
    'Eerst rondkijken?': 'D’abord jeter un coup d’œil ?',
    'Elke medewerker krijgt een eigen uitnodiging, 14 dagen geldig.': 'Chaque collaborateur reçoit sa propre invitation, valable 14 jours.',
    'Er staan geen rijen in je lijst.': 'Votre liste ne contient aucune ligne.',
    'Geen mail verstuurd: stuur de link zelf door': 'Aucun e-mail envoyé : transmettez le lien vous-même',
    Importeren: 'Importer',
    'Kolommen: e-mailadres en rol (beheerder, coördinator of zorgkundige). Kopieer de cellen in Excel en plak ze hieronder, of kies een CSV-bestand.':
      'Colonnes : adresse e-mail et rôle (gestionnaire, coordinateur ou soignant). Copiez les cellules dans Excel et collez-les ci-dessous, ou choisissez un fichier CSV.',
    'Kolommen: naam, afdeling, kamer en (als je wil) het e-mailadres van één familielid. Kopieer de cellen in Excel en plak ze hieronder, of kies een CSV-bestand.':
      'Colonnes : nom, unité, chambre et (si vous le souhaitez) l’adresse e-mail d’un membre de la famille. Copiez les cellules dans Excel et collez-les ci-dessous, ou choisissez un fichier CSV.',
    Link: 'Lien',
    'Mail verstuurd': 'E-mail envoyé',
    'Naar Beheer': 'Vers Gestion',
    'Naar Kamers': 'Vers Chambres',
    Nakijken: 'Vérifier',
    'Open een demo-woonzorgcentrum met afdelingen, kamers en acht verzonnen bewoners. Je kan het daarna met één klik wissen.':
      'Ouvrez une maison de repos de démo avec des unités, des chambres et huit résidents fictifs. Vous pourrez ensuite la supprimer en un clic.',
    'Plak hier je lijst': 'Collez votre liste ici',
    Status: 'Statut',
    'Stuur elke familie haar link (mail, WhatsApp). Wie de link opent met dat e-mailadres, wordt familiebeheerder en koppelt de tablet. De link is 14 dagen geldig.':
      'Envoyez à chaque famille son lien (e-mail, WhatsApp). La personne qui ouvre le lien avec cette adresse devient gestionnaire familial et associe la tablette. Le lien est valable 14 jours.',
    'Uitnodigingen gemaakt': 'Invitations créées',
    'Uitnodigingen voor de familie': 'Invitations pour la famille',
    Voorbeeldbestand: 'Fichier d’exemple',
    'Wijs ze toe aan zorgkundigen bij Beheer, en geef ze een kamer bij Kamers.':
      'Attribuez-les à des soignants dans Gestion et donnez-leur une chambre dans Chambres.',
    'Zet je bewoners en medewerkers in één keer in LifeAngle Care, rechtstreeks uit Excel.':
      'Ajoutez vos résidents et collaborateurs en une fois dans LifeAngle Care, directement depuis Excel.',
    fout: 'erreur',
    'geen geldig adres': 'adresse non valide',
    'klaar om te importeren': 'prêt à importer',
    'onbekende rol "{rol}"': 'rôle inconnu « {rol} »',
    overgeslagen: 'ignoré',
    '{n} bewoners importeren': 'Importer {n} résidents',
    '{n} bewoners staan nu in Care.': '{n} résidents figurent maintenant dans Care.',
    '{n} families krijgen een uitnodiging.': '{n} familles recevront une invitation.',
    '1 familie krijgt een uitnodiging.': '1 famille recevra une invitation.',
    '{n} uitnodigingen maken': 'Créer {n} invitations',
    '{ok} van {n} rijen zijn in orde.': '{ok} lignes sur {n} sont correctes.',
    // Meldingen van de database (84, 85)
    'Geen naam': 'Pas de nom',
    'Naam of kamer is te lang': 'Nom ou chambre trop long',
    'Staat twee keer in de lijst': 'Figure deux fois dans la liste',
    'Woont hier al': 'Réside déjà ici',
    'Alleen de beheerder of een coördinator importeert bewoners': 'Seul le gestionnaire ou un coordinateur peut importer des résidents',
    'De lijst is leeg': 'La liste est vide',
    'Hoogstens 500 bewoners per keer': '500 résidents maximum par import',
    'Deze bewoner heeft al een familiebeheerder; die nodigt de rest van de familie uit':
      'Ce résident a déjà un gestionnaire familial ; c’est lui qui invite le reste de la famille',
    'Alleen de beheerder of een coördinator van het woonzorgcentrum nodigt de familie uit':
      'Seul le gestionnaire ou un coordinateur de la maison de repos peut inviter la famille',
    'Te veel uitnodigingen. Probeer het over een uur opnieuw.': 'Trop d’invitations. Réessayez dans une heure.',
    'Dit kan alleen in een demo': 'Ceci n’est possible que dans une démo',
    'Onbekende rol': 'Rôle inconnu',
  },
  en: {
    '1 bewoner importeren': 'Import 1 resident',
    '1 bewoner staat nu in Care.': '1 resident is now in Care.',
    '1 uitnodiging maken': 'Create 1 invitation',
    '1. Je lijst': '1. Your list',
    '2. Nakijken': '2. Check',
    'Afdeling "{naam}" bestaat niet': 'Unit “{naam}” does not exist',
    'Alle links (CSV)': 'All links (CSV)',
    'Bekijk als': 'View as',
    'Bezig met nakijken…': 'Checking…',
    'CSV-bestand kiezen': 'Choose a CSV file',
    'De demo en alle verzonnen bewoners wissen?': 'Delete the demo and all made-up residents?',
    'Demo met verzonnen bewoners. Probeer gerust alles uit.': 'Demo with made-up residents. Feel free to try everything.',
    'Demo wissen': 'Delete demo',
    'Demo wordt klaargezet…': 'Setting up the demo…',
    'Demo-woonzorgcentrum openen': 'Open the demo care home',
    'E-mail familie': 'Family e-mail',
    'Een .xlsx-bestand? Kies in Excel "Opslaan als" en dan "CSV (gescheiden door lijstscheidingsteken)".':
      'An .xlsx file? In Excel, choose “Save as” and then “CSV (comma delimited)”.',
    'Eerst rondkijken?': 'Want to look around first?',
    'Elke medewerker krijgt een eigen uitnodiging, 14 dagen geldig.': 'Each staff member gets their own invitation, valid for 14 days.',
    'Er staan geen rijen in je lijst.': 'Your list has no rows.',
    'Geen mail verstuurd: stuur de link zelf door': 'No e-mail sent: forward the link yourself',
    Importeren: 'Import',
    'Kolommen: e-mailadres en rol (beheerder, coördinator of zorgkundige). Kopieer de cellen in Excel en plak ze hieronder, of kies een CSV-bestand.':
      'Columns: e-mail address and role (administrator, coordinator or carer). Copy the cells in Excel and paste them below, or choose a CSV file.',
    'Kolommen: naam, afdeling, kamer en (als je wil) het e-mailadres van één familielid. Kopieer de cellen in Excel en plak ze hieronder, of kies een CSV-bestand.':
      'Columns: name, unit, room and (optionally) the e-mail address of one family member. Copy the cells in Excel and paste them below, or choose a CSV file.',
    Link: 'Link',
    'Mail verstuurd': 'E-mail sent',
    'Naar Beheer': 'Go to Management',
    'Naar Kamers': 'Go to Rooms',
    Nakijken: 'Check',
    'Open een demo-woonzorgcentrum met afdelingen, kamers en acht verzonnen bewoners. Je kan het daarna met één klik wissen.':
      'Open a demo care home with units, rooms and eight made-up residents. You can delete it afterwards with one click.',
    'Plak hier je lijst': 'Paste your list here',
    Status: 'Status',
    'Stuur elke familie haar link (mail, WhatsApp). Wie de link opent met dat e-mailadres, wordt familiebeheerder en koppelt de tablet. De link is 14 dagen geldig.':
      'Send each family its link (e-mail, WhatsApp). Whoever opens the link with that e-mail address becomes the family administrator and pairs the tablet. The link is valid for 14 days.',
    'Uitnodigingen gemaakt': 'Invitations created',
    'Uitnodigingen voor de familie': 'Invitations for the family',
    Voorbeeldbestand: 'Example file',
    'Wijs ze toe aan zorgkundigen bij Beheer, en geef ze een kamer bij Kamers.': 'Assign them to carers in Management, and give them a room in Rooms.',
    'Zet je bewoners en medewerkers in één keer in LifeAngle Care, rechtstreeks uit Excel.':
      'Add your residents and staff to LifeAngle Care in one go, straight from Excel.',
    fout: 'error',
    'geen geldig adres': 'not a valid address',
    'klaar om te importeren': 'ready to import',
    'onbekende rol "{rol}"': 'unknown role “{rol}”',
    overgeslagen: 'skipped',
    '{n} bewoners importeren': 'Import {n} residents',
    '{n} bewoners staan nu in Care.': '{n} residents are now in Care.',
    '{n} families krijgen een uitnodiging.': '{n} families will get an invitation.',
    '1 familie krijgt een uitnodiging.': '1 family will get an invitation.',
    '{n} uitnodigingen maken': 'Create {n} invitations',
    '{ok} van {n} rijen zijn in orde.': '{ok} of {n} rows are fine.',
    'Geen naam': 'No name',
    'Naam of kamer is te lang': 'Name or room is too long',
    'Staat twee keer in de lijst': 'Appears twice in the list',
    'Woont hier al': 'Already lives here',
    'Alleen de beheerder of een coördinator importeert bewoners': 'Only the administrator or a coordinator can import residents',
    'De lijst is leeg': 'The list is empty',
    'Hoogstens 500 bewoners per keer': 'At most 500 residents at a time',
    'Deze bewoner heeft al een familiebeheerder; die nodigt de rest van de familie uit':
      'This resident already has a family administrator; they invite the rest of the family',
    'Alleen de beheerder of een coördinator van het woonzorgcentrum nodigt de familie uit':
      'Only the care home’s administrator or a coordinator can invite the family',
    'Te veel uitnodigingen. Probeer het over een uur opnieuw.': 'Too many invitations. Try again in an hour.',
    'Dit kan alleen in een demo': 'This is only possible in a demo',
    'Onbekende rol': 'Unknown role',
  },
} satisfies Vertaling
