import type { Vertaling } from '../uiTaal'

/** Zorgteam: beheer, bewoners, uitnodigingen, noodtoegang (groep zorg1). */
export default {
  fr: {
    "Beheer": "Gestion",
    "Koppelcode voor familie": "Code de liaison pour la famille",
    "Geef deze code aan de familie van een nieuwe bewoner. De familiebeheerder koppelt er zelf het huishouden mee, bij \"Wie ziet wat\". Een woonzorgcentrum kan nooit zelf een bewoner toevoegen.": "Donnez ce code à la famille d'un nouveau résident. Le gestionnaire familial y relie lui-même le foyer, sous « Qui voit quoi ». Une maison de repos ne peut jamais ajouter elle-même un résident.",
    "Gekopieerd": "Copié",
    "Kopiëren": "Copier",
    "Een nieuwe code maken? De oude werkt dan niet meer.": "Créer un nouveau code ? L'ancien ne fonctionnera plus.",
    "Nieuwe code": "Nouveau code",
    "Bewoners": "Résidents",
    "Medewerkers": "Collaborateurs",
    "Afdelingen": "Unités",
    "Open uitnodigingen": "Invitations en cours",
    "Vraagt aandacht": "Demande de l'attention",
    "Overzicht": "Aperçu",
    "Alles in orde: elke bewoner wordt gevolgd en heeft een plaats.": "Tout est en ordre : chaque résident est suivi et a une place.",
    "Belangrijk:": "Important :",
    "En nog {n} andere.": "Et {n} autres.",
    "Bewoners en wie voor hen zorgt": "Les résidents et qui prend soin d'eux",
    "Wie toegewezen is, ziet de agenda, de zorgnotities en de contactpersonen van die bewoner. Een team lead ziet alle bewoners van zijn afdeling.": "Les personnes assignées voient l'agenda, les notes de soins et les personnes de contact de ce résident. Un chef d'équipe voit tous les résidents de son unité.",
    "Zoek een bewoner": "Rechercher un résident",
    "Nog geen bewoners. Een bewoner verschijnt hier zodra de familie koppelt met de code hierboven.": "Pas encore de résidents. Un résident apparaît ici dès que la famille se relie avec le code ci-dessus.",
    "Medewerker": "Collaborateur",
    "Toewijzing van {naam} stoppen": "Arrêter l'assignation de {naam}",
    "medewerker": "collaborateur",
    "Medewerker toewijzen aan {naam}": "Assigner un collaborateur à {naam}",
    "+ Toewijzen": "+ Assigner",
    "Afdeling {naam}": "Unité {naam}",
    "Geen afdeling": "Pas d'unité",
    "kamer {kamer}": "chambre {kamer}",
    "aanpassen": "modifier",
    "Afdeling": "Unité",
    "Geen": "Aucune",
    "Kamer": "Chambre",
    "Bewaren": "Enregistrer",
    "Annuleren": "Annuler",
    "niet actief": "inactif",
    "team lead": "chef d'équipe",
    "{naam} van afdeling {afdeling} halen": "Retirer {naam} de l'unité {afdeling}",
    "{naam} op een afdeling zetten": "Placer {naam} dans une unité",
    "+ Afdeling": "+ Unité",
    "{naam} (team lead)": "{naam} (chef d'équipe)",
    "Medewerker uitnodigen": "Inviter un collaborateur",
    "E-mailadres": "Adresse e-mail",
    "Rol": "Rôle",
    "Zorgmedewerker": "Soignant(e)",
    "Coördinator": "Coordinateur",
    "Beheerder": "Administrateur",
    "Uitnodiging maken": "Créer l'invitation",
    "De uitnodiging is gemaild. Je kan de link ook zelf doorsturen.": "L'invitation a été envoyée par e-mail. Vous pouvez aussi transmettre le lien vous-même.",
    "Stuur deze link naar de medewerker.": "Envoyez ce lien au collaborateur.",
    "Hij werkt alleen voor wie inlogt met dat e-mailadres, 14 dagen lang.": "Il ne fonctionne que pour la personne qui se connecte avec cette adresse e-mail, pendant 14 jours.",
    "Link kopiëren": "Copier le lien",
    "Actieve bewoners": "Résidents actifs",
    "Een bewoner telt op elke dag met een lopend verblijf, niet op hoe vaak de app gebruikt wordt.": "Un résident compte chaque jour où il a un séjour en cours, pas selon la fréquence d'utilisation de l'app.",
    "Vandaag": "Aujourd'hui",
    "Bewonersdagen deze maand": "Journées-résidents ce mois-ci",
    "Noodtoegang": "Accès d'urgence",
    "Een team lead": "Un chef d'équipe",
    "een bewoner": "un résident",
    "loopt nog": "en cours",
    "gestopt": "arrêté",
    "afgelopen": "terminé",
    "Met {termijn} worden {n} notitie van bewoners die lang geleden vertrokken binnen de week gewist. Doorgaan?": "Avec {termijn}, {n} note de résidents partis depuis longtemps sera supprimée dans la semaine. Continuer ?",
    "Met {termijn} worden {n} notities van bewoners die lang geleden vertrokken binnen de week gewist. Doorgaan?": "Avec {termijn}, {n} notes de résidents partis depuis longtemps seront supprimées dans la semaine. Continuer ?",
    "Bewaard: {termijn}.": "Enregistré : {termijn}.",
    "Bewaartermijn zorgnotities": "Durée de conservation des notes de soins",
    "Zolang een bewoner hier woont, blijven de zorgnotities bewaard. Na het vertrek worden ze na deze termijn automatisch gewist. De termijn geldt ook voor wie al vertrokken is, gerekend vanaf het vertrek.": "Tant qu'un résident vit ici, les notes de soins sont conservées. Après son départ, elles sont automatiquement supprimées au terme de cette durée. La durée s'applique aussi aux personnes déjà parties, à compter de leur départ.",
    "Bewaren na vertrek": "Conserver après le départ",
    "{termijn} na vertrek": "{termijn} après le départ",
    "Met {termijn} verdwijnen vannacht {n} oudere overdracht. Doorgaan?": "Avec {termijn}, {n} transmission plus ancienne disparaîtra cette nuit. Continuer ?",
    "Met {termijn} verdwijnen vannacht {n} oudere overdrachten. Doorgaan?": "Avec {termijn}, {n} transmissions plus anciennes disparaîtront cette nuit. Continuer ?",
    "Bewaartermijn overdracht": "Durée de conservation des transmissions",
    "Een overdracht gaat over een dienst. Ze wordt elke nacht gewist zodra ze ouder is dan deze termijn. Wat blijvend belangrijk is over een bewoner, hoort in een zorgnotitie.": "Une transmission concerne un service. Elle est supprimée chaque nuit dès qu'elle dépasse cette durée. Ce qui reste important à propos d'un résident a sa place dans une note de soins.",
    "Met {termijn} verdwijnen vannacht {n} oudere teamberichten. Doorgaan?": "Avec {termijn}, {n} messages d'équipe plus anciens disparaîtront cette nuit. Continuer ?",
    "Bewaartermijn teamberichten": "Durée de conservation des messages d'équipe",
    "Teamberichten worden elke nacht gewist zodra ze ouder zijn dan deze termijn.": "Les messages d'équipe sont supprimés chaque nuit dès qu'ils dépassent cette durée.",
    "Als beheerder ziet {naam} geen inhoud over bewoners: afdelingen en toewijzingen vervallen.": "En tant qu'administrateur, {naam} ne voit aucun contenu sur les résidents : les unités et assignations sont supprimées.",
    "{naam} {rol} maken?": "Nommer {naam} {rol} ?",
    "Rol van {naam}": "Rôle de {naam}",
    "{naam} uit dienst zetten? Toegang, afdelingen en toewijzingen stoppen meteen.": "Retirer {naam} du service ? L'accès, les unités et les assignations s'arrêtent immédiatement.",
    "Uit dienst": "Retirer du service",
    "Terug in dienst": "Remettre en service",
    "Opnieuw gemaild, en 14 dagen langer geldig.": "Renvoyée par e-mail, et valable 14 jours de plus.",
    "14 dagen langer geldig. De mail kon niet vertrekken; stuur de link zelf.": "Valable 14 jours de plus. L'e-mail n'a pas pu partir ; envoyez le lien vous-même.",
    "Openstaande uitnodigingen": "Invitations en attente",
    "Geen openstaande uitnodigingen.": "Aucune invitation en attente.",
    "Verlopen op {datum}": "Expirée le {datum}",
    "Geldig tot {datum}": "Valable jusqu'au {datum}",
    "Opnieuw sturen": "Renvoyer",
    "De uitnodiging voor {email} intrekken? De link werkt dan niet meer.": "Révoquer l'invitation pour {email} ? Le lien ne fonctionnera plus.",
    "Intrekken": "Révoquer",
    "Organisatie": "Organisation",
    "Naam": "Nom",
    "Contact-e-mail": "E-mail de contact",
    "Btw-nummer": "Numéro de TVA",
    "Bewaard.": "Enregistré.",
    "Nog geen afdelingen.": "Pas encore d'unités.",
    "Afdeling {naam} archiveren? Medewerkers verliezen hun plaats op deze afdeling.": "Archiver l'unité {naam} ? Les collaborateurs perdent leur place dans cette unité.",
    "Nieuwe afdeling": "Nouvelle unité",
    "De Eik": "Le Chêne",
    "Toevoegen": "Ajouter",
    "Gearchiveerd ({n})": "Archivées ({n})",
    "Terugzetten": "Restaurer",
    "Nieuwe naam voor {naam}": "Nouveau nom pour {naam}",
    "{naam} hernoemen": "Renommer {naam}",
    "Hernoemen": "Renommer",
    "{naam} archiveren": "Archiver {naam}",
    "Archiveren": "Archiver",
    "Bewoner": "Résident",
    "de bewoner": "le résident",
    "deze bewoner": "ce résident",
    "Je bent niet toegewezen aan deze bewoner. Vraag het aan je coördinator.": "Vous n'êtes pas assigné(e) à ce résident. Demandez-le à votre coordinateur.",
    "Niets gepland vandaag.": "Rien de prévu aujourd'hui.",
    "gedaan": "fait",
    "Contactpersonen": "Personnes de contact",
    "Geen contactpersonen.": "Aucune personne de contact.",
    "Bel {naam}": "Appeler {naam}",
    "Zorgnotities": "Notes de soins",
    "Correctie op:": "Correction de :",
    "Soort notitie": "Type de note",
    "Wat zag of deed je?": "Qu'avez-vous vu ou fait ?",
    "Ook voor de familie": "Aussi pour la famille",
    "Familie die mag meekijken en de bewoner zelf zien deze notitie. Anders blijft ze in het team.": "La famille autorisée à consulter et le résident lui-même voient cette note. Sinon, elle reste au sein de l'équipe.",
    "Bezig…": "En cours…",
    "Correctie bewaren": "Enregistrer la correction",
    "Notitie bewaren": "Enregistrer la note",
    "Een notitie kan je niet aanpassen of wissen. Klopt er iets niet, voeg dan een correctie toe.": "Une note ne peut être ni modifiée ni supprimée. Si quelque chose n'est pas correct, ajoutez une correction.",
    "Nog geen zorgnotities.": "Pas encore de notes de soins.",
    "Een collega": "Un collègue",
    "ook familie": "aussi la famille",
    "gecorrigeerd": "corrigée",
    "correctie": "correction",
    "Corrigeren": "Corriger",
    "Je bent niet toegewezen aan {naam}. In een noodgeval kan je als team lead 4 uur meekijken: naam, voorkeuren, agenda, logboek, zorgnotities en contactpersonen. Geen dagboek, documenten of locatie.": "Vous n'êtes pas assigné(e) à {naam}. En cas d'urgence, en tant que chef d'équipe, vous pouvez consulter pendant 4 heures : nom, préférences, agenda, journal, notes de soins et personnes de contact. Pas de journal intime, de documents ni de localisation.",
    "De familiebeheerder en de beheerder van je organisatie krijgen meteen bericht, met jouw reden.": "Le gestionnaire familial et l'administrateur de votre organisation sont prévenus immédiatement, avec votre motif.",
    "Elke keer dat je kijkt, wordt bijgehouden.": "Chaque consultation est enregistrée.",
    "Hoogstens 3 keer per 24 uur.": "Au maximum 3 fois par 24 heures.",
    "Waarom heb je dit nu nodig?": "Pourquoi en avez-vous besoin maintenant ?",
    "Bijvoorbeeld: gevallen in de gang, familie niet bereikbaar, nachtdienst zoekt de contactpersoon.": "Par exemple : chute dans le couloir, famille injoignable, l'équipe de nuit cherche la personne de contact.",
    "Genoeg uitleg.": "Explication suffisante.",
    "Nog {n} teken.": "Encore {n} caractère.",
    "Nog {n} tekens.": "Encore {n} caractères.",
    "Noodtoegang starten": "Démarrer l'accès d'urgence",
    "Noodtoegang tot {uur}": "Accès d'urgence jusqu'à {uur}",
    "Noodtoegang nu stoppen?": "Arrêter l'accès d'urgence maintenant ?",
    "Nu stoppen": "Arrêter maintenant",
    "Elke keer dat je deze pagina opent, wordt bijgehouden.": "Chaque ouverture de cette page est enregistrée.",
    "Voorkeuren": "Préférences",
    "Geen voorkeuren genoteerd.": "Aucune préférence notée.",
    "Agenda vandaag en morgen": "Agenda aujourd'hui et demain",
    "Niets gepland.": "Rien de prévu.",
    "Laatste 24 uur": "Dernières 24 heures",
    "Niets genoteerd.": "Rien de noté.",
    "zorgnotitie": "note de soins",
    "logboek": "journal",
    "Terug naar de bewoners": "Retour aux résidents",
    "de noodtoegang loopt door tot je ze stopt of tot ze afloopt.": "l'accès d'urgence reste actif jusqu'à ce que vous l'arrêtiez ou qu'il expire.",
    "Nog geen afdeling": "Pas encore d'unité",
    "Jouw bewoners en die van je afdeling.": "Vos résidents et ceux de votre unité.",
    "De bewoners die jou zijn toegewezen.": "Les résidents qui vous sont assignés.",
    "Mijn bewoners": "Mes résidents",
    "Je bent nog aan niemand toegewezen. Vraag het aan je coördinator of de beheerder van {organisatie}.": "Vous n'êtes encore assigné(e) à personne. Demandez-le à votre coordinateur ou à l'administrateur de {organisatie}.",
    "je organisatie": "votre organisation",
    "via je afdeling": "via votre unité",
    "{n} vraag": "{n} question",
    "{n} vragen": "{n} questions",
    "Andere bewoners": "Autres résidents",
    "Je ziet hier alleen naam en kamer.": "Vous ne voyez ici que le nom et la chambre.",
    "In een noodgeval kan je als team lead 4 uur meekijken; de familie krijgt daar meteen bericht van.": "En cas d'urgence, en tant que chef d'équipe, vous pouvez consulter pendant 4 heures ; la famille en est immédiatement prévenue.",
    "Naam, afdeling of kamer": "Nom, unité ou chambre",
    "Geen andere bewoners gevonden.": "Aucun autre résident trouvé.",
    "Even geduld…": "Un instant…",
    "Een woonzorgcentrum registreren": "Enregistrer une maison de repos",
    "Je wordt beheerder. Daarna nodig je medewerkers uit en krijg je een code voor de familie van je bewoners.": "Vous en devenez l'administrateur. Ensuite, vous invitez vos collaborateurs et recevez un code pour la famille de vos résidents.",
    "Werk je in een woonzorgcentrum dat al LifeAngle gebruikt? Dan heb je een uitnodiging nodig van je beheerder.": "Vous travaillez dans une maison de repos qui utilise déjà LifeAngle ? Il vous faut alors une invitation de votre administrateur.",
    "Naam van het woonzorgcentrum": "Nom de la maison de repos",
    "WZC De Linde": "MRS Les Tilleuls",
    "Registreren": "Enregistrer",
    "Terug": "Retour",
    "Deze link is onvolledig. Vraag een nieuwe uitnodiging.": "Ce lien est incomplet. Demandez une nouvelle invitation.",
    "Je bent uitgenodigd": "Vous êtes invité(e)",
    "Om in LifeAngle Care te werken voor je woonzorgcentrum.": "Pour travailler dans LifeAngle Care pour votre maison de repos.",
    "Eerst even inloggen": "Connectez-vous d'abord",
    "Gebruik het e-mailadres waarop je de uitnodiging kreeg. Je krijgt een code van zes cijfers.": "Utilisez l'adresse e-mail à laquelle vous avez reçu l'invitation. Vous recevrez un code à six chiffres.",
    "Deze uitnodiging bestaat niet.": "Cette invitation n'existe pas.",
    "{organisatie} nodigt je uit": "{organisatie} vous invite",
    "Als {rol}.": "En tant que {rol}.",
    "Deze uitnodiging is {status}. Vraag je beheerder om een nieuwe.": "Cette invitation est {status}. Demandez-en une nouvelle à votre administrateur.",
    "ingetrokken": "révoquée",
    "al gebruikt": "déjà utilisée",
    "verlopen": "expirée",
    "Deze uitnodiging is voor": "Cette invitation est destinée à",
    "Je bent nu ingelogd als": "Vous êtes actuellement connecté(e) en tant que",
    "Uitloggen en inloggen met {email}": "Se déconnecter et se connecter avec {email}",
    "Uitnodiging aanvaarden": "Accepter l'invitation",
    "Uitnodiging": "Invitation",
    "Uitnodiging van {organisatie}": "Invitation de {organisatie}",
    "Je bent uitgenodigd als {rol}. Werk je daar? Dan hoef je hieronder niets in te vullen.": "Vous êtes invité(e) en tant que {rol}. Vous y travaillez ? Vous n'avez alors rien à remplir ci-dessous.",
    "Aanvaarden": "Accepter",
    "Woonzorgcentrum": "Maison de repos",
    "Uitnodiging van {organisatie} aanvaarden": "Accepter l'invitation de {organisatie}",
    "Naar het woonzorgcentrum": "Vers la maison de repos",
    "Verhuisd": "Déménagé(e)",
    "Overleden": "Décédé(e)",
    "Andere reden": "Autre raison",
    "Verblijf beëindigen": "Mettre fin au séjour",
    "Het verblijf van {naam} beëindigen": "Mettre fin au séjour de {naam}",
    "Het zorgteam verliest meteen de toegang en alle toewijzingen stoppen. De familie krijgt een melding en houdt al haar gegevens. Komt {naam} terug, dan koppelt de familie opnieuw met de koppelcode.": "L'équipe soignante perd immédiatement l'accès et toutes les assignations s'arrêtent. La famille est prévenue et conserve toutes ses données. Si {naam} revient, la famille se relie à nouveau avec le code de liaison.",
    "Reden": "Raison",
    "Open vragen van bewoners": "Questions en attente des résidents",
    "Vragen van {naam}": "Questions de {naam}",
    "{n} nieuw": "{n} nouveau(x)",
    "Nog geen vragen. {naam} kan op de tablet iets vragen aan het zorgteam.": "Pas encore de questions. {naam} peut poser une question à l'équipe soignante depuis la tablette.",
    "Antwoord": "Réponse",
    "Antwoord aan {naam}": "Réponse à {naam}",
    "Kort en eenvoudig, bv. 'Ik kom om 15 uur.'": "Court et simple, p. ex. « Je passe à 15 h. »",
    "Antwoord sturen": "Envoyer la réponse",
    "Gezien": "Vu",
    "Antwoorden": "Répondre",
    "Zo praat je best met mij": "Voici comment me parler",
    "Als ik onrustig ben, helpt dit": "Quand je suis agité(e), ceci m'aide",
    "Hier raak ik van overstuur": "Ceci me bouleverse",
    "Dit ben ik": "Qui je suis",
    "De familie vulde nog niets in. Vraag hen om \"Dit ben ik\" aan te vullen in de app.": "La famille n'a encore rien rempli. Demandez-lui de compléter « Qui je suis » dans l'app.",
    "Noem mij": "Appelez-moi",
    "Wie bij mij hoort": "Mes proches",
    "Wat ik graag heb": "Ce que j'aime",
    "Uit mijn verhaal": "Extrait de mon histoire",
    "Ingevuld door {naam} en de familie.": "Rempli par {naam} et la famille.",
    "Niemand volgt {naam}. Wijs een medewerker toe.": "Personne ne suit {naam}. Assignez un collaborateur.",
    "{naam} heeft nog geen afdeling.": "{naam} n'a pas encore d'unité.",
    "{naam} heeft nog geen kamer.": "{naam} n'a pas encore de chambre.",
    "Afdeling {naam} heeft geen team lead.": "L'unité {naam} n'a pas de chef d'équipe.",
    "{naam} staat op geen enkele afdeling.": "{naam} n'est dans aucune unité.",
    "De uitnodiging voor {email} verloopt binnenkort en is nog niet aanvaard.": "L'invitation pour {email} expire bientôt et n'a pas encore été acceptée.",
    "Observatie": "Observation",
    "Zorg": "Soins",
    "Maaltijd": "Repas",
    "Slaap": "Sommeil",
    "Stemming": "Humeur",
    "Incident": "Incident",
    "Overig": "Autre",
    "Vroege dienst": "Service du matin",
    "Late dienst": "Service du soir",
    "Nachtdienst": "Service de nuit",
    "Alleen de beheerder kan een afdeling hernoemen.": "Seul l'administrateur peut renommer une unité.",
    "Alleen de beheerder kan de gegevens aanpassen.": "Seul l'administrateur peut modifier les données.",
    "1 jaar": "1 an",
    "{n} jaar": "{n} ans",
    "{n} maanden": "{n} mois",
    "Alleen de beheerder kan dit aanpassen.": "Seul l'administrateur peut modifier ceci.",
    "Deze code kennen we niet. Kijk ze na of vraag ze opnieuw aan het woonzorgcentrum.": "Nous ne connaissons pas ce code. Vérifiez-le ou redemandez-le à la maison de repos.",
    "1 week": "1 semaine",
    "2 weken": "2 semaines",
    "{n} dagen": "{n} jours",
  },
  en: {
    "Beheer": "Management",
    "Koppelcode voor familie": "Link code for family",
    "Geef deze code aan de familie van een nieuwe bewoner. De familiebeheerder koppelt er zelf het huishouden mee, bij \"Wie ziet wat\". Een woonzorgcentrum kan nooit zelf een bewoner toevoegen.": "Give this code to the family of a new resident. The family administrator links the household themselves, under \"Who sees what\". A care home can never add a resident itself.",
    "Gekopieerd": "Copied",
    "Kopiëren": "Copy",
    "Een nieuwe code maken? De oude werkt dan niet meer.": "Create a new code? The old one will stop working.",
    "Nieuwe code": "New code",
    "Bewoners": "Residents",
    "Medewerkers": "Staff",
    "Afdelingen": "Units",
    "Open uitnodigingen": "Open invitations",
    "Vraagt aandacht": "Needs attention",
    "Overzicht": "Overview",
    "Alles in orde: elke bewoner wordt gevolgd en heeft een plaats.": "All in order: every resident is followed up and has a place.",
    "Belangrijk:": "Important:",
    "En nog {n} andere.": "And {n} more.",
    "Bewoners en wie voor hen zorgt": "Residents and who cares for them",
    "Wie toegewezen is, ziet de agenda, de zorgnotities en de contactpersonen van die bewoner. Een team lead ziet alle bewoners van zijn afdeling.": "Whoever is assigned sees that resident's diary, care notes and contacts. A team lead sees all residents of their unit.",
    "Zoek een bewoner": "Search for a resident",
    "Nog geen bewoners. Een bewoner verschijnt hier zodra de familie koppelt met de code hierboven.": "No residents yet. A resident appears here as soon as the family links up with the code above.",
    "Medewerker": "Staff member",
    "Toewijzing van {naam} stoppen": "Stop assignment of {naam}",
    "medewerker": "staff member",
    "Medewerker toewijzen aan {naam}": "Assign a staff member to {naam}",
    "+ Toewijzen": "+ Assign",
    "Afdeling {naam}": "Unit {naam}",
    "Geen afdeling": "No unit",
    "kamer {kamer}": "room {kamer}",
    "aanpassen": "change",
    "Afdeling": "Unit",
    "Geen": "None",
    "Kamer": "Room",
    "Bewaren": "Save",
    "Annuleren": "Cancel",
    "niet actief": "inactive",
    "team lead": "team lead",
    "{naam} van afdeling {afdeling} halen": "Remove {naam} from unit {afdeling}",
    "{naam} op een afdeling zetten": "Add {naam} to a unit",
    "+ Afdeling": "+ Unit",
    "{naam} (team lead)": "{naam} (team lead)",
    "Medewerker uitnodigen": "Invite a staff member",
    "E-mailadres": "Email address",
    "Rol": "Role",
    "Zorgmedewerker": "Care worker",
    "Coördinator": "Coordinator",
    "Beheerder": "Administrator",
    "Uitnodiging maken": "Create invitation",
    "De uitnodiging is gemaild. Je kan de link ook zelf doorsturen.": "The invitation has been emailed. You can also forward the link yourself.",
    "Stuur deze link naar de medewerker.": "Send this link to the staff member.",
    "Hij werkt alleen voor wie inlogt met dat e-mailadres, 14 dagen lang.": "It only works for whoever signs in with that email address, for 14 days.",
    "Link kopiëren": "Copy link",
    "Actieve bewoners": "Active residents",
    "Een bewoner telt op elke dag met een lopend verblijf, niet op hoe vaak de app gebruikt wordt.": "A resident counts on every day with an ongoing stay, not on how often the app is used.",
    "Vandaag": "Today",
    "Bewonersdagen deze maand": "Resident days this month",
    "Noodtoegang": "Emergency access",
    "Een team lead": "A team lead",
    "een bewoner": "a resident",
    "loopt nog": "still running",
    "gestopt": "stopped",
    "afgelopen": "expired",
    "Met {termijn} worden {n} notitie van bewoners die lang geleden vertrokken binnen de week gewist. Doorgaan?": "With {termijn}, {n} note of residents who left long ago will be deleted within the week. Continue?",
    "Met {termijn} worden {n} notities van bewoners die lang geleden vertrokken binnen de week gewist. Doorgaan?": "With {termijn}, {n} notes of residents who left long ago will be deleted within the week. Continue?",
    "Bewaard: {termijn}.": "Saved: {termijn}.",
    "Bewaartermijn zorgnotities": "Retention period for care notes",
    "Zolang een bewoner hier woont, blijven de zorgnotities bewaard. Na het vertrek worden ze na deze termijn automatisch gewist. De termijn geldt ook voor wie al vertrokken is, gerekend vanaf het vertrek.": "As long as a resident lives here, the care notes are kept. After they leave, the notes are deleted automatically after this period. The period also applies to those who have already left, counted from their departure.",
    "Bewaren na vertrek": "Keep after departure",
    "{termijn} na vertrek": "{termijn} after departure",
    "Met {termijn} verdwijnen vannacht {n} oudere overdracht. Doorgaan?": "With {termijn}, {n} older handover will disappear tonight. Continue?",
    "Met {termijn} verdwijnen vannacht {n} oudere overdrachten. Doorgaan?": "With {termijn}, {n} older handovers will disappear tonight. Continue?",
    "Bewaartermijn overdracht": "Retention period for handovers",
    "Een overdracht gaat over een dienst. Ze wordt elke nacht gewist zodra ze ouder is dan deze termijn. Wat blijvend belangrijk is over een bewoner, hoort in een zorgnotitie.": "A handover is about one shift. It is deleted every night once it is older than this period. Anything of lasting importance about a resident belongs in a care note.",
    "Met {termijn} verdwijnen vannacht {n} oudere teamberichten. Doorgaan?": "With {termijn}, {n} older team messages will disappear tonight. Continue?",
    "Bewaartermijn teamberichten": "Retention period for team messages",
    "Teamberichten worden elke nacht gewist zodra ze ouder zijn dan deze termijn.": "Team messages are deleted every night once they are older than this period.",
    "Als beheerder ziet {naam} geen inhoud over bewoners: afdelingen en toewijzingen vervallen.": "As an administrator, {naam} sees no content about residents: units and assignments will lapse.",
    "{naam} {rol} maken?": "Make {naam} {rol}?",
    "Rol van {naam}": "Role of {naam}",
    "{naam} uit dienst zetten? Toegang, afdelingen en toewijzingen stoppen meteen.": "Take {naam} off duty? Access, units and assignments stop immediately.",
    "Uit dienst": "Off duty",
    "Terug in dienst": "Back on duty",
    "Opnieuw gemaild, en 14 dagen langer geldig.": "Emailed again, and valid for 14 more days.",
    "14 dagen langer geldig. De mail kon niet vertrekken; stuur de link zelf.": "Valid for 14 more days. The email could not be sent; send the link yourself.",
    "Openstaande uitnodigingen": "Pending invitations",
    "Geen openstaande uitnodigingen.": "No pending invitations.",
    "Verlopen op {datum}": "Expired on {datum}",
    "Geldig tot {datum}": "Valid until {datum}",
    "Opnieuw sturen": "Send again",
    "De uitnodiging voor {email} intrekken? De link werkt dan niet meer.": "Revoke the invitation for {email}? The link will stop working.",
    "Intrekken": "Revoke",
    "Organisatie": "Organisation",
    "Naam": "Name",
    "Contact-e-mail": "Contact email",
    "Btw-nummer": "VAT number",
    "Bewaard.": "Saved.",
    "Nog geen afdelingen.": "No units yet.",
    "Afdeling {naam} archiveren? Medewerkers verliezen hun plaats op deze afdeling.": "Archive unit {naam}? Staff will lose their place in this unit.",
    "Nieuwe afdeling": "New unit",
    "De Eik": "The Oak",
    "Toevoegen": "Add",
    "Gearchiveerd ({n})": "Archived ({n})",
    "Terugzetten": "Restore",
    "Nieuwe naam voor {naam}": "New name for {naam}",
    "{naam} hernoemen": "Rename {naam}",
    "Hernoemen": "Rename",
    "{naam} archiveren": "Archive {naam}",
    "Archiveren": "Archive",
    "Bewoner": "Resident",
    "de bewoner": "the resident",
    "deze bewoner": "this resident",
    "Je bent niet toegewezen aan deze bewoner. Vraag het aan je coördinator.": "You are not assigned to this resident. Ask your coordinator.",
    "Niets gepland vandaag.": "Nothing planned today.",
    "gedaan": "done",
    "Contactpersonen": "Contacts",
    "Geen contactpersonen.": "No contacts.",
    "Bel {naam}": "Call {naam}",
    "Zorgnotities": "Care notes",
    "Correctie op:": "Correction of:",
    "Soort notitie": "Type of note",
    "Wat zag of deed je?": "What did you see or do?",
    "Ook voor de familie": "Also for the family",
    "Familie die mag meekijken en de bewoner zelf zien deze notitie. Anders blijft ze in het team.": "Family members who may view and the resident themselves will see this note. Otherwise it stays within the team.",
    "Bezig…": "Working…",
    "Correctie bewaren": "Save correction",
    "Notitie bewaren": "Save note",
    "Een notitie kan je niet aanpassen of wissen. Klopt er iets niet, voeg dan een correctie toe.": "A note cannot be changed or deleted. If something is wrong, add a correction.",
    "Nog geen zorgnotities.": "No care notes yet.",
    "Een collega": "A colleague",
    "ook familie": "family too",
    "gecorrigeerd": "corrected",
    "correctie": "correction",
    "Corrigeren": "Correct",
    "Je bent niet toegewezen aan {naam}. In een noodgeval kan je als team lead 4 uur meekijken: naam, voorkeuren, agenda, logboek, zorgnotities en contactpersonen. Geen dagboek, documenten of locatie.": "You are not assigned to {naam}. In an emergency, as team lead you can view for 4 hours: name, preferences, diary, log, care notes and contacts. No journal, documents or location.",
    "De familiebeheerder en de beheerder van je organisatie krijgen meteen bericht, met jouw reden.": "The family administrator and your organisation's administrator are notified immediately, with your reason.",
    "Elke keer dat je kijkt, wordt bijgehouden.": "Every time you look is recorded.",
    "Hoogstens 3 keer per 24 uur.": "At most 3 times per 24 hours.",
    "Waarom heb je dit nu nodig?": "Why do you need this now?",
    "Bijvoorbeeld: gevallen in de gang, familie niet bereikbaar, nachtdienst zoekt de contactpersoon.": "For example: fell in the corridor, family unreachable, night shift looking for the contact person.",
    "Genoeg uitleg.": "Enough explanation.",
    "Nog {n} teken.": "{n} more character.",
    "Nog {n} tekens.": "{n} more characters.",
    "Noodtoegang starten": "Start emergency access",
    "Noodtoegang tot {uur}": "Emergency access until {uur}",
    "Noodtoegang nu stoppen?": "Stop emergency access now?",
    "Nu stoppen": "Stop now",
    "Elke keer dat je deze pagina opent, wordt bijgehouden.": "Every time you open this page is recorded.",
    "Voorkeuren": "Preferences",
    "Geen voorkeuren genoteerd.": "No preferences noted.",
    "Agenda vandaag en morgen": "Diary today and tomorrow",
    "Niets gepland.": "Nothing planned.",
    "Laatste 24 uur": "Last 24 hours",
    "Niets genoteerd.": "Nothing noted.",
    "zorgnotitie": "care note",
    "logboek": "log",
    "Terug naar de bewoners": "Back to residents",
    "de noodtoegang loopt door tot je ze stopt of tot ze afloopt.": "emergency access continues until you stop it or it expires.",
    "Nog geen afdeling": "No unit yet",
    "Jouw bewoners en die van je afdeling.": "Your residents and those of your unit.",
    "De bewoners die jou zijn toegewezen.": "The residents assigned to you.",
    "Mijn bewoners": "My residents",
    "Je bent nog aan niemand toegewezen. Vraag het aan je coördinator of de beheerder van {organisatie}.": "You are not assigned to anyone yet. Ask your coordinator or the administrator of {organisatie}.",
    "je organisatie": "your organisation",
    "via je afdeling": "via your unit",
    "{n} vraag": "{n} question",
    "{n} vragen": "{n} questions",
    "Andere bewoners": "Other residents",
    "Je ziet hier alleen naam en kamer.": "You only see name and room here.",
    "In een noodgeval kan je als team lead 4 uur meekijken; de familie krijgt daar meteen bericht van.": "In an emergency, as team lead you can view for 4 hours; the family is notified immediately.",
    "Naam, afdeling of kamer": "Name, unit or room",
    "Geen andere bewoners gevonden.": "No other residents found.",
    "Even geduld…": "One moment…",
    "Een woonzorgcentrum registreren": "Register a care home",
    "Je wordt beheerder. Daarna nodig je medewerkers uit en krijg je een code voor de familie van je bewoners.": "You become the administrator. Then you invite your staff and get a code for your residents' families.",
    "Werk je in een woonzorgcentrum dat al LifeAngle gebruikt? Dan heb je een uitnodiging nodig van je beheerder.": "Do you work in a care home that already uses LifeAngle? Then you need an invitation from your administrator.",
    "Naam van het woonzorgcentrum": "Name of the care home",
    "WZC De Linde": "The Lindens Care Home",
    "Registreren": "Register",
    "Terug": "Back",
    "Deze link is onvolledig. Vraag een nieuwe uitnodiging.": "This link is incomplete. Ask for a new invitation.",
    "Je bent uitgenodigd": "You have been invited",
    "Om in LifeAngle Care te werken voor je woonzorgcentrum.": "To work in LifeAngle Care for your care home.",
    "Eerst even inloggen": "Sign in first",
    "Gebruik het e-mailadres waarop je de uitnodiging kreeg. Je krijgt een code van zes cijfers.": "Use the email address the invitation was sent to. You will receive a six-digit code.",
    "Deze uitnodiging bestaat niet.": "This invitation does not exist.",
    "{organisatie} nodigt je uit": "{organisatie} is inviting you",
    "Als {rol}.": "As {rol}.",
    "Deze uitnodiging is {status}. Vraag je beheerder om een nieuwe.": "This invitation is {status}. Ask your administrator for a new one.",
    "ingetrokken": "revoked",
    "al gebruikt": "already used",
    "verlopen": "expired",
    "Deze uitnodiging is voor": "This invitation is for",
    "Je bent nu ingelogd als": "You are currently signed in as",
    "Uitloggen en inloggen met {email}": "Sign out and sign in with {email}",
    "Uitnodiging aanvaarden": "Accept invitation",
    "Uitnodiging": "Invitation",
    "Uitnodiging van {organisatie}": "Invitation from {organisatie}",
    "Je bent uitgenodigd als {rol}. Werk je daar? Dan hoef je hieronder niets in te vullen.": "You have been invited as {rol}. Do you work there? Then you don't need to fill in anything below.",
    "Aanvaarden": "Accept",
    "Woonzorgcentrum": "Care home",
    "Uitnodiging van {organisatie} aanvaarden": "Accept invitation from {organisatie}",
    "Naar het woonzorgcentrum": "Go to the care home",
    "Verhuisd": "Moved",
    "Overleden": "Passed away",
    "Andere reden": "Other reason",
    "Verblijf beëindigen": "End stay",
    "Het verblijf van {naam} beëindigen": "End the stay of {naam}",
    "Het zorgteam verliest meteen de toegang en alle toewijzingen stoppen. De familie krijgt een melding en houdt al haar gegevens. Komt {naam} terug, dan koppelt de familie opnieuw met de koppelcode.": "The care team loses access immediately and all assignments stop. The family is notified and keeps all its data. If {naam} comes back, the family links up again with the link code.",
    "Reden": "Reason",
    "Open vragen van bewoners": "Open questions from residents",
    "Vragen van {naam}": "Questions from {naam}",
    "{n} nieuw": "{n} new",
    "Nog geen vragen. {naam} kan op de tablet iets vragen aan het zorgteam.": "No questions yet. {naam} can ask the care team something on the tablet.",
    "Antwoord": "Reply",
    "Antwoord aan {naam}": "Reply to {naam}",
    "Kort en eenvoudig, bv. 'Ik kom om 15 uur.'": "Short and simple, e.g. 'I'll come at 3 pm.'",
    "Antwoord sturen": "Send reply",
    "Gezien": "Seen",
    "Antwoorden": "Reply",
    "Zo praat je best met mij": "This is the best way to talk to me",
    "Als ik onrustig ben, helpt dit": "When I'm restless, this helps",
    "Hier raak ik van overstuur": "This upsets me",
    "Dit ben ik": "This is me",
    "De familie vulde nog niets in. Vraag hen om \"Dit ben ik\" aan te vullen in de app.": "The family has not filled anything in yet. Ask them to complete \"This is me\" in the app.",
    "Noem mij": "Call me",
    "Wie bij mij hoort": "My people",
    "Wat ik graag heb": "What I like",
    "Uit mijn verhaal": "From my story",
    "Ingevuld door {naam} en de familie.": "Filled in by {naam} and the family.",
    "Niemand volgt {naam}. Wijs een medewerker toe.": "Nobody is following {naam}. Assign a staff member.",
    "{naam} heeft nog geen afdeling.": "{naam} has no unit yet.",
    "{naam} heeft nog geen kamer.": "{naam} has no room yet.",
    "Afdeling {naam} heeft geen team lead.": "Unit {naam} has no team lead.",
    "{naam} staat op geen enkele afdeling.": "{naam} is not in any unit.",
    "De uitnodiging voor {email} verloopt binnenkort en is nog niet aanvaard.": "The invitation for {email} expires soon and has not been accepted yet.",
    "Observatie": "Observation",
    "Zorg": "Care",
    "Maaltijd": "Meal",
    "Slaap": "Sleep",
    "Stemming": "Mood",
    "Incident": "Incident",
    "Overig": "Other",
    "Vroege dienst": "Early shift",
    "Late dienst": "Late shift",
    "Nachtdienst": "Night shift",
    "Alleen de beheerder kan een afdeling hernoemen.": "Only the administrator can rename a unit.",
    "Alleen de beheerder kan de gegevens aanpassen.": "Only the administrator can change the details.",
    "1 jaar": "1 year",
    "{n} jaar": "{n} years",
    "{n} maanden": "{n} months",
    "Alleen de beheerder kan dit aanpassen.": "Only the administrator can change this.",
    "Deze code kennen we niet. Kijk ze na of vraag ze opnieuw aan het woonzorgcentrum.": "We don't recognise this code. Check it or ask the care home for it again.",
    "1 week": "1 week",
    "2 weken": "2 weeks",
    "{n} dagen": "{n} days",
  },
} satisfies Vertaling
