import type { Vertaling } from '../uiTaal'

/** Care: zorgschermen, kamers, weekplanning, rapporten, uitstap, spullen, nieuws en prijzen. */
export default {
  fr: {
    "ma": "lu",
    "di": "ma",
    "wo": "me",
    "do": "je",
    "vr": "ve",
    "za": "sa",
    "zo": "di",
    "elke dag": "tous les jours",
    "weekdagen": "en semaine",
    "weekend": "le week-end",
    "Even geduld…": "Un instant…",
    "Vandaag": "Aujourd'hui",
    "Bewoners": "Résidents",
    "Overdracht": "Transmission",
    "Team": "Équipe",
    "Activiteiten": "Activités",
    "Weekplanning": "Planning de la semaine",
    "Kamers": "Chambres",
    "Nieuws": "Actualités",
    "Rapporten": "Rapports",
    "Beheer": "Gestion",
    "Dagelijks": "Au quotidien",
    "Planning": "Planning",
    "Families": "Familles",
    "team lead": "chef d'équipe",
    "Organisatie": "Organisation",
    "Naar mijn familie": "Vers ma famille",
    "Mijn account en wachtwoord": "Mon compte et mot de passe",
    "Uitloggen": "Se déconnecter",
    "Hoofdnavigatie": "Navigation principale",
    "open vraag": "question ouverte",
    "open vragen": "questions ouvertes",
    "Meer": "Plus",
    "Wat er gepland is in het woonzorgcentrum. Het staat vanzelf op de tablets van de bewoners.": "Ce qui est prévu dans la maison de repos. Cela apparaît automatiquement sur les tablettes des résidents.",
    "Nieuws voor de families": "Actualités pour les familles",
    "Gepland": "Prévu",
    "Er is nog niets gepland.": "Rien n'est encore prévu.",
    "geannuleerd": "annulé",
    "Nieuwe activiteit": "Nouvelle activité",
    "Wat": "Quoi",
    "Samen zingen": "Chanter ensemble",
    "Wanneer": "Quand",
    "Waar": "Où",
    "Cafetaria": "Cafétéria",
    "Voor": "Pour",
    "Het hele woonzorgcentrum": "Toute la maison de repos",
    "Afdeling {naam}": "Unité {naam}",
    "Bezig…": "En cours…",
    "Activiteit plannen": "Planifier une activité",
    "ingeschreven": "inscrit(e)",
    "aanwezig": "présent(e)",
    "afwezig": "absent(e)",
    "Nog niemand ingeschreven.": "Personne n'est encore inscrit.",
    "Bewoner": "Résident(e)",
    "Aanwezig": "Présent(e)",
    "Afwezig": "Absent(e)",
    "Iemand inschrijven": "Inscrire quelqu'un",
    "Kies een bewoner": "Choisissez un résident",
    "Inschrijven": "Inscrire",
    "Was erbij": "Était présent(e)",
    "\"{titel}\" annuleren?": "Annuler « {titel} » ?",
    "Activiteit annuleren": "Annuler l'activité",
    "Maaltijd": "Repas",
    "Rust": "Repos",
    "Activiteit": "Activité",
    "Verzorging": "Soins",
    "Andere": "Autre",
    "De vaste dag": "La journée type",
    "Wat elke dag terugkomt. Het staat vanzelf op de tablet van elke bewoner van die afdeling, en bij haar familie.": "Ce qui revient chaque jour. Cela apparaît automatiquement sur la tablette de chaque résident de cette unité, et chez sa famille.",
    "Nog geen vaste dag ingevuld.": "Aucune journée type n'a encore été remplie.",
    "staat uit": "désactivé",
    "Zet uit": "Désactiver",
    "Zet aan": "Activer",
    "\"{titel}\" wissen?": "Supprimer « {titel} » ?",
    "{titel} wissen": "Supprimer {titel}",
    "Iets toevoegen": "Ajouter quelque chose",
    "Middagmaal": "Repas de midi",
    "Soort": "Type",
    "Van": "De",
    "Tot (mag leeg)": "Jusqu'à (facultatif)",
    "Op welke dagen": "Quels jours",
    "Toevoegen aan de vaste dag": "Ajouter à la journée type",
    "Eén bericht, bij elke familie in de app. Met de naam van het woonzorgcentrum erbij.": "Un seul message, chez chaque famille dans l'app. Avec le nom de la maison de repos.",
    "Verstuurd": "Envoyé",
    "Nog geen nieuws verstuurd.": "Aucune actualité envoyée pour l'instant.",
    "Aan de families van afdeling {naam}": "Aux familles de l'unité {naam}",
    "Aan alle families": "À toutes les familles",
    "\"{titel}\" wissen? De families zien het dan niet meer.": "Supprimer « {titel} » ? Les familles ne le verront plus.",
    "Nieuws blijft 180 dagen staan.": "Les actualités restent visibles 180 jours.",
    "Nieuw bericht": "Nouveau message",
    "Versturen naar de families van deze afdeling?": "Envoyer aux familles de cette unité ?",
    "Versturen naar alle families?": "Envoyer à toutes les familles ?",
    "Aan wie": "À qui",
    "Alle families": "Toutes les familles",
    "De families van afdeling {naam}": "Les familles de l'unité {naam}",
    "Titel": "Titre",
    "Zomerfeest zaterdag": "Fête d'été samedi",
    "Bericht": "Message",
    "Zaterdag om 14 uur in de tuin. Iedereen welkom.": "Samedi à 14 h dans le jardin. Tout le monde est bienvenu.",
    "Schrijf hier nooit iets over één bewoner. Dit lezen alle families van die afdeling.": "N'écrivez jamais ici à propos d'un seul résident. Toutes les familles de cette unité le liront.",
    "Schrijf hier nooit iets over één bewoner. Dit lezen alle families.": "N'écrivez jamais ici à propos d'un seul résident. Toutes les familles le liront.",
    "Versturen": "Envoyer",
    "Je staat nog op geen afdeling. De beheerder van {org} zet je op een afdeling.": "Vous n'êtes encore affecté(e) à aucune unité. L'administrateur de {org} vous affectera à une unité.",
    "Wat de volgende dienst moet weten. Een overdracht wordt na een tijd automatisch gewist; wat blijvend belangrijk is, schrijf je in een zorgnotitie.": "Ce que l'équipe suivante doit savoir. Une transmission est effacée automatiquement après un certain temps ; ce qui reste important, notez-le dans une note de soins.",
    "Afdeling": "Unité",
    "Nieuwe overdracht · {afdeling}": "Nouvelle transmission · {afdeling}",
    "Dienst": "Service",
    "Wat moet de volgende dienst weten?": "Que doit savoir l'équipe suivante ?",
    "Overdracht bewaren": "Enregistrer la transmission",
    "De laatste dagen": "Ces derniers jours",
    "Nog geen overdracht de laatste dagen.": "Aucune transmission ces derniers jours.",
    "Een collega": "Un(e) collègue",
    "Gisteren": "Hier",
    "Korte berichten voor je afdeling. Wat over een bewoner blijvend belangrijk is, schrijf je in een zorgnotitie.": "De courts messages pour votre unité. Ce qui reste important à propos d'un résident, notez-le dans une note de soins.",
    "Berichten van {afdeling}": "Messages de {afdeling}",
    "Nog geen berichten op {afdeling}.": "Pas encore de messages dans {afdeling}.",
    "wissen": "supprimer",
    "Bericht aan {afdeling}": "Message à {afdeling}",
    "Bericht aan je afdeling": "Message à votre unité",
    "Goedemorgen": "Bonjour",
    "Goedemiddag": "Bon après-midi",
    "Goedenavond": "Bonsoir",
    "{n} afdeling": "{n} unité",
    "{n} afdelingen": "{n} unités",
    "Vrije bedden": "Lits libres",
    "van {n} bedden": "sur {n} lits",
    "kamers nog niet ingevoerd": "chambres pas encore encodées",
    "Vandaag gepland": "Prévu aujourd'hui",
    "straks: {tijd} {titel}": "bientôt : {tijd} {titel}",
    "activiteiten": "activités",
    "Nieuws verstuurd": "Actualités envoyées",
    "laatste 180 dagen": "180 derniers jours",
    "Open vragen": "Questions ouvertes",
    "van je bewoners": "de vos résidents",
    "Nieuws versturen": "Envoyer une actualité",
    "Vandaag in het huis": "Aujourd'hui dans la maison",
    "Er staat vandaag niets gepland.": "Rien n'est prévu aujourd'hui.",
    "Vul de vaste dag in": "Remplissez la journée type",
    "hele huis": "toute la maison",
    "gaat niet door": "n'a pas lieu",
    "straks": "bientôt",
    "Laatste nieuws": "Dernières actualités",
    "Nog geen nieuws aan de families.": "Pas encore d'actualités pour les familles.",
    "Snel naar": "Accès rapide",
    "Bedden": "Lits",
    "Zonder kamer": "Sans chambre",
    "Kamers en bezetting": "Chambres et occupation",
    "Wie waar woont en wat er vrij is, per afdeling.": "Qui habite où et ce qui est libre, par unité.",
    "Er zijn nog geen kamers ingevoerd.": "Aucune chambre n'a encore été encodée.",
    "Voeg ze hieronder toe, bijvoorbeeld \"101-120\" in één keer.": "Ajoutez-les ci-dessous, par exemple « 101-120 » en une fois.",
    "Vraag het aan de beheerder of een coördinator.": "Demandez-le à l'administrateur ou à un coordinateur.",
    "Maak eerst afdelingen aan bij": "Créez d'abord des unités dans",
    "{n} bewoner": "{n} résident",
    "{n} bewoners": "{n} résidents",
    "{vrij} vrij van {bedden}": "{vrij} libre(s) sur {bedden}",
    "Nog geen kamers op deze afdeling.": "Pas encore de chambres dans cette unité.",
    "Nog zonder kamer": "Encore sans chambre",
    "{n} bed(den)": "{n} lit(s)",
    "buiten gebruik": "hors service",
    "vrij": "libre",
    "{n} bed vrij": "{n} lit libre",
    "bezet": "occupée",
    "Bewoner plaatsen": "Placer un résident",
    "Buiten gebruik": "Mettre hors service",
    "In gebruik nemen": "Remettre en service",
    "Kamer {naam} wissen?": "Supprimer la chambre {naam} ?",
    "Kamer {naam} wissen": "Supprimer la chambre {naam}",
    "kamer \"{kamer}\" bestaat niet op deze afdeling": "la chambre « {kamer} » n'existe pas dans cette unité",
    "Kamer voor {naam}": "Chambre pour {naam}",
    "Kies een kamer": "Choisissez une chambre",
    "Toewijzen": "Attribuer",
    "Kamers toevoegen": "Ajouter des chambres",
    "101-120 of 12, 14, 16": "101-120 ou 12, 14, 16",
    "Bedden per kamer": "Lits par chambre",
    "{n} kamers toevoegen": "Ajouter {n} chambres",
    "Kamer toevoegen": "Ajouter une chambre",
    "Maandag": "Lundi",
    "Dinsdag": "Mardi",
    "Woensdag": "Mercredi",
    "Donderdag": "Jeudi",
    "Vrijdag": "Vendredi",
    "Zaterdag": "Samedi",
    "Zondag": "Dimanche",
    "De vaste dag en de activiteiten van het huis. Wat hier staat, staat ook op de tablets.": "La journée type et les activités de la maison. Ce qui figure ici apparaît aussi sur les tablettes.",
    "Afdrukken": "Imprimer",
    "Vorige week": "Semaine précédente",
    "Deze week": "Cette semaine",
    "Volgende week": "Semaine suivante",
    "Alle afdelingen": "Toutes les unités",
    "afdeling {naam}": "unité {naam}",
    "week van {datum}": "semaine du {datum}",
    "Er staat deze week nog niets. Vul bij Activiteiten de vaste dag in (ontbijt, middagmaal, rust) en plan activiteiten.": "Rien n'est encore prévu cette semaine. Remplissez la journée type sous Activités (petit-déjeuner, repas de midi, repos) et planifiez des activités.",
    "vandaag": "aujourd'hui",
    "Niets gepland": "Rien de prévu",
    "vaste dag": "journée type",
    "activiteit": "activité",
    "Deze maand": "Ce mois-ci",
    "Vorige maand": "Mois dernier",
    "Laatste 30 dagen": "30 derniers jours",
    "Dit jaar": "Cette année",
    "Wat er in het huis gebeurt, in aantallen.": "Ce qui se passe dans la maison, en chiffres.",
    "Download (CSV)": "Télécharger (CSV)",
    "Zelf kiezen": "Choisir soi-même",
    "Tot en met": "Jusqu'au",
    "{van} tot en met {tot}": "du {van} au {tot} inclus",
    "De rapporten zijn er na de update van de database (83).": "Les rapports seront disponibles après la mise à jour de la base de données (83).",
    "Pas vanaf 5 bewoners en 28 dagen": "Uniquement à partir de 5 résidents et 28 jours",
    "Per afdeling": "Par unité",
    "Aanwezigheden": "Présences",
    "Alleen aantallen, nooit namen of iets over één bewoner. Bezoeken en uitstappen tellen pas mee als er in die periode minstens vijf bewoners waren, over minstens 28 dagen.": "Uniquement des chiffres, jamais de noms ni d'informations sur un seul résident. Les visites et les sorties ne sont comptées que s'il y avait au moins cinq résidents pendant cette période, sur au moins 28 jours.",
    "Uitstap vandaag": "Sortie aujourd'hui",
    "met {wie}": "avec {wie}",
    "nog niet terug": "pas encore rentré(e)",
    "vertrokken": "parti(e)",
    "gepland": "prévu",
    "Vertrokken": "Parti(e)",
    "Is terug": "Est rentré(e)",
    "Kwijt op de afdeling": "Perdu dans l'unité",
    "van {bewoner}": "de {bewoner}",
    "kamer {kamer}": "chambre {kamer}",
    "hoort: {waar}": "se range : {waar}",
    "Gevonden": "Retrouvé",
    "Er ging iets mis. Probeer het opnieuw.": "Un problème est survenu. Veuillez réessayer.",
    "Bezig met laden…": "Chargement…",
    "Nu in het woonzorgcentrum": "Actuellement dans la maison de repos",
    "Opnames": "Admissions",
    "Nieuwe bewoners in deze periode": "Nouveaux résidents pendant cette période",
    "Vertrekken": "Départs",
    "Verblijven die afliepen": "Séjours terminés",
    "Gepland, zonder de geannuleerde": "Prévues, hors annulations",
    "Keer dat een bewoner erbij was": "Nombre de fois qu'un résident était présent",
    "Deelnemers": "Participants",
    "Verschillende bewoners die meededen": "Résidents différents ayant participé",
    "Bezoeken": "Visites",
    "Vastgelegd in \"Wie was er hier?\"": "Enregistrées dans « Qui est passé ? »",
    "Uitstappen": "Sorties",
    "Met de familie, echt vertrokken": "Avec la famille, réellement parti(e)",
    "Nieuwsberichten": "Actualités",
    "Verstuurd aan de families": "Envoyées aux familles",
    "Periode": "Période",
    "Cijfer": "Indicateur",
    "Waarde": "Valeur",
    "Totaal": "Total",
    "niet getoond (minder dan 5 bewoners of korter dan 28 dagen)": "non affiché (moins de 5 résidents ou moins de 28 jours)",
    "Alleen de beheerder of een coördinator past kamers aan.": "Seul l'administrateur ou un coordinateur peut modifier les chambres.",
    "Alleen de beheerder of een coördinator wist kamers.": "Seul l'administrateur ou un coordinateur peut supprimer des chambres.",
    "Zonder afdeling": "Sans unité",
    "Bril": "Lunettes",
    "Gebit": "Dentier",
    "Hoorapparaat": "Appareil auditif",
    "Kleding": "Vêtements",
    "Sieraad": "Bijou",
    "Hulpmiddel": "Aide technique",
    "Dit kan je niet wissen.": "Vous ne pouvez pas supprimer ceci.",
    "net gemeld": "signalé à l'instant",
    "sinds {n} uur": "depuis {n} h",
    "sinds gisteren": "depuis hier",
    "sinds {n} dagen": "depuis {n} jours",
    "Dit bericht kan je niet wissen.": "Vous ne pouvez pas supprimer ce message.",
    "Van {van} · afdeling {afdeling}": "De {van} · unité {afdeling}",
    "Van {van}": "De {van}",
    "terug": "rentré(e)",
    "Uitstap": "Sortie",
    "Neem je {naam} mee? Meld het hier, dan weet het zorgteam waar {naam} is en zegt de tablet wie er komt.": "Vous emmenez {naam} ? Signalez-le ici : l'équipe soignante saura où se trouve {naam} et la tablette dira qui vient.",
    "Wie {naam} meeneemt, en wanneer ze terug is.": "Qui emmène {naam}, et quand elle rentre.",
    "Uitstap melden": "Signaler une sortie",
    "Met {wie}": "Avec {wie}",
    "Deze uitstap annuleren?": "Annuler cette sortie ?",
    "Annuleren": "Annuler",
    "Terug moet na het vertrek liggen.": "Le retour doit être après le départ.",
    "Met wie": "Avec qui",
    "Els": "Els",
    "Vertrek": "Départ",
    "Terug": "Retour",
    "Waar naartoe (mag leeg)": "Où (facultatif)",
    "Naar de markt en daarna bij ons eten": "Au marché, puis manger chez nous",
    "Melden": "Signaler",
    "Spullen van {naam}": "Affaires de {naam}",
    "{n} kwijt": "{n} perdu(s)",
    "Bril, gebit, hoorapparaat, gemerkte kleding: met een foto en waar het hoort. Raakt iets kwijt, dan zoekt de hele afdeling mee.": "Lunettes, dentier, appareil auditif, vêtements marqués : avec une photo et l'endroit où ils se rangent. Si quelque chose se perd, toute l'unité aide à chercher.",
    "Minder tonen": "Afficher moins",
    "Alle {n} spullen": "Toutes les {n} affaires",
    "Hoort: {waar}": "Se range : {waar}",
    "Kwijt": "Perdu",
    "Andere foto": "Autre photo",
    "Foto": "Photo",
    "Leesbril": "Lunettes de lecture",
    "Herkenbaar aan (mag leeg)": "Signe distinctif (facultatif)",
    "Rood montuur, naam binnenin": "Monture rouge, nom à l'intérieur",
    "Waar het hoort (mag leeg)": "Où il se range (facultatif)",
    "Op het nachtkastje": "Sur la table de nuit",
    "Bewaren": "Enregistrer",
    "{naam} ingeschreven": "{naam} inscrit(e)",
    "{naam} was erbij": "{naam} était présent(e)",
    "{naam} was er niet bij": "{naam} n'était pas présent(e)",
    "Vandaag in het woonzorgcentrum": "Aujourd'hui à la maison de repos",
    "Gepland door het woonzorgcentrum.": "Prévu par la maison de repos.",
    "Nieuws van {van}": "Actualités de {van}",
    "nieuw": "nouveau",
    "Alle {n} berichten": "Tous les {n} messages",
    "Systeemcontrole": "Contrôle du système",
    "Draai in Supabase de update": "Exécutez dans Supabase la mise à jour",
    "dan zie je hier welke andere updates nog ontbreken.": "vous verrez alors ici quelles autres mises à jour manquent encore.",
    "De controle lukte nu niet. Probeer het later opnieuw.": "Le contrôle n'a pas abouti. Réessayez plus tard.",
    "Alle {n} updates van de database staan erin.": "Les {n} mises à jour de la base de données sont toutes installées.",
    "Eén update ontbreekt.": "Il manque une mise à jour.",
    "{n} updates ontbreken.": "Il manque {n} mises à jour.",
    "Draai ze in Supabase, in deze volgorde. Tot dan werken deze onderdelen niet of maar half.": "Exécutez-les dans Supabase, dans cet ordre. D'ici là, ces fonctions ne marchent pas ou seulement en partie.",
    "Proefperiode": "Période d'essai",
    "Pilot": "Projet pilote",
    "Actief": "Actif",
    "Betaling openstaand": "Paiement en attente",
    "Gepauzeerd": "En pause",
    "Stopgezet": "Arrêté",
    "Jouw abonnement": "Votre abonnement",
    "tot {datum}": "jusqu'au {datum}",
    "Je gebruikt alles van LifeAngle, en er wordt nog niets aangerekend.": "Vous utilisez tout LifeAngle, et rien n'est encore facturé.",
    "Met {n} bewoner zou Care {bedrag} per maand kosten": "Avec {n} résident, Care coûterait {bedrag} par mois",
    "Met {n} bewoners zou Care {bedrag} per maand kosten": "Avec {n} résidents, Care coûterait {bedrag} par mois",
    "(excl. btw)": "(hors TVA)",
    "Bekijk de prijzen": "Voir les tarifs",
    "Wat kost LifeAngle?": "Combien coûte LifeAngle ?",
    "Eén prijs per huishouden, met zoveel familieleden als je wil. Voor een woonzorgcentrum: per bewoner die er echt verblijft.": "Un seul prix par foyer, avec autant de membres de la famille que vous le souhaitez. Pour une maison de repos : par résident qui y séjourne réellement.",
    "Prijzen onder voorbehoud. Er wordt nu nog niets aangerekend.": "Tarifs sous réserve. Rien n'est encore facturé pour l'instant.",
    "Voor wie": "Pour qui",
    "Voor families": "Pour les familles",
    "Voor woonzorgcentra": "Pour les maisons de repos",
    "Per jaar betalen": "Payer par an",
    "De prijzen zijn nog niet ingesteld.": "Les tarifs ne sont pas encore définis.",
    "Goed om te weten": "Bon à savoir",
    "Alle familieleden, de tablet van de persoon en zorgverleners: inbegrepen, zonder meerprijs.": "Tous les membres de la famille, la tablette de la personne et les soignants : inclus, sans supplément.",
    "Verblijft iemand in een woonzorgcentrum dat LifeAngle Care gebruikt, dan betaalt de familie niets extra.": "Si quelqu'un séjourne dans une maison de repos qui utilise LifeAngle Care, la famille ne paie rien de plus.",
    "Opzeggen kan altijd. Je gegevens kan je eerst downloaden.": "Vous pouvez résilier à tout moment. Vous pouvez d'abord télécharger vos données.",
    "Woonzorgcentrum?": "Maison de repos ?",
    "Je betaalt alleen voor bewoners die die maand echt verblijven, niet voor bedden of medewerkers. Begin met een pilot op één afdeling.": "Vous ne payez que pour les résidents qui séjournent réellement ce mois-là, pas pour les lits ni le personnel. Commencez par un projet pilote dans une unité.",
    "Een woonzorgcentrum registreren": "Inscrire une maison de repos",
    "per bewoner per maand": "par résident par mois",
    "per jaar": "par an",
    "per maand": "par mois",
    "Gratis": "Gratuit",
    "btw inbegrepen": "TVA comprise",
    "excl. btw": "hors TVA",
    "minimum {bedrag} per maand": "minimum {bedrag} par mois",
    "{n} maand gratis": "{n} mois gratuit",
    "{n} maanden gratis": "{n} mois gratuits",
    "{n} dagen gratis proberen": "{n} jours d'essai gratuit",
    "Wat zit erin": "Ce qui est inclus",
    // Prijzen bij de livegang (86) en teksten uit de database
    "Eén prijs per huishouden, met zoveel familieleden als je wil. Voor een woonzorgcentrum maken we een voorstel op maat.": "Un seul prix par foyer, avec autant de membres de la famille que vous le souhaitez. Pour une maison de repos, nous faisons une proposition sur mesure.",
    "We maken een voorstel op maat, op basis van het aantal bewoners. Begin met een pilot op één afdeling.": "Nous faisons une proposition sur mesure, selon le nombre de résidents. Commencez par un projet pilote dans une unité.",
    "Prijsaanvraag LifeAngle Care": "Demande de prix LifeAngle Care",
    "Vraag een prijs aan": "Demander un prix",
    "Prijs op aanvraag": "Prix sur demande",
    "Daarna {bedrag} per jaar. Opzeggen kan altijd.": "Ensuite {bedrag} par an. Résiliable à tout moment.",
    "Daarna {bedrag} per maand. Opzeggen kan altijd.": "Ensuite {bedrag} par mois. Résiliable à tout moment.",
    "Home gratis": "Home gratuit",
    "Home met AI": "Home avec IA",
    "Care met AI": "Care avec IA",
    "Alles voor thuis: de dag, familie, medicatie, routines, Home Memory, documenten en de spraakassistent.": "Tout pour la maison : la journée, la famille, les médicaments, les routines, Home Memory, les documents et l'assistant vocal.",
    "Voor woonzorgcentra: zorgnotities, overdracht, team, activiteiten, kamers en beheer.": "Pour les maisons de repos : notes de soins, transmissions, équipe, activités, chambres et gestion.",
    "De dag, berichten, familie en herinneringen. Voor altijd gratis.": "La journée, les messages, la famille et les souvenirs. Gratuit pour toujours.",
    "Alles voor thuis: medicatie, routines, Home Memory, familieportaal en analyse.": "Tout pour la maison : médicaments, routines, Home Memory, portail familial et analyse.",
    "Home, plus de spraakassistent die antwoordt uit jullie eigen gegevens.": "Home, plus l'assistant vocal qui répond à partir de vos propres données.",
    "Voor woonzorgcentra: zorgnotities, overdracht, team, activiteiten en beheer.": "Pour les maisons de repos : notes de soins, transmissions, équipe, activités et gestion.",
    "Care, plus de spraakassistent voor bewoners en medewerkers.": "Care, plus l'assistant vocal pour les résidents et le personnel.",
    "Agenda": "Agenda",
    "Contacten": "Contacts",
    "Verhalen en dagboek": "Histoires et journal",
    "Herinneringen en foto's": "Souvenirs et photos",
    "Spraak zonder AI": "Voix sans IA",
    "Radio": "Radio",
    "Videobellen": "Appels vidéo",
    "Familieportaal": "Portail familial",
    "Spraak met AI": "Voix avec IA",
    "Spraak naar tekst": "Voix en texte",
    "Vragen uit eigen gegevens": "Questions sur vos propres données",
    "Teamberichten": "Messages d'équipe",
    "Overzicht organisatie": "Aperçu de l'organisation",
    "Rapporten met rendement": "Rapports avec rendement",
    "Companion-toestel": "Appareil Companion",
    "Toestellen per kamer": "Appareils par chambre",
    "Koppeling met het EPD": "Liaison avec le dossier patient informatisé",
  },
  en: {
    "ma": "Mon",
    "di": "Tue",
    "wo": "Wed",
    "do": "Thu",
    "vr": "Fri",
    "za": "Sat",
    "zo": "Sun",
    "elke dag": "every day",
    "weekdagen": "weekdays",
    "weekend": "weekends",
    "Even geduld…": "One moment…",
    "Vandaag": "Today",
    "Bewoners": "Residents",
    "Overdracht": "Handover",
    "Team": "Team",
    "Activiteiten": "Activities",
    "Weekplanning": "Weekly schedule",
    "Kamers": "Rooms",
    "Nieuws": "News",
    "Rapporten": "Reports",
    "Beheer": "Management",
    "Dagelijks": "Daily",
    "Planning": "Planning",
    "Families": "Families",
    "team lead": "team lead",
    "Organisatie": "Organisation",
    "Naar mijn familie": "Go to my family",
    "Mijn account en wachtwoord": "My account and password",
    "Uitloggen": "Sign out",
    "Hoofdnavigatie": "Main navigation",
    "open vraag": "open question",
    "open vragen": "open questions",
    "Meer": "More",
    "Wat er gepland is in het woonzorgcentrum. Het staat vanzelf op de tablets van de bewoners.": "What is planned in the care home. It appears automatically on the residents' tablets.",
    "Nieuws voor de families": "News for families",
    "Gepland": "Planned",
    "Er is nog niets gepland.": "Nothing is planned yet.",
    "geannuleerd": "cancelled",
    "Nieuwe activiteit": "New activity",
    "Wat": "What",
    "Samen zingen": "Singing together",
    "Wanneer": "When",
    "Waar": "Where",
    "Cafetaria": "Cafeteria",
    "Voor": "For",
    "Het hele woonzorgcentrum": "The whole care home",
    "Afdeling {naam}": "Unit {naam}",
    "Bezig…": "Working…",
    "Activiteit plannen": "Plan an activity",
    "ingeschreven": "signed up",
    "aanwezig": "present",
    "afwezig": "absent",
    "Nog niemand ingeschreven.": "No one has signed up yet.",
    "Bewoner": "Resident",
    "Aanwezig": "Present",
    "Afwezig": "Absent",
    "Iemand inschrijven": "Sign someone up",
    "Kies een bewoner": "Choose a resident",
    "Inschrijven": "Sign up",
    "Was erbij": "Was there",
    "\"{titel}\" annuleren?": "Cancel \"{titel}\"?",
    "Activiteit annuleren": "Cancel activity",
    "Maaltijd": "Meal",
    "Rust": "Rest",
    "Activiteit": "Activity",
    "Verzorging": "Care",
    "Andere": "Other",
    "De vaste dag": "The daily routine",
    "Wat elke dag terugkomt. Het staat vanzelf op de tablet van elke bewoner van die afdeling, en bij haar familie.": "What comes back every day. It appears automatically on the tablet of every resident in that unit, and for their family.",
    "Nog geen vaste dag ingevuld.": "No daily routine filled in yet.",
    "staat uit": "switched off",
    "Zet uit": "Switch off",
    "Zet aan": "Switch on",
    "\"{titel}\" wissen?": "Delete \"{titel}\"?",
    "{titel} wissen": "Delete {titel}",
    "Iets toevoegen": "Add something",
    "Middagmaal": "Lunch",
    "Soort": "Type",
    "Van": "From",
    "Tot (mag leeg)": "Until (optional)",
    "Op welke dagen": "On which days",
    "Toevoegen aan de vaste dag": "Add to the daily routine",
    "Eén bericht, bij elke familie in de app. Met de naam van het woonzorgcentrum erbij.": "One message, to every family in the app. With the name of the care home.",
    "Verstuurd": "Sent",
    "Nog geen nieuws verstuurd.": "No news sent yet.",
    "Aan de families van afdeling {naam}": "To the families of unit {naam}",
    "Aan alle families": "To all families",
    "\"{titel}\" wissen? De families zien het dan niet meer.": "Delete \"{titel}\"? Families will no longer see it.",
    "Nieuws blijft 180 dagen staan.": "News stays visible for 180 days.",
    "Nieuw bericht": "New message",
    "Versturen naar de families van deze afdeling?": "Send to the families of this unit?",
    "Versturen naar alle families?": "Send to all families?",
    "Aan wie": "To",
    "Alle families": "All families",
    "De families van afdeling {naam}": "The families of unit {naam}",
    "Titel": "Title",
    "Zomerfeest zaterdag": "Summer party on Saturday",
    "Bericht": "Message",
    "Zaterdag om 14 uur in de tuin. Iedereen welkom.": "Saturday at 2 pm in the garden. Everyone welcome.",
    "Schrijf hier nooit iets over één bewoner. Dit lezen alle families van die afdeling.": "Never write about an individual resident here. All families of that unit will read this.",
    "Schrijf hier nooit iets over één bewoner. Dit lezen alle families.": "Never write about an individual resident here. All families will read this.",
    "Versturen": "Send",
    "Je staat nog op geen afdeling. De beheerder van {org} zet je op een afdeling.": "You are not assigned to a unit yet. The administrator of {org} will assign you to one.",
    "Wat de volgende dienst moet weten. Een overdracht wordt na een tijd automatisch gewist; wat blijvend belangrijk is, schrijf je in een zorgnotitie.": "What the next shift needs to know. A handover is deleted automatically after a while; anything of lasting importance goes in a care note.",
    "Afdeling": "Unit",
    "Nieuwe overdracht · {afdeling}": "New handover · {afdeling}",
    "Dienst": "Shift",
    "Wat moet de volgende dienst weten?": "What does the next shift need to know?",
    "Overdracht bewaren": "Save handover",
    "De laatste dagen": "The last few days",
    "Nog geen overdracht de laatste dagen.": "No handovers in the last few days.",
    "Een collega": "A colleague",
    "Gisteren": "Yesterday",
    "Korte berichten voor je afdeling. Wat over een bewoner blijvend belangrijk is, schrijf je in een zorgnotitie.": "Short messages for your unit. Anything of lasting importance about a resident goes in a care note.",
    "Berichten van {afdeling}": "Messages from {afdeling}",
    "Nog geen berichten op {afdeling}.": "No messages in {afdeling} yet.",
    "wissen": "delete",
    "Bericht aan {afdeling}": "Message to {afdeling}",
    "Bericht aan je afdeling": "Message to your unit",
    "Goedemorgen": "Good morning",
    "Goedemiddag": "Good afternoon",
    "Goedenavond": "Good evening",
    "{n} afdeling": "{n} unit",
    "{n} afdelingen": "{n} units",
    "Vrije bedden": "Free beds",
    "van {n} bedden": "of {n} beds",
    "kamers nog niet ingevoerd": "rooms not entered yet",
    "Vandaag gepland": "Planned today",
    "straks: {tijd} {titel}": "next: {tijd} {titel}",
    "activiteiten": "activities",
    "Nieuws verstuurd": "News sent",
    "laatste 180 dagen": "last 180 days",
    "Open vragen": "Open questions",
    "van je bewoners": "from your residents",
    "Nieuws versturen": "Send news",
    "Vandaag in het huis": "Today in the home",
    "Er staat vandaag niets gepland.": "Nothing is planned today.",
    "Vul de vaste dag in": "Fill in the daily routine",
    "hele huis": "whole home",
    "gaat niet door": "cancelled",
    "straks": "next",
    "Laatste nieuws": "Latest news",
    "Nog geen nieuws aan de families.": "No news for families yet.",
    "Snel naar": "Quick links",
    "Bedden": "Beds",
    "Zonder kamer": "Without a room",
    "Kamers en bezetting": "Rooms and occupancy",
    "Wie waar woont en wat er vrij is, per afdeling.": "Who lives where and what is free, per unit.",
    "Er zijn nog geen kamers ingevoerd.": "No rooms have been entered yet.",
    "Voeg ze hieronder toe, bijvoorbeeld \"101-120\" in één keer.": "Add them below, for example \"101-120\" in one go.",
    "Vraag het aan de beheerder of een coördinator.": "Ask the administrator or a coordinator.",
    "Maak eerst afdelingen aan bij": "First create units under",
    "{n} bewoner": "{n} resident",
    "{n} bewoners": "{n} residents",
    "{vrij} vrij van {bedden}": "{vrij} free of {bedden}",
    "Nog geen kamers op deze afdeling.": "No rooms in this unit yet.",
    "Nog zonder kamer": "Still without a room",
    "{n} bed(den)": "{n} bed(s)",
    "buiten gebruik": "out of use",
    "vrij": "free",
    "{n} bed vrij": "{n} bed free",
    "bezet": "occupied",
    "Bewoner plaatsen": "Place a resident",
    "Buiten gebruik": "Take out of use",
    "In gebruik nemen": "Put into use",
    "Kamer {naam} wissen?": "Delete room {naam}?",
    "Kamer {naam} wissen": "Delete room {naam}",
    "kamer \"{kamer}\" bestaat niet op deze afdeling": "room \"{kamer}\" does not exist in this unit",
    "Kamer voor {naam}": "Room for {naam}",
    "Kies een kamer": "Choose a room",
    "Toewijzen": "Assign",
    "Kamers toevoegen": "Add rooms",
    "101-120 of 12, 14, 16": "101-120 or 12, 14, 16",
    "Bedden per kamer": "Beds per room",
    "{n} kamers toevoegen": "Add {n} rooms",
    "Kamer toevoegen": "Add room",
    "Maandag": "Monday",
    "Dinsdag": "Tuesday",
    "Woensdag": "Wednesday",
    "Donderdag": "Thursday",
    "Vrijdag": "Friday",
    "Zaterdag": "Saturday",
    "Zondag": "Sunday",
    "De vaste dag en de activiteiten van het huis. Wat hier staat, staat ook op de tablets.": "The daily routine and the activities of the home. What is shown here is also on the tablets.",
    "Afdrukken": "Print",
    "Vorige week": "Previous week",
    "Deze week": "This week",
    "Volgende week": "Next week",
    "Alle afdelingen": "All units",
    "afdeling {naam}": "unit {naam}",
    "week van {datum}": "week of {datum}",
    "Er staat deze week nog niets. Vul bij Activiteiten de vaste dag in (ontbijt, middagmaal, rust) en plan activiteiten.": "Nothing is planned this week yet. Fill in the daily routine under Activities (breakfast, lunch, rest) and plan activities.",
    "vandaag": "today",
    "Niets gepland": "Nothing planned",
    "vaste dag": "daily routine",
    "activiteit": "activity",
    "Deze maand": "This month",
    "Vorige maand": "Last month",
    "Laatste 30 dagen": "Last 30 days",
    "Dit jaar": "This year",
    "Wat er in het huis gebeurt, in aantallen.": "What happens in the home, in numbers.",
    "Download (CSV)": "Download (CSV)",
    "Zelf kiezen": "Custom",
    "Tot en met": "Up to and including",
    "{van} tot en met {tot}": "{van} to {tot} inclusive",
    "De rapporten zijn er na de update van de database (83).": "Reports will be available after the database update (83).",
    "Pas vanaf 5 bewoners en 28 dagen": "Only from 5 residents and 28 days",
    "Per afdeling": "Per unit",
    "Aanwezigheden": "Attendances",
    "Alleen aantallen, nooit namen of iets over één bewoner. Bezoeken en uitstappen tellen pas mee als er in die periode minstens vijf bewoners waren, over minstens 28 dagen.": "Only numbers, never names or anything about an individual resident. Visits and outings only count if there were at least five residents in that period, over at least 28 days.",
    "Uitstap vandaag": "Outing today",
    "met {wie}": "with {wie}",
    "nog niet terug": "not back yet",
    "vertrokken": "left",
    "gepland": "planned",
    "Vertrokken": "Left",
    "Is terug": "Is back",
    "Kwijt op de afdeling": "Missing in the unit",
    "van {bewoner}": "belonging to {bewoner}",
    "kamer {kamer}": "room {kamer}",
    "hoort: {waar}": "belongs: {waar}",
    "Gevonden": "Found",
    "Er ging iets mis. Probeer het opnieuw.": "Something went wrong. Please try again.",
    "Bezig met laden…": "Loading…",
    "Nu in het woonzorgcentrum": "Currently in the care home",
    "Opnames": "Admissions",
    "Nieuwe bewoners in deze periode": "New residents in this period",
    "Vertrekken": "Departures",
    "Verblijven die afliepen": "Stays that ended",
    "Gepland, zonder de geannuleerde": "Planned, excluding cancelled ones",
    "Keer dat een bewoner erbij was": "Times a resident took part",
    "Deelnemers": "Participants",
    "Verschillende bewoners die meededen": "Different residents who took part",
    "Bezoeken": "Visits",
    "Vastgelegd in \"Wie was er hier?\"": "Recorded in \"Who was here?\"",
    "Uitstappen": "Outings",
    "Met de familie, echt vertrokken": "With the family, actually departed",
    "Nieuwsberichten": "News items",
    "Verstuurd aan de families": "Sent to families",
    "Periode": "Period",
    "Cijfer": "Figure",
    "Waarde": "Value",
    "Totaal": "Total",
    "niet getoond (minder dan 5 bewoners of korter dan 28 dagen)": "not shown (fewer than 5 residents or shorter than 28 days)",
    "Alleen de beheerder of een coördinator past kamers aan.": "Only the administrator or a coordinator can change rooms.",
    "Alleen de beheerder of een coördinator wist kamers.": "Only the administrator or a coordinator can delete rooms.",
    "Zonder afdeling": "Without a unit",
    "Bril": "Glasses",
    "Gebit": "Dentures",
    "Hoorapparaat": "Hearing aid",
    "Kleding": "Clothing",
    "Sieraad": "Jewellery",
    "Hulpmiddel": "Mobility aid",
    "Dit kan je niet wissen.": "You can't delete this.",
    "net gemeld": "just reported",
    "sinds {n} uur": "for {n} hours",
    "sinds gisteren": "since yesterday",
    "sinds {n} dagen": "for {n} days",
    "Dit bericht kan je niet wissen.": "You can't delete this message.",
    "Van {van} · afdeling {afdeling}": "From {van} · unit {afdeling}",
    "Van {van}": "From {van}",
    "terug": "back",
    "Uitstap": "Outing",
    "Neem je {naam} mee? Meld het hier, dan weet het zorgteam waar {naam} is en zegt de tablet wie er komt.": "Taking {naam} out? Let us know here, so the care team knows where {naam} is and the tablet says who is coming.",
    "Wie {naam} meeneemt, en wanneer ze terug is.": "Who is taking {naam} out, and when they will be back.",
    "Uitstap melden": "Report an outing",
    "Met {wie}": "With {wie}",
    "Deze uitstap annuleren?": "Cancel this outing?",
    "Annuleren": "Cancel",
    "Terug moet na het vertrek liggen.": "The return must be after the departure.",
    "Met wie": "With whom",
    "Els": "Els",
    "Vertrek": "Departure",
    "Terug": "Return",
    "Waar naartoe (mag leeg)": "Where to (optional)",
    "Naar de markt en daarna bij ons eten": "To the market and then dinner at ours",
    "Melden": "Report",
    "Spullen van {naam}": "{naam}'s belongings",
    "{n} kwijt": "{n} missing",
    "Bril, gebit, hoorapparaat, gemerkte kleding: met een foto en waar het hoort. Raakt iets kwijt, dan zoekt de hele afdeling mee.": "Glasses, dentures, hearing aid, labelled clothing: with a photo and where it belongs. If something goes missing, the whole unit helps look for it.",
    "Minder tonen": "Show less",
    "Alle {n} spullen": "All {n} belongings",
    "Hoort: {waar}": "Belongs: {waar}",
    "Kwijt": "Missing",
    "Andere foto": "Different photo",
    "Foto": "Photo",
    "Leesbril": "Reading glasses",
    "Herkenbaar aan (mag leeg)": "Recognisable by (optional)",
    "Rood montuur, naam binnenin": "Red frame, name inside",
    "Waar het hoort (mag leeg)": "Where it belongs (optional)",
    "Op het nachtkastje": "On the bedside table",
    "Bewaren": "Save",
    "{naam} ingeschreven": "{naam} signed up",
    "{naam} was erbij": "{naam} was there",
    "{naam} was er niet bij": "{naam} was not there",
    "Vandaag in het woonzorgcentrum": "Today in the care home",
    "Gepland door het woonzorgcentrum.": "Planned by the care home.",
    "Nieuws van {van}": "News from {van}",
    "nieuw": "new",
    "Alle {n} berichten": "All {n} messages",
    "Systeemcontrole": "System check",
    "Draai in Supabase de update": "Run the update in Supabase:",
    "dan zie je hier welke andere updates nog ontbreken.": "you will then see here which other updates are still missing.",
    "De controle lukte nu niet. Probeer het later opnieuw.": "The check didn't work just now. Please try again later.",
    "Alle {n} updates van de database staan erin.": "All {n} database updates are in place.",
    "Eén update ontbreekt.": "One update is missing.",
    "{n} updates ontbreken.": "{n} updates are missing.",
    "Draai ze in Supabase, in deze volgorde. Tot dan werken deze onderdelen niet of maar half.": "Run them in Supabase, in this order. Until then these parts won't work, or only partly.",
    "Proefperiode": "Trial",
    "Pilot": "Pilot",
    "Actief": "Active",
    "Betaling openstaand": "Payment outstanding",
    "Gepauzeerd": "Paused",
    "Stopgezet": "Cancelled",
    "Jouw abonnement": "Your subscription",
    "tot {datum}": "until {datum}",
    "Je gebruikt alles van LifeAngle, en er wordt nog niets aangerekend.": "You're using all of LifeAngle, and nothing is being charged yet.",
    "Met {n} bewoner zou Care {bedrag} per maand kosten": "With {n} resident, Care would cost {bedrag} per month",
    "Met {n} bewoners zou Care {bedrag} per maand kosten": "With {n} residents, Care would cost {bedrag} per month",
    "(excl. btw)": "(excl. VAT)",
    "Bekijk de prijzen": "View pricing",
    "Wat kost LifeAngle?": "What does LifeAngle cost?",
    "Eén prijs per huishouden, met zoveel familieleden als je wil. Voor een woonzorgcentrum: per bewoner die er echt verblijft.": "One price per household, with as many family members as you like. For a care home: per resident actually staying there.",
    "Prijzen onder voorbehoud. Er wordt nu nog niets aangerekend.": "Prices subject to change. Nothing is being charged yet.",
    "Voor wie": "For whom",
    "Voor families": "For families",
    "Voor woonzorgcentra": "For care homes",
    "Per jaar betalen": "Pay yearly",
    "De prijzen zijn nog niet ingesteld.": "Prices have not been set yet.",
    "Goed om te weten": "Good to know",
    "Alle familieleden, de tablet van de persoon en zorgverleners: inbegrepen, zonder meerprijs.": "All family members, the person's tablet and carers: included, at no extra cost.",
    "Verblijft iemand in een woonzorgcentrum dat LifeAngle Care gebruikt, dan betaalt de familie niets extra.": "If someone lives in a care home that uses LifeAngle Care, the family pays nothing extra.",
    "Opzeggen kan altijd. Je gegevens kan je eerst downloaden.": "You can cancel at any time. You can download your data first.",
    "Woonzorgcentrum?": "Care home?",
    "Je betaalt alleen voor bewoners die die maand echt verblijven, niet voor bedden of medewerkers. Begin met een pilot op één afdeling.": "You only pay for residents actually staying that month, not for beds or staff. Start with a pilot in one unit.",
    "Een woonzorgcentrum registreren": "Register a care home",
    "per bewoner per maand": "per resident per month",
    "per jaar": "per year",
    "per maand": "per month",
    "Gratis": "Free",
    "btw inbegrepen": "VAT included",
    "excl. btw": "excl. VAT",
    "minimum {bedrag} per maand": "minimum {bedrag} per month",
    "{n} maand gratis": "{n} month free",
    "{n} maanden gratis": "{n} months free",
    "{n} dagen gratis proberen": "{n}-day free trial",
    "Wat zit erin": "What's included",
    // Prijzen bij de livegang (86) en teksten uit de database
    "Eén prijs per huishouden, met zoveel familieleden als je wil. Voor een woonzorgcentrum maken we een voorstel op maat.": "One price per household, with as many family members as you like. For a care home, we make a tailored proposal.",
    "We maken een voorstel op maat, op basis van het aantal bewoners. Begin met een pilot op één afdeling.": "We make a tailored proposal based on the number of residents. Start with a pilot on one ward.",
    "Prijsaanvraag LifeAngle Care": "Price request LifeAngle Care",
    "Vraag een prijs aan": "Request a price",
    "Prijs op aanvraag": "Price on request",
    "Daarna {bedrag} per jaar. Opzeggen kan altijd.": "Then {bedrag} per year. Cancel anytime.",
    "Daarna {bedrag} per maand. Opzeggen kan altijd.": "Then {bedrag} per month. Cancel anytime.",
    "Home gratis": "Home free",
    "Home met AI": "Home with AI",
    "Care met AI": "Care with AI",
    "Alles voor thuis: de dag, familie, medicatie, routines, Home Memory, documenten en de spraakassistent.": "Everything for home: the day, family, medication, routines, Home Memory, documents and the voice assistant.",
    "Voor woonzorgcentra: zorgnotities, overdracht, team, activiteiten, kamers en beheer.": "For care homes: care notes, handover, team, activities, rooms and management.",
    "De dag, berichten, familie en herinneringen. Voor altijd gratis.": "The day, messages, family and memories. Free forever.",
    "Alles voor thuis: medicatie, routines, Home Memory, familieportaal en analyse.": "Everything for home: medication, routines, Home Memory, family portal and analysis.",
    "Home, plus de spraakassistent die antwoordt uit jullie eigen gegevens.": "Home, plus the voice assistant that answers from your own data.",
    "Voor woonzorgcentra: zorgnotities, overdracht, team, activiteiten en beheer.": "For care homes: care notes, handover, team, activities and management.",
    "Care, plus de spraakassistent voor bewoners en medewerkers.": "Care, plus the voice assistant for residents and staff.",
    "Agenda": "Calendar",
    "Contacten": "Contacts",
    "Verhalen en dagboek": "Stories and diary",
    "Herinneringen en foto's": "Memories and photos",
    "Spraak zonder AI": "Voice without AI",
    "Radio": "Radio",
    "Videobellen": "Video calls",
    "Familieportaal": "Family portal",
    "Spraak met AI": "Voice with AI",
    "Spraak naar tekst": "Speech to text",
    "Vragen uit eigen gegevens": "Questions from your own data",
    "Teamberichten": "Team messages",
    "Overzicht organisatie": "Organisation overview",
    "Rapporten met rendement": "Reports with return on investment",
    "Companion-toestel": "Companion device",
    "Toestellen per kamer": "Devices per room",
    "Koppeling met het EPD": "Link with the electronic health record",
  },
} satisfies Vertaling
